# SPDX-License-Identifier: Apache-2.0
version: 2

build:
  os: debian
  image: ghcr.io/linux-nvme/debian:latest
  tools:
    python: "3.11"

  commands:
    - scripts/build.sh docs
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp .build-ci/*.html > $READTHEDOCS_OUTPUT/html/
    - mv $READTHEDOCS_OUTPUT/html/nvme.html $READTHEDOCS_OUTPUT/html/index.html

formats: []
