# SPDX-License-Identifier: Apache-2.0
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

  apt_packages:
    - meson
    - python3-lxml
    - docbook-xsl
    - xsltproc
    - pandoc
    - asciidoc
    - xmlto

  commands:
    - pip install lxml
    - scripts/build.sh docs
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp .build-ci/*.html > $READTHEDOCS_OUTPUT/html/
    - mv $READTHEDOCS_OUTPUT/html/nvme.html $READTHEDOCS_OUTPUT/html/index.html

formats: []
