---
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of nvme.
# Copyright (c) 2026 SUSE LLC
#
# Authors: Daniel Wagner <dwagner@suse.de>

ignore:
  - 'subprojects'
  - 'ccan'
  - '.build-ci'
  - 'tests'
  - 'libnvme/tests'
  - 'libnvme/examples'
  - 'shared/tests'
  - 'discoverd/tests'
  - 'keysd/tests'

coverage:
  status:
    project: off
    patch: off
