.TH "libnvmf_context_get_trsvcid" 9 "libnvmf_context_get_trsvcid" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_trsvcid \- Get trsvcid.
.SH SYNOPSIS
.B "const char *" libnvmf_context_get_trsvcid
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the trsvcid field, or NULL if not set.
