.TH "libnvme_ns_set_name" 9 "libnvme_ns_set_name" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_set_name \- Set name.
.SH SYNOPSIS
.B "void" libnvme_ns_set_name
.BI "(struct libnvme_ns *p "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to update.
.IP "name" 12
New string; a copy is stored. Pass NULL to clear.
