.TH "libnvme_path_update_stat" 9 "libnvme_path_update_stat" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_update_stat \- Update stat of an nvme_path_t object
.SH SYNOPSIS
.B "int" libnvme_path_update_stat
.BI "(libnvme_path_t p "  ","
.BI "bool diffstat "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.IP "diffstat" 12
If set to true then getters return the diff stat otherwise
return the current absolute stat
.SH "RETURN"
0 on success, negative error code otherwise.
