.TH "libnvme_subsystem_get_iopolicy" 9 "libnvme_subsystem_get_iopolicy" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_get_iopolicy \- Get subsystem iopolicy name
.SH SYNOPSIS
.B "char *" libnvme_subsystem_get_iopolicy
.BI "(libnvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
subsystem
.SH "RETURN"
The iopolicy configured in subsystem \fIs\fP
