.TH "libnvme_ns_head_get_sysfs_dir" 9 "libnvme_ns_head_get_sysfs_dir" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_head_get_sysfs_dir \- sysfs dir of namespave head
.SH SYNOPSIS
.B "const char *" libnvme_ns_head_get_sysfs_dir
.BI "(libnvme_ns_head_t head "  ");"
.SH ARGUMENTS
.IP "head" 12
namespace head instance
.SH "RETURN"
sysfs directory name of \fIhead\fP
