.TH "libnvme_scan_ns_head_paths" 9 "libnvme_scan_ns_head_paths" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_scan_ns_head_paths \- Scan for namespace paths
.SH SYNOPSIS
.B "int" libnvme_scan_ns_head_paths
.BI "(libnvme_ns_head_t head "  ","
.BI "struct dirent ***paths "  ");"
.SH ARGUMENTS
.IP "head" 12
Namespace head node to scan
.IP "paths" 12
Pointer to array of dirents
.SH "RETURN"
number of entries in \fIents\fP or a negative error code
