.TH "libnvmf_discovery_args_set_max_retries" 9 "libnvmf_discovery_args_set_max_retries" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_discovery_args_set_max_retries \- Set max_retries.
.SH SYNOPSIS
.B "void" libnvmf_discovery_args_set_max_retries
.BI "(struct libnvmf_discovery_args *p "  ","
.BI "int max_retries "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_discovery_args\fP instance to update.
.IP "max_retries" 12
Value to assign to the max_retries field.
