.TH "libnvmf_uri_free" 9 "libnvmf_uri_free" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_uri_free \- Free the URI structure
.SH SYNOPSIS
.B "void" libnvmf_uri_free
.BI "(struct libnvmf_uri *uri "  ");"
.SH ARGUMENTS
.IP "uri" 12
\fIlibnvme_fabrics_uri\fP structure
.SH "DESCRIPTION"
Free an \fIlibnvmf_uri\fP structure.
