.TH "libnvme_ns_set_nsid" 9 "libnvme_ns_set_nsid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_set_nsid \- Set nsid.
.SH SYNOPSIS
.B "void" libnvme_ns_set_nsid
.BI "(struct libnvme_ns *p "  ","
.BI "__u32 nsid "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to update.
.IP "nsid" 12
Value to assign to the nsid field.
