.TH "libnvmf_context_set_default_keep_alive_timeout" 9 "libnvmf_context_set_default_keep_alive_timeout" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_default_keep_alive_timeout \- Setter.
.SH SYNOPSIS
.B "void" libnvmf_context_set_default_keep_alive_timeout
.BI "(struct libnvmf_context *p "  ","
.BI "int default_keep_alive_timeout "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to update.
.IP "default_keep_alive_timeout" 12
New value.
