.TH "libnvme_fabric_options_set_tls_key" 9 "libnvme_fabric_options_set_tls_key" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_tls_key \- Set tls_key.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_tls_key
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool tls_key "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "tls_key" 12
Value to assign to the tls_key field.
