.TH "libnvme_host_get_global_ctx" 9 "libnvme_host_get_global_ctx" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_host_get_global_ctx \- Returns libnvme_global_ctx object
.SH SYNOPSIS
.B "struct libnvme_global_ctx *" libnvme_host_get_global_ctx
.BI "(libnvme_host_t h "  ");"
.SH ARGUMENTS
.IP "h" 12
\fIlibnvme_host_t\fP object
.SH "RETURN"
\fIstruct libnvme_global_ctx\fP object from \fIh\fP
