.TH "libnvme_path_get_grpid" 9 "libnvme_path_get_grpid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_grpid \- Get grpid.
.SH SYNOPSIS
.B "int" libnvme_path_get_grpid
.BI "(const struct libnvme_path *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_path\fP instance to query.
.SH "RETURN"
The value of the grpid field.
