.TH "libnvme_get_ioctl_probing" 9 "libnvme_get_ioctl_probing" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_get_ioctl_probing \- Get ioctl_probing.
.SH SYNOPSIS
.B "bool" libnvme_get_ioctl_probing
.BI "(const struct libnvme_global_ctx *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_global_ctx\fP instance to query.
.SH "RETURN"
The value of the ioctl_probing field.
