.TH "libnvme_first_subsystem" 9 "libnvme_first_subsystem" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_first_subsystem \- Start subsystem iterator
.SH SYNOPSIS
.B "libnvme_subsystem_t" libnvme_first_subsystem
.BI "(libnvme_host_t h "  ");"
.SH ARGUMENTS
.IP "h" 12
\fIlibnvme_host_t\fP object
.SH "RETURN"
first \fIlibnvme_subsystem_t\fP object in an iterator
