.TH "libnvme_ns_get_inflights" 9 "libnvme_ns_get_inflights" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_inflights \- Inflight IOs for nvme_ns_t object
.SH SYNOPSIS
.B "unsigned int" libnvme_ns_get_inflights
.BI "(struct libnvme_ns *n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIstruct libnvme_ns\fP object
.SH "RETURN"
Inflight number of IOs
