.TH "libnvme_mi_mi_pda_write" 9 "libnvme_mi_mi_pda_write" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_mi_mi_pda_write \- Write the NVMe-MI Persistent Data Area (PDA)
.SH SYNOPSIS
.B "int" libnvme_mi_mi_pda_write
.BI "(struct libnvme_mi_ep *ep "  ","
.BI "enum nvme_mi_pda_dformat dformat "  ","
.BI "__u32 dofst "  ","
.BI "__u32 dlen "  ","
.BI "void *data "  ","
.BI "size_t data_len "  ");"
.SH ARGUMENTS
.IP "ep" 12
endpoint for MI communication
.IP "dformat" 12
data format to use for \fIdofst\fP and \fIdlen\fP, see
\fIenum nvme_mi_pda_dformat\fP
.IP "dofst" 12
starting offset, in units of \fIdformat\fP, into the PDA to write
.IP "dlen" 12
length, in units of \fIdformat\fP, of \fIdata\fP to write to the PDA
starting at \fIdofst\fP
.IP "data" 12
data to write to the PDA
.IP "data_len" 12
length of \fIdata\fP
.SH "DESCRIPTION"
Performs an NVMe-MI PDA Write command.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or negative error code otherwise.
