.TH "libnvme_subsystem_get_host" 9 "libnvme_subsystem_get_host" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_get_host \- Returns libnvme_host_t object
.SH SYNOPSIS
.B "libnvme_host_t" libnvme_subsystem_get_host
.BI "(libnvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
subsystem
.SH "RETURN"
\fIlibnvme_host_t\fP object from \fIs\fP
