.TH "libnvme_ns_get_read_ios" 9 "libnvme_ns_get_read_ios" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_read_ios \- Get num of read I/Os
.SH SYNOPSIS
.B "unsigned long" libnvme_ns_get_read_ios
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIlibnvme_ns_t\fP object
.SH "RETURN"
Num of read IOs processed between two stat samples
