.TH "libnvme_fabric_options_set_dhchap_secret" 9 "libnvme_fabric_options_set_dhchap_secret" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_dhchap_secret \- Set dhchap_secret.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_dhchap_secret
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool dhchap_secret "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "dhchap_secret" 12
Value to assign to the dhchap_secret field.
