.TH "libnvme_dump_tree" 9 "libnvme_dump_tree" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_dump_tree \- Dump internal object tree
.SH SYNOPSIS
.B "int" libnvme_dump_tree
.BI "(struct libnvme_global_ctx *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
\fIstruct libnvme_global_ctx\fP object
.SH "DESCRIPTION"
Prints the internal object tree in JSON format
to stdout.
.SH "RETURN"
0 on success or negative error code otherwise
