.TH "libnvme_exec_io_passthru" 9 "libnvme_exec_io_passthru" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_exec_io_passthru \- Submit an IO passthru command and wait
.SH SYNOPSIS
.B "int" libnvme_exec_io_passthru
.BI "(struct libnvme_transport_handle *hdl "  ","
.BI "struct libnvme_passthru_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "hdl" 12
Transport handle
.IP "cmd" 12
The nvme IO command to send
.SH "DESCRIPTION"
Synchronous command execution. Note: when io_uring is enabled, this shares
the async queue. Avoid mixing this with direct async API usage on the same
handle. For batching, use the async API exclusively.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP), or negative error code otherwise.
