.TH "libnvme_ctrl_for_each_path" 9 "libnvme_ctrl_for_each_path" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_for_each_path \- Traverse paths
.SH SYNOPSIS
.B "libnvme_ctrl_for_each_path
.BI "(c "  ","
.BI "p "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "p" 12
\fIlibnvme_path_t\fP object
