.TH "libnvme_ctrl_set_discovered" 9 "libnvme_ctrl_set_discovered" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_set_discovered \- Set discovered.
.SH SYNOPSIS
.B "void" libnvme_ctrl_set_discovered
.BI "(struct libnvme_ctrl *p "  ","
.BI "bool discovered "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to update.
.IP "discovered" 12
Value to assign to the discovered field.
