.TH "libnvme_first_host" 9 "libnvme_first_host" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_first_host \- Start host iterator
.SH SYNOPSIS
.B "struct libnvme_host *" libnvme_first_host
.BI "(struct libnvme_global_ctx *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct libnvme_global_ctx object
.SH "RETURN"
First \fIstruct libnvme_host\fP object in an iterator
