.TH "libnvme_fabric_options_set_nr_poll_queues" 9 "libnvme_fabric_options_set_nr_poll_queues" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_nr_poll_queues \- Set nr_poll_queues.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_nr_poll_queues
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool nr_poll_queues "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "nr_poll_queues" 12
Value to assign to the nr_poll_queues field.
