.TH "libnvme_subsystem_first_ctrl" 9 "libnvme_subsystem_first_ctrl" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_first_ctrl \- First ctrl iterator
.SH SYNOPSIS
.B "libnvme_ctrl_t" libnvme_subsystem_first_ctrl
.BI "(libnvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
\fIlibnvme_subsystem_t\fP object
.SH "RETURN"
First controller of an \fIs\fP iterator
