.TH "libnvme_fabrics_config_get_nr_io_queues" 9 "libnvme_fabrics_config_get_nr_io_queues" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_get_nr_io_queues \- Get nr_io_queues.
.SH SYNOPSIS
.B "int" libnvme_fabrics_config_get_nr_io_queues
.BI "(const struct libnvme_fabrics_config *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to query.
.SH "RETURN"
The value of the nr_io_queues field.
