.TH "libnvmf_context_set_nr_poll_queues" 9 "libnvmf_context_set_nr_poll_queues" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_nr_poll_queues \- Set nr_poll_queues.
.SH SYNOPSIS
.B "void" libnvmf_context_set_nr_poll_queues
.BI "(struct libnvmf_context *p "  ","
.BI "int nr_poll_queues "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to update.
.IP "nr_poll_queues" 12
Value to assign to the nr_poll_queues field.
