.TH "libnvme_ctrl_get_reset_count" 9 "libnvme_ctrl_get_reset_count" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_reset_count \- Get controller reset count
.SH SYNOPSIS
.B "long" libnvme_ctrl_get_reset_count
.BI "(libnvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
Number of timer controller \fIc\fP is reset
