.TH "libnvme_ctrl_get_tls_configured_key_id" 9 "libnvme_ctrl_get_tls_configured_key_id" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_tls_configured_key_id \- Get tls_configured_key_id.
.SH SYNOPSIS
.B "long" libnvme_ctrl_get_tls_configured_key_id
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the tls_configured_key_id field.
