.TH "libnvme_ctrl_get_persistent" 9 "libnvme_ctrl_get_persistent" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_persistent \- Get persistent.
.SH SYNOPSIS
.B "bool" libnvme_ctrl_get_persistent
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the persistent field.
