.TH "libnvme_ns_get_meta_size" 9 "libnvme_ns_get_meta_size" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_meta_size \- Get meta_size.
.SH SYNOPSIS
.B "int" libnvme_ns_get_meta_size
.BI "(const struct libnvme_ns *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to query.
.SH "RETURN"
The value of the meta_size field.
