.TH "libnvme_ns_get_command_error_count" 9 "libnvme_ns_get_command_error_count" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_command_error_count \- Get command error count
.SH SYNOPSIS
.B "long" libnvme_ns_get_command_error_count
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIlibnvme_ns_t\fP object
.SH "RETURN"
Number of times command issued to namespace \fIn\fP returns non-zero
status or error
