.TH "libnvme_ctrl_set_unique_discovery_ctrl" 9 "libnvme_ctrl_set_unique_discovery_ctrl" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_set_unique_discovery_ctrl \- Set unique_discovery_ctrl.
.SH SYNOPSIS
.B "void" libnvme_ctrl_set_unique_discovery_ctrl
.BI "(struct libnvme_ctrl *p "  ","
.BI "bool unique_discovery_ctrl "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to update.
.IP "unique_discovery_ctrl" 12
Value to assign to the unique_discovery_ctrl field.
