.TH "libnvme_scan_subsystems" 9 "libnvme_scan_subsystems" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_scan_subsystems \- Scan for subsystems
.SH SYNOPSIS
.B "int" libnvme_scan_subsystems
.BI "(struct dirent ***subsys "  ");"
.SH ARGUMENTS
.IP "subsys" 12
Pointer to array of dirents
.SH "RETURN"
number of entries in \fIsubsys\fP or a negative error code
