.TH "libnvme_host_release_fds" 9 "libnvme_host_release_fds" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_host_release_fds \- Close all opened file descriptors under host
.SH SYNOPSIS
.B "void" libnvme_host_release_fds
.BI "(struct libnvme_host *h "  ");"
.SH ARGUMENTS
.IP "h" 12
libnvme_host_t object
.SH "DESCRIPTION"
Controller and Namespace objects cache the file descriptors
of opened nvme devices. This API can be used to close and
clear all cached fds under this host.
