.TH "libnvmf_context_get_tls" 9 "libnvmf_context_get_tls" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_tls \- Get tls.
.SH SYNOPSIS
.B "bool" libnvmf_context_get_tls
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the tls field.
