.TH "libnvmf_context_get_tos" 9 "libnvmf_context_get_tos" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_tos \- Get tos.
.SH SYNOPSIS
.B "int" libnvmf_context_get_tos
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the tos field.
