.TH "libnvme_generate_hostid" 9 "libnvme_generate_hostid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_generate_hostid \- Generate a machine specific host identifier
.SH SYNOPSIS
.B "char *" libnvme_generate_hostid
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
On success, an identifier string based on the machine identifier to
be used as NVMe Host Identifier, or NULL on failure.
