.TH "libnvme_fabric_options_set_hostnqn" 9 "libnvme_fabric_options_set_hostnqn" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_hostnqn \- Set hostnqn.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_hostnqn
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool hostnqn "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "hostnqn" 12
Value to assign to the hostnqn field.
