.TH "libnvme_fabric_options_get_trsvcid" 9 "libnvme_fabric_options_get_trsvcid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_get_trsvcid \- Get trsvcid.
.SH SYNOPSIS
.B "bool" libnvme_fabric_options_get_trsvcid
.BI "(const struct libnvme_fabric_options *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to query.
.SH "RETURN"
The value of the trsvcid field.
