.TH "libnvme_host_get_pdc_enabled_valid" 9 "libnvme_host_get_pdc_enabled_valid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_host_get_pdc_enabled_valid \- Get pdc_enabled_valid.
.SH SYNOPSIS
.B "bool" libnvme_host_get_pdc_enabled_valid
.BI "(const struct libnvme_host *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_host\fP instance to query.
.SH "RETURN"
The value of the pdc_enabled_valid field.
