.TH "libnvmf_context_get_hostkey" 9 "libnvmf_context_get_hostkey" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_hostkey \- Get hostkey.
.SH SYNOPSIS
.B "const char *" libnvmf_context_get_hostkey
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the hostkey field, or NULL if not set.
