.TH "libnvme_for_each_host_safe" 9 "libnvme_for_each_host_safe" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_for_each_host_safe \- Traverse host list
.SH SYNOPSIS
.B "libnvme_for_each_host_safe
.BI "(r "  ","
.BI "h "  ","
.BI "_h "  ");"
.SH ARGUMENTS
.IP "r" 12
\fIlibnvme_root_t\fP object
.IP "h" 12
\fIlibnvme_host_t\fP object
.IP "_h" 12
Temporary \fIlibnvme_host_t\fP object
