.TH "libnvme_ctrl_get_queue_size" 9 "libnvme_ctrl_get_queue_size" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_queue_size \- Get queue_size.
.SH SYNOPSIS
.B "int" libnvme_ctrl_get_queue_size
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the queue_size field.
