.TH "libnvmf_context_set_connection" 9 "libnvmf_context_set_connection" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_connection \- Set connection parameters for context
.SH SYNOPSIS
.B "int" libnvmf_context_set_connection
.BI "(struct libnvmf_context *fctx "  ","
.BI "const char *subsysnqn "  ","
.BI "const char *transport "  ","
.BI "const char *traddr "  ","
.BI "const char *trsvcid "  ","
.BI "const char *host_traddr "  ","
.BI "const char *host_iface "  ");"
.SH ARGUMENTS
.IP "fctx" 12
Fabrics context
.IP "subsysnqn" 12
Subsystem NQN
.IP "transport" 12
Transport type
.IP "traddr" 12
Transport address
.IP "trsvcid" 12
Transport service ID
.IP "host_traddr" 12
Host transport address
.IP "host_iface" 12
Host interface
.SH "DESCRIPTION"
Sets the connection parameters for the context.
.SH "RETURN"
0 on success, or a negative error code on failure.
