.TH "libnvme_fabrics_config_set_tls_key_id" 9 "libnvme_fabrics_config_set_tls_key_id" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_set_tls_key_id \- Set tls_key_id.
.SH SYNOPSIS
.B "void" libnvme_fabrics_config_set_tls_key_id
.BI "(struct libnvme_fabrics_config *p "  ","
.BI "long tls_key_id "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to update.
.IP "tls_key_id" 12
Value to assign to the tls_key_id field.
