.TH "libnvme_ns_set_meta_size" 9 "libnvme_ns_set_meta_size" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_set_meta_size \- Set meta_size.
.SH SYNOPSIS
.B "void" libnvme_ns_set_meta_size
.BI "(struct libnvme_ns *p "  ","
.BI "int meta_size "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to update.
.IP "meta_size" 12
Value to assign to the meta_size field.
