.TH "libnvmf_uri_get_path_segments" 9 "libnvmf_uri_get_path_segments" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_uri_get_path_segments \- Get path_segments.
.SH SYNOPSIS
.B "const char *const *" libnvmf_uri_get_path_segments
.BI "(const struct libnvmf_uri *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_uri\fP instance to query.
.SH "RETURN"
The value of the path_segments field.
