.TH "libnvme_fabric_options_get_nr_poll_queues" 9 "libnvme_fabric_options_get_nr_poll_queues" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_get_nr_poll_queues \- Get nr_poll_queues.
.SH SYNOPSIS
.B "bool" libnvme_fabric_options_get_nr_poll_queues
.BI "(const struct libnvme_fabric_options *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to query.
.SH "RETURN"
The value of the nr_poll_queues field.
