.TH "libnvmf_discovery_args_free" 9 "libnvmf_discovery_args_free" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_discovery_args_free \- Release a discovery args object
.SH SYNOPSIS
.B "void" libnvmf_discovery_args_free
.BI "(struct libnvmf_discovery_args *args "  ");"
.SH ARGUMENTS
.IP "args" 12
Object previously returned by \fBlibnvmf_discovery_args_create\fP
