.TH "libnvme_ns_get_stat_interval" 9 "libnvme_ns_get_stat_interval" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_stat_interval \- Get interval between two stat samples
.SH SYNOPSIS
.B "double" libnvme_ns_get_stat_interval
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIlibnvme_ns_t\fP object
.SH "RETURN"
Interval, in milliseconds, between collection of two consecutive
stat samples
