.TH "libnvme_fabric_options_get_dhchap_secret" 9 "libnvme_fabric_options_get_dhchap_secret" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_get_dhchap_secret \- Get dhchap_secret.
.SH SYNOPSIS
.B "bool" libnvme_fabric_options_get_dhchap_secret
.BI "(const struct libnvme_fabric_options *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to query.
.SH "RETURN"
The value of the dhchap_secret field.
