.TH "libnvme_fabric_options_set_discovery" 9 "libnvme_fabric_options_set_discovery" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_discovery \- Set discovery.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_discovery
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool discovery "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "discovery" 12
Value to assign to the discovery field.
