.TH "libnvmf_tid_get_traddr" 9 "libnvmf_tid_get_traddr" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_tid_get_traddr \- Get traddr.
.SH SYNOPSIS
.B "const char *" libnvmf_tid_get_traddr
.BI "(const struct libnvmf_tid *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_tid\fP instance to query.
.SH "RETURN"
The value of the traddr field, or NULL if not set.
