.TH "libnvmf_uri_get_scheme" 9 "libnvmf_uri_get_scheme" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_uri_get_scheme \- Get scheme.
.SH SYNOPSIS
.B "const char *" libnvmf_uri_get_scheme
.BI "(const struct libnvmf_uri *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_uri\fP instance to query.
.SH "RETURN"
The value of the scheme field, or NULL if not set.
