.TH "libnvme_fabrics_config_set_duplicate_connect" 9 "libnvme_fabrics_config_set_duplicate_connect" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_set_duplicate_connect \- Set duplicate_connect.
.SH SYNOPSIS
.B "void" libnvme_fabrics_config_set_duplicate_connect
.BI "(struct libnvme_fabrics_config *p "  ","
.BI "bool duplicate_connect "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to update.
.IP "duplicate_connect" 12
Value to assign to the duplicate_connect field.
