.TH "libnvme_fabric_options_set_keyring" 9 "libnvme_fabric_options_set_keyring" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_keyring \- Set keyring.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_keyring
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool keyring "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "keyring" 12
Value to assign to the keyring field.
