.TH "libnvme_subsystem_lookup_namespace" 9 "libnvme_subsystem_lookup_namespace" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_lookup_namespace \- lookup namespace by NSID
.SH SYNOPSIS
.B "struct libnvme_ns *" libnvme_subsystem_lookup_namespace
.BI "(struct libnvme_subsystem *s "  ","
.BI "__u32 nsid "  ");"
.SH ARGUMENTS
.IP "s" 12
struct libnvme_subsystem object
.IP "nsid" 12
Namespace id
.SH "RETURN"
struct libnvme_ns of the namespace with id \fInsid\fP in subsystem \fIs\fP
