.TH "libnvme_fabrics_config_get_queue_size" 9 "libnvme_fabrics_config_get_queue_size" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_get_queue_size \- Get queue_size.
.SH SYNOPSIS
.B "int" libnvme_fabrics_config_get_queue_size
.BI "(const struct libnvme_fabrics_config *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to query.
.SH "RETURN"
The value of the queue_size field.
