.TH "libnvme_fabric_options_set_tls" 9 "libnvme_fabric_options_set_tls" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_tls \- Set tls.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_tls
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool tls "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "tls" 12
Value to assign to the tls field.
