.TH "libnvme_ns_get_eui64" 9 "libnvme_ns_get_eui64" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_eui64 \- 64-bit eui of a namespace
.SH SYNOPSIS
.B "const uint8_t *" libnvme_ns_get_eui64
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.SH "RETURN"
A pointer to the 64-bit eui
