.TH "libnvme_set_force_4k" 9 "libnvme_set_force_4k" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_set_force_4k \- Set force_4k.
.SH SYNOPSIS
.B "void" libnvme_set_force_4k
.BI "(struct libnvme_global_ctx *p "  ","
.BI "bool force_4k "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_global_ctx\fP instance to update.
.IP "force_4k" 12
Value to assign to the force_4k field.
