.TH "libnvme_first_subsystem" 9 "libnvme_first_subsystem" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_first_subsystem \- Start subsystem iterator
.SH SYNOPSIS
.B "struct libnvme_subsystem *" libnvme_first_subsystem
.BI "(struct libnvme_host *h "  ");"
.SH ARGUMENTS
.IP "h" 12
\fIstruct libnvme_host\fP object
.SH "RETURN"
first \fIstruct libnvme_subsystem\fP object in an iterator
