.TH "libnvme_ctrl_get_nr_write_queues" 9 "libnvme_ctrl_get_nr_write_queues" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_nr_write_queues \- Get nr_write_queues.
.SH SYNOPSIS
.B "int" libnvme_ctrl_get_nr_write_queues
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the nr_write_queues field.
