.TH "libnvme_ctrl_get_host_iface" 9 "libnvme_ctrl_get_host_iface" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_host_iface \- Get host_iface.
.SH SYNOPSIS
.B "const char *" libnvme_ctrl_get_host_iface
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the host_iface field, or NULL if not set.
