.TH "libnvme_ctrl_get_fast_io_fail_tmo" 9 "libnvme_ctrl_get_fast_io_fail_tmo" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_fast_io_fail_tmo \- Get fast_io_fail_tmo.
.SH SYNOPSIS
.B "int" libnvme_ctrl_get_fast_io_fail_tmo
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the fast_io_fail_tmo field.
