.TH "libnvme_path_get_io_ticks" 9 "libnvme_path_get_io_ticks" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_io_ticks \- Get I/O ticks
.SH SYNOPSIS
.B "unsigned int" libnvme_path_get_io_ticks
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
Time consumed, in milliseconds, processing I/O requests between
two stat samples
