.TH "libnvmf_ctrl_get_fabrics_config" 9 "libnvmf_ctrl_get_fabrics_config" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_ctrl_get_fabrics_config \- Fabrics configuration of a controller
.SH SYNOPSIS
.B "struct libnvme_fabrics_config *" libnvmf_ctrl_get_fabrics_config
.BI "(libnvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
Fabrics configuration of \fIc\fP
