.TH "libnvme_fabric_options_set_concat" 9 "libnvme_fabric_options_set_concat" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_concat \- Set concat.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_concat
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool concat "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "concat" 12
Value to assign to the concat field.
