.TH "libnvme_set_keyring" 9 "libnvme_set_keyring" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_set_keyring \- Link keyring for lookup
.SH SYNOPSIS
.B "int" libnvme_set_keyring
.BI "(struct libnvme_global_ctx *ctx "  ","
.BI "long keyring_id "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct libnvme_global_ctx object
.IP "keyring_id" 12
Keyring id
.SH "DESCRIPTION"
Links \fIkeyring_id\fP into the session keyring such that
its keys are available for further key lookups.
.SH "RETURN"
0 on success or negative error code otherwise
