.TH "libnvme_ns_get_command_retry_count" 9 "libnvme_ns_get_command_retry_count" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_command_retry_count \- Get command retry count
.SH SYNOPSIS
.B "long" libnvme_ns_get_command_retry_count
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIlibnvme_ns_t\fP object
.SH "RETURN"
Number of times any command issued to namespace \fIn\fP has to be retried
