.TH "libnvme_fabric_options_set_host_iface" 9 "libnvme_fabric_options_set_host_iface" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_host_iface \- Set host_iface.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_host_iface
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool host_iface "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "host_iface" 12
Value to assign to the host_iface field.
