.TH "libnvmf_context_get_fast_io_fail_tmo" 9 "libnvmf_context_get_fast_io_fail_tmo" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_fast_io_fail_tmo \- Get fast_io_fail_tmo.
.SH SYNOPSIS
.B "int" libnvmf_context_get_fast_io_fail_tmo
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the fast_io_fail_tmo field.
