.TH "libnvme_namespace_for_each_path" 9 "libnvme_namespace_for_each_path" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_namespace_for_each_path \- Traverse paths
.SH SYNOPSIS
.B "libnvme_namespace_for_each_path
.BI "(n "  ","
.BI "p "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.IP "p" 12
\fIlibnvme_path_t\fP object
