.TH "libnvme" 9 "struct libnvme_passthru_completion" "June 2026" "API Manual" LINUX
.SH NAME
struct libnvme_passthru_completion \- Async passthru completion record
.SH SYNOPSIS
struct libnvme_passthru_completion {
.br
.BI "    struct libnvme_passthru_cmd *cmd;"
.br
.BI "    void *cookie;"
.br
.BI "    int status;"
.br
.BI "
};
.br

.SH Members
.IP "cmd" 12
Command that completed
.IP "cookie" 12
User cookie provided to libnvme_submit_*\fB_passthru\fP
.IP "status" 12
Completion status (NVMe status or negative errno)
.SH "Description"
Used for both admin and IO passthru command completions.
