.TH "libnvme_fabric_options_get_fast_io_fail_tmo" 9 "libnvme_fabric_options_get_fast_io_fail_tmo" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_get_fast_io_fail_tmo \- Get fast_io_fail_tmo.
.SH SYNOPSIS
.B "bool" libnvme_fabric_options_get_fast_io_fail_tmo
.BI "(const struct libnvme_fabric_options *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to query.
.SH "RETURN"
The value of the fast_io_fail_tmo field.
