.TH "libnvme_fabric_options_set_reconnect_delay" 9 "libnvme_fabric_options_set_reconnect_delay" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_reconnect_delay \- Set reconnect_delay.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_reconnect_delay
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool reconnect_delay "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "reconnect_delay" 12
Value to assign to the reconnect_delay field.
