.TH "libnvmf_uri_set_protocol" 9 "libnvmf_uri_set_protocol" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_uri_set_protocol \- Set protocol.
.SH SYNOPSIS
.B "void" libnvmf_uri_set_protocol
.BI "(struct libnvmf_uri *p "  ","
.BI "const char *protocol "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_uri\fP instance to update.
.IP "protocol" 12
New string; a copy is stored. Pass NULL to clear.
