.TH "libnvme_host_get_hostid" 9 "libnvme_host_get_hostid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_host_get_hostid \- Get hostid.
.SH SYNOPSIS
.B "const char *" libnvme_host_get_hostid
.BI "(const struct libnvme_host *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_host\fP instance to query.
.SH "RETURN"
The value of the hostid field, or NULL if not set.
