.TH "libnvme_fabric_options_get_hostid" 9 "libnvme_fabric_options_get_hostid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_get_hostid \- Get hostid.
.SH SYNOPSIS
.B "bool" libnvme_fabric_options_get_hostid
.BI "(const struct libnvme_fabric_options *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to query.
.SH "RETURN"
The value of the hostid field.
