.TH "libnvme_fabric_options_set_tos" 9 "libnvme_fabric_options_set_tos" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_tos \- Set tos.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_tos
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool tos "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "tos" 12
Value to assign to the tos field.
