.TH "libnvmf_context_get_disable_sqflow" 9 "libnvmf_context_get_disable_sqflow" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_disable_sqflow \- Get disable_sqflow.
.SH SYNOPSIS
.B "bool" libnvmf_context_get_disable_sqflow
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the disable_sqflow field.
