.TH "libnvme_ns_get_firmware" 9 "libnvme_ns_get_firmware" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_firmware \- Firmware string of a namespace
.SH SYNOPSIS
.B "const char *" libnvme_ns_get_firmware
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.SH "RETURN"
Firmware string of \fIn\fP
