.TH "libnvme_subsystem_get_host" 9 "libnvme_subsystem_get_host" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_get_host \- Returns struct libnvme_host object
.SH SYNOPSIS
.B "struct libnvme_host *" libnvme_subsystem_get_host
.BI "(struct libnvme_subsystem *s "  ");"
.SH ARGUMENTS
.IP "s" 12
subsystem
.SH "RETURN"
\fIstruct libnvme_host\fP object from \fIs\fP
