.TH "libnvme_mi_submit_entry" 9 "libnvme_mi_submit_entry" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_mi_submit_entry \- Weak hook called before an MI message is sent.
.SH SYNOPSIS
.B "void *" libnvme_mi_submit_entry
.BI "(__u8 type "  ","
.BI "const struct nvme_mi_msg_hdr *hdr "  ","
.BI "size_t hdr_len "  ","
.BI "const void *data "  ","
.BI "size_t data_len "  ");"
.SH ARGUMENTS
.IP "type" 12
MCTP message type
.IP "hdr" 12
Pointer to the MI message header
.IP "hdr_len" 12
Length of the message header in bytes
.IP "data" 12
Pointer to message payload data
.IP "data_len" 12
Length of payload data in bytes
.SH "DESCRIPTION"
This is a weak symbol that can be overridden by an application to intercept
outgoing MI messages for tracing or testing purposes.  The return value is
passed back as \fIuser_data\fP to the matching \fBlibnvme_mi_submit_exit\fP call.
.SH "RETURN"
An opaque pointer passed to \fBlibnvme_mi_submit_exit\fP, or NULL.
