.TH "libnvmf_discovery_args_get_max_retries" 9 "libnvmf_discovery_args_get_max_retries" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_discovery_args_get_max_retries \- Get max_retries.
.SH SYNOPSIS
.B "int" libnvmf_discovery_args_get_max_retries
.BI "(const struct libnvmf_discovery_args *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_discovery_args\fP instance to query.
.SH "RETURN"
The value of the max_retries field.
