.TH "libnvme_fabrics_config_set_reconnect_delay" 9 "libnvme_fabrics_config_set_reconnect_delay" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_set_reconnect_delay \- Set reconnect_delay.
.SH SYNOPSIS
.B "void" libnvme_fabrics_config_set_reconnect_delay
.BI "(struct libnvme_fabrics_config *p "  ","
.BI "int reconnect_delay "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to update.
.IP "reconnect_delay" 12
Value to assign to the reconnect_delay field.
