.TH "libnvme_fabrics_config_set_keyring_id" 9 "libnvme_fabrics_config_set_keyring_id" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_set_keyring_id \- Set keyring_id.
.SH SYNOPSIS
.B "void" libnvme_fabrics_config_set_keyring_id
.BI "(struct libnvme_fabrics_config *p "  ","
.BI "long keyring_id "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to update.
.IP "keyring_id" 12
Value to assign to the keyring_id field.
