.TH "libnvme_ns_set_lba_size" 9 "libnvme_ns_set_lba_size" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_set_lba_size \- Set lba_size.
.SH SYNOPSIS
.B "void" libnvme_ns_set_lba_size
.BI "(struct libnvme_ns *p "  ","
.BI "int lba_size "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to update.
.IP "lba_size" 12
Value to assign to the lba_size field.
