.TH "libnvme_ctrl_get_discovered" 9 "libnvme_ctrl_get_discovered" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_discovered \- Get discovered.
.SH SYNOPSIS
.B "bool" libnvme_ctrl_get_discovered
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the discovered field.
