.TH "libnvme_mi_aem_get_enabled" 9 "libnvme_mi_aem_get_enabled" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_mi_aem_get_enabled \- Return information on which AEs are enabled
.SH SYNOPSIS
.B "int" libnvme_mi_aem_get_enabled
.BI "(libnvme_mi_ep_t ep "  ","
.BI "struct libnvme_mi_aem_enabled_map *enabled "  ");"
.SH ARGUMENTS
.IP "ep" 12
Endpoint to check enabled status
.IP "enabled" 12
libnvme_mi_aem_enabled_map indexed by AE event ID of enabled state
.SH "RETURN"
0 is a success, nonzero is an error and errno may be read for further details
