.TH "libnvmf_context_get_default_max_discovery_retries" 9 "libnvmf_context_get_default_max_discovery_retries" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_default_max_discovery_retries \- Getter.
.SH SYNOPSIS
.B "int" libnvmf_context_get_default_max_discovery_retries
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the default_max_discovery_retries field.
