.TH "libnvme_update_block_size" 9 "libnvme_update_block_size" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_update_block_size \- Update the block size
.SH SYNOPSIS
.B "int" libnvme_update_block_size
.BI "(struct libnvme_transport_handle *hdl "  ","
.BI "int block_size "  ");"
.SH ARGUMENTS
.IP "hdl" 12
Transport handle
.IP "block_size" 12
New block size
.SH "DESCRIPTION"
Notify the kernel blkdev to update its block size after a block size change.
This should only be used for namespace handles, not controllers.
.SH "RETURN"
0 if the block size was updated or a negative error code otherwise.
