.TH "libnvme_get_path_attr" 9 "libnvme_get_path_attr" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_get_path_attr \- Read path sysfs attribute
.SH SYNOPSIS
.B "char *" libnvme_get_path_attr
.BI "(struct libnvme_path *p "  ","
.BI "const char *attr "  ");"
.SH ARGUMENTS
.IP "p" 12
struct libnvme_path object
.IP "attr" 12
sysfs attribute name
.SH "RETURN"
A newly allocated string with the contents of \fIattr\fP (the caller
frees), or NULL in case of an empty value or error.
