.TH "libnvme_ctrl_get_tos" 9 "libnvme_ctrl_get_tos" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_tos \- Get tos.
.SH SYNOPSIS
.B "int" libnvme_ctrl_get_tos
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the tos field.
