.TH "libnvme_fabric_options_set_nqn" 9 "libnvme_fabric_options_set_nqn" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_nqn \- Set nqn.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_nqn
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool nqn "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "nqn" 12
Value to assign to the nqn field.
