.TH "libnvme_ctrl_set_persistent" 9 "libnvme_ctrl_set_persistent" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_set_persistent \- Set persistent.
.SH SYNOPSIS
.B "void" libnvme_ctrl_set_persistent
.BI "(struct libnvme_ctrl *p "  ","
.BI "bool persistent "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to update.
.IP "persistent" 12
Value to assign to the persistent field.
