.TH "libnvme_subsystem_release_fds" 9 "libnvme_subsystem_release_fds" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_release_fds \- Close all opened fds under subsystem
.SH SYNOPSIS
.B "void" libnvme_subsystem_release_fds
.BI "(struct libnvme_subsystem *s "  ");"
.SH ARGUMENTS
.IP "s" 12
libnvme_subsystem_t object
.SH "DESCRIPTION"
Controller and Namespace objects cache the file descriptors
of opened nvme devices. This API can be used to close and
clear all cached fds under this subsystem.
