.TH "libnvme_ctrl_for_each_ns" 9 "libnvme_ctrl_for_each_ns" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_for_each_ns \- Traverse namespaces
.SH SYNOPSIS
.B "libnvme_ctrl_for_each_ns
.BI "(c "  ","
.BI "n "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "n" 12
\fIlibnvme_ns_t\fP object
