.TH "libnvme_mi_aem_open" 9 "libnvme_mi_aem_open" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_mi_aem_open \- Prepare an existing endpoint to receive AEMs
.SH SYNOPSIS
.B "int" libnvme_mi_aem_open
.BI "(libnvme_mi_ep_t ep "  ");"
.SH ARGUMENTS
.IP "ep" 12
Endpoint to configure for AEMs
.SH "RETURN"
0 if success, -1 otherwise
