.TH "libnvme_path_get_ctrl" 9 "libnvme_path_get_ctrl" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_ctrl \- Parent controller of an libnvme_path_t object
.SH SYNOPSIS
.B "libnvme_ctrl_t" libnvme_path_get_ctrl
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
Parent controller if present
