.TH "libnvme_fabrics_config_get_tls" 9 "libnvme_fabrics_config_get_tls" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_get_tls \- Get tls.
.SH SYNOPSIS
.B "bool" libnvme_fabrics_config_get_tls
.BI "(const struct libnvme_fabrics_config *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to query.
.SH "RETURN"
The value of the tls field.
