.TH "libnvme_path_get_read_ticks" 9 "libnvme_path_get_read_ticks" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_read_ticks \- Get read I/O ticks
.SH SYNOPSIS
.B "unsigned int" libnvme_path_get_read_ticks
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
Time, in milliseconds, sepnt processing read I/O requests
between two stat samples
