.TH "libnvme_next_host" 9 "libnvme_next_host" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_next_host \- Next host iterator
.SH SYNOPSIS
.B "libnvme_host_t" libnvme_next_host
.BI "(struct libnvme_global_ctx *ctx "  ","
.BI "libnvme_host_t h "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct libnvme_global_ctx object
.IP "h" 12
Previous \fIlibnvme_host_t\fP iterator
.SH "RETURN"
Next \fIlibnvme_host_t\fP object in an iterator
