.TH "libnvme_path_set_grpid" 9 "libnvme_path_set_grpid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_set_grpid \- Set grpid.
.SH SYNOPSIS
.B "void" libnvme_path_set_grpid
.BI "(struct libnvme_path *p "  ","
.BI "int grpid "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_path\fP instance to update.
.IP "grpid" 12
Value to assign to the grpid field.
