.TH "libnvmf_context_set_epcsd" 9 "libnvmf_context_set_epcsd" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_epcsd \- Set epcsd.
.SH SYNOPSIS
.B "void" libnvmf_context_set_epcsd
.BI "(struct libnvmf_context *p "  ","
.BI "enum libnvmf_tristate epcsd "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to update.
.IP "epcsd" 12
Value to assign to the epcsd field.
