.TH "libnvme_ctrl_first_ns" 9 "libnvme_ctrl_first_ns" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_first_ns \- Start namespace iterator
.SH SYNOPSIS
.B "libnvme_ns_t" libnvme_ctrl_first_ns
.BI "(libnvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
First \fIlibnvme_ns_t\fP object of an \fIc\fP iterator
