.TH "libnvme_fabric_options_set_ctrl_loss_tmo" 9 "libnvme_fabric_options_set_ctrl_loss_tmo" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_ctrl_loss_tmo \- Set ctrl_loss_tmo.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_ctrl_loss_tmo
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool ctrl_loss_tmo "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "ctrl_loss_tmo" 12
Value to assign to the ctrl_loss_tmo field.
