.TH "libnvme_ns_get_io_ticks" 9 "libnvme_ns_get_io_ticks" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_io_ticks \- Get IO ticks
.SH SYNOPSIS
.B "unsigned int" libnvme_ns_get_io_ticks
.BI "(struct libnvme_ns *n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIstruct libnvme_ns\fP object
.SH "RETURN"
Time consumed, in milliseconds, processing I/O requests between
two stat samples
