.TH "libnvme_init_ctrl" 9 "libnvme_init_ctrl" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_init_ctrl \- Initialize libnvme_ctrl_t object for an existing controller.
.SH SYNOPSIS
.B "int" libnvme_init_ctrl
.BI "(libnvme_host_t h "  ","
.BI "libnvme_ctrl_t c "  ","
.BI "int instance "  ");"
.SH ARGUMENTS
.IP "h" 12
libnvme_host_t object
.IP "c" 12
libnvme_ctrl_t object
.IP "instance" 12
Instance number (e.g. 1 for nvme1)
.SH "RETURN"
0 on success or negative error code otherwise
