.TH "libnvme_host_get_dhchap_host_key" 9 "libnvme_host_get_dhchap_host_key" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_host_get_dhchap_host_key \- Get dhchap_host_key.
.SH SYNOPSIS
.B "const char *" libnvme_host_get_dhchap_host_key
.BI "(const struct libnvme_host *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_host\fP instance to query.
.SH "RETURN"
The value of the dhchap_host_key field, or NULL if not set.
