.TH "libnvme_first_host" 9 "libnvme_first_host" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_first_host \- Start host iterator
.SH SYNOPSIS
.B "libnvme_host_t" libnvme_first_host
.BI "(struct libnvme_global_ctx *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct libnvme_global_ctx object
.SH "RETURN"
First \fIlibnvme_host_t\fP object in an iterator
