.TH "libnvme_ctrl_get_subsystem" 9 "libnvme_ctrl_get_subsystem" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_subsystem \- Parent subsystem of a controller
.SH SYNOPSIS
.B "struct libnvme_subsystem *" libnvme_ctrl_get_subsystem
.BI "(struct libnvme_ctrl *c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
Parent struct libnvme_subsystem object
