.TH "libnvme_ns_set_lba_util" 9 "libnvme_ns_set_lba_util" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_set_lba_util \- Set lba_util.
.SH SYNOPSIS
.B "void" libnvme_ns_set_lba_util
.BI "(struct libnvme_ns *p "  ","
.BI "uint64_t lba_util "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to update.
.IP "lba_util" 12
Value to assign to the lba_util field.
