.TH "libnvmf_nbft_free" 9 "libnvmf_nbft_free" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_nbft_free \- Free NBFT file entry list
.SH SYNOPSIS
.B "void" libnvmf_nbft_free
.BI "(struct libnvme_global_ctx *ctx "  ","
.BI "struct nbft_file_entry *head "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct libnvme_global_ctx object
.IP "head" 12
Head of the NBFT file entry list
.SH "DESCRIPTION"
Frees all memory associated with the NBFT file entry list.
