.TH "libnvme_for_each_host" 9 "libnvme_for_each_host" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_for_each_host \- Traverse host list
.SH SYNOPSIS
.B "libnvme_for_each_host
.BI "(r "  ","
.BI "h "  ");"
.SH ARGUMENTS
.IP "r" 12
\fIlibnvme_root_t\fP object
.IP "h" 12
\fIlibnvme_host_t\fP object
