.TH "libnvmf_context_get_tls_configured_key_id" 9 "libnvmf_context_get_tls_configured_key_id" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_tls_configured_key_id \- Get tls_configured_key_id.
.SH SYNOPSIS
.B "long" libnvmf_context_get_tls_configured_key_id
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the tls_configured_key_id field.
