.TH "libnvme_ctrl_get_trsvcid" 9 "libnvme_ctrl_get_trsvcid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_trsvcid \- Get trsvcid.
.SH SYNOPSIS
.B "const char *" libnvme_ctrl_get_trsvcid
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the trsvcid field, or NULL if not set.
