.TH "libnvme_ctrl_release_transport_handle" 9 "libnvme_ctrl_release_transport_handle" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_release_transport_handle \- Free transport handle from controller object
.SH SYNOPSIS
.B "void" libnvme_ctrl_release_transport_handle
.BI "(libnvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
