.TH "libnvme_subsystem_first_ns" 9 "libnvme_subsystem_first_ns" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_first_ns \- Start namespace iterator
.SH SYNOPSIS
.B "libnvme_ns_t" libnvme_subsystem_first_ns
.BI "(libnvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
\fIlibnvme_subsystem_t\fP object
.SH "RETURN"
First \fIlibnvme_ns_t\fP object of an \fIs\fP iterator
