.TH "libnvme_fabrics_config_set_fast_io_fail_tmo" 9 "libnvme_fabrics_config_set_fast_io_fail_tmo" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_set_fast_io_fail_tmo \- Set fast_io_fail_tmo.
.SH SYNOPSIS
.B "void" libnvme_fabrics_config_set_fast_io_fail_tmo
.BI "(struct libnvme_fabrics_config *p "  ","
.BI "int fast_io_fail_tmo "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to update.
.IP "fast_io_fail_tmo" 12
Value to assign to the fast_io_fail_tmo field.
