.TH "libnvme_fabric_options_get_instance" 9 "libnvme_fabric_options_get_instance" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_get_instance \- Get instance.
.SH SYNOPSIS
.B "bool" libnvme_fabric_options_get_instance
.BI "(const struct libnvme_fabric_options *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to query.
.SH "RETURN"
The value of the instance field.
