.TH "libnvme_ns_get_stat_interval" 9 "libnvme_ns_get_stat_interval" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_stat_interval \- Get interval between two stat samples
.SH SYNOPSIS
.B "double" libnvme_ns_get_stat_interval
.BI "(struct libnvme_ns *n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIstruct libnvme_ns\fP object
.SH "RETURN"
Interval, in milliseconds, between collection of two consecutive
stat samples
