.TH "libnvme_ctrl_get_reconnect_count" 9 "libnvme_ctrl_get_reconnect_count" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_reconnect_count \- Get controller reconnect count
.SH SYNOPSIS
.B "long" libnvme_ctrl_get_reconnect_count
.BI "(libnvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
Number of times controller has to reconnect to the target
