.TH "libnvme_ns_get_name" 9 "libnvme_ns_get_name" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_name \- Get name.
.SH SYNOPSIS
.B "const char *" libnvme_ns_get_name
.BI "(const struct libnvme_ns *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to query.
.SH "RETURN"
The value of the name field, or NULL if not set.
