.TH "libnvme_path_get_inflights" 9 "libnvme_path_get_inflights" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_inflights \- Inflight IOs for nvme_path_t object
.SH SYNOPSIS
.B "unsigned int" libnvme_path_get_inflights
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
Inflight number of IOs
