.TH "libnvme_ctrl_next_path" 9 "libnvme_ctrl_next_path" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_next_path \- Next path iterator
.SH SYNOPSIS
.B "struct libnvme_path *" libnvme_ctrl_next_path
.BI "(struct libnvme_ctrl *c "  ","
.BI "struct libnvme_path *p "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "p" 12
Previous \fIstruct libnvme_path\fP object of an \fIc\fP iterator
.SH "RETURN"
Next \fIstruct libnvme_path\fP object of an \fIc\fP iterator
