.TH "libnvme_ctrl_get_transport_handle" 9 "libnvme_ctrl_get_transport_handle" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_transport_handle \- Get associated transport handle
.SH SYNOPSIS
.B "struct libnvme_transport_handle *" libnvme_ctrl_get_transport_handle
.BI "(libnvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "DESCRIPTION"
libnvme will \fBopen\fP the device (if not already opened) and keep an
internal copy of the link handle. Following calls to this API retrieve
the internal cached copy of the link handle. The file will remain
opened and the handle will remain cached until the controller object
is deleted or \fBlibnvme_ctrl_release_transport_handle\fP is called.
.SH "RETURN"
Link handle associated with \fIc\fP or NULL
