.TH "libnvme_ns_get_eui64" 9 "libnvme_ns_get_eui64" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_eui64 \- Get eui64.
.SH SYNOPSIS
.B "const uint8_t *" libnvme_ns_get_eui64
.BI "(const struct libnvme_ns *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to query.
.SH "RETURN"
Pointer to the eui64 array of 8 uint8_t elements.
