.TH "libnvme_fabric_options_set_transport" 9 "libnvme_fabric_options_set_transport" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_transport \- Set transport.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_transport
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool transport "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "transport" 12
Value to assign to the transport field.
