.TH "libnvme_ns_get_generic_name" 9 "libnvme_ns_get_generic_name" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_generic_name \- Returns name of generic namespace chardev.
.SH SYNOPSIS
.B "const char *" libnvme_ns_get_generic_name
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.SH "RETURN"
Name of generic namespace chardev
