.TH "libnvme_path_get_write_sectors" 9 "libnvme_path_get_write_sectors" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_write_sectors \- Get write I/O sectors
.SH SYNOPSIS
.B "unsigned long long" libnvme_path_get_write_sectors
.BI "(struct libnvme_path *p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIstruct libnvme_path\fP object
.SH "RETURN"
Num of sectors written to the device between two stat samples
