.TH "libnvme_fabric_options_set_nr_io_queues" 9 "libnvme_fabric_options_set_nr_io_queues" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_nr_io_queues \- Set nr_io_queues.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_nr_io_queues
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool nr_io_queues "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "nr_io_queues" 12
Value to assign to the nr_io_queues field.
