.TH "libnvme_free_global_ctx" 9 "libnvme_free_global_ctx" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_free_global_ctx \- Free global context object
.SH SYNOPSIS
.B "void" libnvme_free_global_ctx
.BI "(struct libnvme_global_ctx *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
\fIstruct libnvme_global_ctx\fP object
.SH "DESCRIPTION"
Free an \fIstruct libnvme_global_ctx\fP object and all attached objects
