.TH "libnvme_ctrl_for_each_path_safe" 9 "libnvme_ctrl_for_each_path_safe" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_for_each_path_safe \- Traverse paths
.SH SYNOPSIS
.B "libnvme_ctrl_for_each_path_safe
.BI "(c "  ","
.BI "p "  ","
.BI "_p "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "p" 12
\fIstruct libnvme_path\fP object
.IP "_p" 12
A \fIstruct libnvme_path\fP node to use as temporary storage
