.TH "libnvme_fabrics_config_set_nr_write_queues" 9 "libnvme_fabrics_config_set_nr_write_queues" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_set_nr_write_queues \- Set nr_write_queues.
.SH SYNOPSIS
.B "void" libnvme_fabrics_config_set_nr_write_queues
.BI "(struct libnvme_fabrics_config *p "  ","
.BI "int nr_write_queues "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to update.
.IP "nr_write_queues" 12
Value to assign to the nr_write_queues field.
