.TH "libnvme_fabrics_config_get_concat" 9 "libnvme_fabrics_config_get_concat" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_get_concat \- Get concat.
.SH SYNOPSIS
.B "bool" libnvme_fabrics_config_get_concat
.BI "(const struct libnvme_fabrics_config *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to query.
.SH "RETURN"
The value of the concat field.
