.TH "libnvme_path_get_multipath_failover_count" 9 "libnvme_path_get_multipath_failover_count" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_multipath_failover_count \- Get multipath failover count
.SH SYNOPSIS
.B "long" libnvme_path_get_multipath_failover_count
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
Number of times I/Os have to be failed over to another active path
from path \fIp\fP maybe due to any transient error observed on path \fIp\fP
