.TH "libnvmf_context_get_keyring_id" 9 "libnvmf_context_get_keyring_id" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_keyring_id \- Get keyring_id.
.SH SYNOPSIS
.B "long" libnvmf_context_get_keyring_id
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the keyring_id field.
