.TH "libnvmf_context_get_default_keep_alive_timeout" 9 "libnvmf_context_get_default_keep_alive_timeout" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_default_keep_alive_timeout \- Getter.
.SH SYNOPSIS
.B "int" libnvmf_context_get_default_keep_alive_timeout
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the default_keep_alive_timeout field.
