.TH "libnvme_lookup_key" 9 "libnvme_lookup_key" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_lookup_key \- Lookup key serial number
.SH SYNOPSIS
.B "int" libnvme_lookup_key
.BI "(struct libnvme_global_ctx *ctx "  ","
.BI "const char *type "  ","
.BI "const char *identity "  ","
.BI "long *key "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct libnvme_global_ctx object
.IP "type" 12
Key type
.IP "identity" 12
Key description
.IP "key" 12
Key serial number to return
.SH "DESCRIPTION"
Looks up the serial number of the key \fIidentity\fP
with type type in the current session keyring.
.SH "RETURN"
0 on success or negative error code otherwise
