.TH "libnvme_ctrl_get_keyring_id" 9 "libnvme_ctrl_get_keyring_id" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_keyring_id \- Get keyring_id.
.SH SYNOPSIS
.B "long" libnvme_ctrl_get_keyring_id
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the keyring_id field.
