.TH "libnvme_fabrics_config_get_tls_configured_key_id" 9 "libnvme_fabrics_config_get_tls_configured_key_id" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabrics_config_get_tls_configured_key_id \- Get tls_configured_key_id.
.SH SYNOPSIS
.B "long" libnvme_fabrics_config_get_tls_configured_key_id
.BI "(const struct libnvme_fabrics_config *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabrics_config\fP instance to query.
.SH "RETURN"
The value of the tls_configured_key_id field.
