.TH "libnvme_ctrl_get_subsystem" 9 "libnvme_ctrl_get_subsystem" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_subsystem \- Parent subsystem of a controller
.SH SYNOPSIS
.B "libnvme_subsystem_t" libnvme_ctrl_get_subsystem
.BI "(libnvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
Parent libnvme_subsystem_t object
