.TH "libnvme_path_get_ns" 9 "libnvme_path_get_ns" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_ns \- Parent namespace of an struct libnvme_path object
.SH SYNOPSIS
.B "struct libnvme_ns *" libnvme_path_get_ns
.BI "(struct libnvme_path *p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIstruct libnvme_path\fP object
.SH "RETURN"
Parent namespace if present
