.TH "libnvme_subsystem_for_each_ns" 9 "libnvme_subsystem_for_each_ns" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_for_each_ns \- Traverse namespaces
.SH SYNOPSIS
.B "libnvme_subsystem_for_each_ns
.BI "(s "  ","
.BI "n "  ");"
.SH ARGUMENTS
.IP "s" 12
\fIlibnvme_subsystem_t\fP object
.IP "n" 12
\fIlibnvme_ns_t\fP object
