.TH "libnvme_host_set_pdc_enabled_valid" 9 "libnvme_host_set_pdc_enabled_valid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_host_set_pdc_enabled_valid \- Set pdc_enabled_valid.
.SH SYNOPSIS
.B "void" libnvme_host_set_pdc_enabled_valid
.BI "(struct libnvme_host *p "  ","
.BI "bool pdc_enabled_valid "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_host\fP instance to update.
.IP "pdc_enabled_valid" 12
Value to assign to the pdc_enabled_valid field.
