.TH "libnvme_fabric_options_set_trsvcid" 9 "libnvme_fabric_options_set_trsvcid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_trsvcid \- Set trsvcid.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_trsvcid
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool trsvcid "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "trsvcid" 12
Value to assign to the trsvcid field.
