.TH "libnvme" 9 "struct libnbft_security" "April 2026" "API Manual" LINUX
.SH NAME
struct libnbft_security \- Security Profile Descriptor
.SH SYNOPSIS
struct libnbft_security {
.br
.BI "    int index;"
.br
.BI "
};
.br

.SH Members
.IP "index" 12
The number of this Security Profile Descriptor in the Security
Profile Descriptor List.
