.TH "libnvmf_uri_get_port" 9 "libnvmf_uri_get_port" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_uri_get_port \- Get port.
.SH SYNOPSIS
.B "int" libnvmf_uri_get_port
.BI "(const struct libnvmf_uri *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_uri\fP instance to query.
.SH "RETURN"
The value of the port field.
