.TH "libnvme_path_get_ns" 9 "libnvme_path_get_ns" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_ns \- Parent namespace of an libnvme_path_t object
.SH SYNOPSIS
.B "libnvme_ns_t" libnvme_path_get_ns
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
Parent namespace if present
