.TH "libnvme" 9 "struct libnbft_host" "July 2026" "API Manual" LINUX
.SH NAME
struct libnbft_host \- Host Descriptor
.SH SYNOPSIS
struct libnbft_host {
.br
.BI "    unsigned char *id;"
.br
.BI "    char *nqn;"
.br
.BI "    __u8 flags;"
.br
.BI "
};
.br

.SH Members
.IP "id" 12
Host ID (raw UUID, length = 16 bytes).
.IP "nqn" 12
Host NQN.
.IP "flags" 12
Host Descriptor Flags bitmask, see \fIenum nbft_host_flags\fP.
