.TH "libnvmf_context_set_disable_sqflow" 9 "libnvmf_context_set_disable_sqflow" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_disable_sqflow \- Set disable_sqflow.
.SH SYNOPSIS
.B "void" libnvmf_context_set_disable_sqflow
.BI "(struct libnvmf_context *p "  ","
.BI "bool disable_sqflow "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to update.
.IP "disable_sqflow" 12
Value to assign to the disable_sqflow field.
