.TH "libnvme_get_force_4k" 9 "libnvme_get_force_4k" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_get_force_4k \- Get force_4k.
.SH SYNOPSIS
.B "bool" libnvme_get_force_4k
.BI "(const struct libnvme_global_ctx *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_global_ctx\fP instance to query.
.SH "RETURN"
The value of the force_4k field.
