.TH "libnvme_fabric_options_set_keep_alive_tmo" 9 "libnvme_fabric_options_set_keep_alive_tmo" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_keep_alive_tmo \- Set keep_alive_tmo.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_keep_alive_tmo
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool keep_alive_tmo "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "keep_alive_tmo" 12
Value to assign to the keep_alive_tmo field.
