.TH "libnvme_path_get_queue_depth" 9 "libnvme_path_get_queue_depth" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_queue_depth \- Queue depth of an libnvme_path_t object
.SH SYNOPSIS
.B "int" libnvme_path_get_queue_depth
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
Queue depth of \fIp\fP
