.TH "libnvmf_discovery_args_set_lsp" 9 "libnvmf_discovery_args_set_lsp" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_discovery_args_set_lsp \- Set lsp.
.SH SYNOPSIS
.B "void" libnvmf_discovery_args_set_lsp
.BI "(struct libnvmf_discovery_args *p "  ","
.BI "__u8 lsp "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_discovery_args\fP instance to update.
.IP "lsp" 12
Value to assign to the lsp field.
