.TH "libnvmf_context_set_data_digest" 9 "libnvmf_context_set_data_digest" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_data_digest \- Set data_digest.
.SH SYNOPSIS
.B "void" libnvmf_context_set_data_digest
.BI "(struct libnvmf_context *p "  ","
.BI "bool data_digest "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to update.
.IP "data_digest" 12
Value to assign to the data_digest field.
