.TH "libnvme_subsystem_get_subsystype" 9 "libnvme_subsystem_get_subsystype" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_get_subsystype \- Get subsystype.
.SH SYNOPSIS
.B "const char *" libnvme_subsystem_get_subsystype
.BI "(const struct libnvme_subsystem *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_subsystem\fP instance to query.
.SH "RETURN"
The value of the subsystype field, or NULL if not set.
