.TH "libnvme_path_get_ana_state" 9 "libnvme_path_get_ana_state" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_path_get_ana_state \- ANA state of an nvme_path_t object
.SH SYNOPSIS
.B "char *" libnvme_path_get_ana_state
.BI "(libnvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fIlibnvme_path_t\fP object
.SH "RETURN"
ANA state of \fIp\fP
