.TH "libnvme_ns_get_write_ios" 9 "libnvme_ns_get_write_ios" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_write_ios \- Get num of write I/Os
.SH SYNOPSIS
.B "unsigned long" libnvme_ns_get_write_ios
.BI "(libnvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
\fIlibnvme_ns_t\fP object
.SH "RETURN"
Num of write IOs processed between two consecutive stat samples
