.TH "libnvmf_generate_hostnqn" 9 "libnvmf_generate_hostnqn" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_generate_hostnqn \- Generate a machine specific host nqn
.SH SYNOPSIS
.B "char *" libnvmf_generate_hostnqn
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
An nvm namespace qualified name string based on the machine
identifier, or NULL if not successful.
