.TH "libnvme_subsystem_next_ns" 9 "libnvme_subsystem_next_ns" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_subsystem_next_ns \- Next namespace iterator
.SH SYNOPSIS
.B "struct libnvme_ns *" libnvme_subsystem_next_ns
.BI "(struct libnvme_subsystem *s "  ","
.BI "struct libnvme_ns *n "  ");"
.SH ARGUMENTS
.IP "s" 12
\fIstruct libnvme_subsystem\fP object
.IP "n" 12
Previous \fIstruct libnvme_ns\fP iterator
.SH "RETURN"
Next \fIstruct libnvme_ns\fP object of an \fIs\fP iterator
