.TH "libnvmf_context_get_fabrics_config" 9 "libnvmf_context_get_fabrics_config" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_fabrics_config \- Fabrics configuration of a fabrics context
.SH SYNOPSIS
.B "struct libnvme_fabrics_config *" libnvmf_context_get_fabrics_config
.BI "(struct libnvmf_context *fctx "  ");"
.SH ARGUMENTS
.IP "fctx" 12
Fabrics context
.SH "RETURN"
Fabrics configuration of \fIfctx\fP
