.TH "libnvme_fabric_options_set_cntlid" 9 "libnvme_fabric_options_set_cntlid" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_cntlid \- Set cntlid.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_cntlid
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool cntlid "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "cntlid" 12
Value to assign to the cntlid field.
