.TH "libnvme_mi_aem_get_fd" 9 "libnvme_mi_aem_get_fd" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_mi_aem_get_fd \- Returns the pollable fd for AEM data available
.SH SYNOPSIS
.B "int" libnvme_mi_aem_get_fd
.BI "(libnvme_mi_ep_t ep "  ");"
.SH ARGUMENTS
.IP "ep" 12
The endpoint being monitored for asynchronous data
.SH "DESCRIPTION"
This populated structure can be polled from the application to understand if
a call to \fBlibnvme_mi_aem_process\fP is required (when a poll returns > 0).
.SH "RETURN"
The fd value or -1 if error
