.TH "libnvmf_context_set_force" 9 "libnvmf_context_set_force" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_force \- Set force.
.SH SYNOPSIS
.B "void" libnvmf_context_set_force
.BI "(struct libnvmf_context *p "  ","
.BI "bool force "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to update.
.IP "force" 12
Value to assign to the force field.
