.TH "libnvme_get_dry_run" 9 "libnvme_get_dry_run" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_get_dry_run \- Get dry_run.
.SH SYNOPSIS
.B "bool" libnvme_get_dry_run
.BI "(const struct libnvme_global_ctx *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_global_ctx\fP instance to query.
.SH "RETURN"
The value of the dry_run field.
