.TH "libnvme_ns_set_lba_shift" 9 "libnvme_ns_set_lba_shift" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_set_lba_shift \- Set lba_shift.
.SH SYNOPSIS
.B "void" libnvme_ns_set_lba_shift
.BI "(struct libnvme_ns *p "  ","
.BI "int lba_shift "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to update.
.IP "lba_shift" 12
Value to assign to the lba_shift field.
