.TH "libnvmf_context_get_keep_alive_tmo" 9 "libnvmf_context_get_keep_alive_tmo" "July 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_keep_alive_tmo \- Get keep_alive_tmo.
.SH SYNOPSIS
.B "int" libnvmf_context_get_keep_alive_tmo
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the keep_alive_tmo field.
