.TH "libnvmf_context_get_data_digest" 9 "libnvmf_context_get_data_digest" "June 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_get_data_digest \- Get data_digest.
.SH SYNOPSIS
.B "bool" libnvmf_context_get_data_digest
.BI "(const struct libnvmf_context *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to query.
.SH "RETURN"
The value of the data_digest field.
