.TH "libnvme_fabric_options_set_disable_sqflow" 9 "libnvme_fabric_options_set_disable_sqflow" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_disable_sqflow \- Set disable_sqflow.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_disable_sqflow
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool disable_sqflow "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "disable_sqflow" 12
Value to assign to the disable_sqflow field.
