.TH "libnvme_ctrl_get_model" 9 "libnvme_ctrl_get_model" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ctrl_get_model \- Get model.
.SH SYNOPSIS
.B "const char *" libnvme_ctrl_get_model
.BI "(const struct libnvme_ctrl *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ctrl\fP instance to query.
.SH "RETURN"
The value of the model field, or NULL if not set.
