.TH "libnvme_ns_get_lba_util" 9 "libnvme_ns_get_lba_util" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_ns_get_lba_util \- Get lba_util.
.SH SYNOPSIS
.B "uint64_t" libnvme_ns_get_lba_util
.BI "(const struct libnvme_ns *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_ns\fP instance to query.
.SH "RETURN"
The value of the lba_util field.
