.TH "libnvmf_context_set_no_reuse" 9 "libnvmf_context_set_no_reuse" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_context_set_no_reuse \- Set no_reuse.
.SH SYNOPSIS
.B "void" libnvmf_context_set_no_reuse
.BI "(struct libnvmf_context *p "  ","
.BI "bool no_reuse "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_context\fP instance to update.
.IP "no_reuse" 12
Value to assign to the no_reuse field.
