.TH "libnvmf_discovery_args_get_lsp" 9 "libnvmf_discovery_args_get_lsp" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvmf_discovery_args_get_lsp \- Get lsp.
.SH SYNOPSIS
.B "__u8" libnvmf_discovery_args_get_lsp
.BI "(const struct libnvmf_discovery_args *p "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvmf_discovery_args\fP instance to query.
.SH "RETURN"
The value of the lsp field.
