.TH "libnvme_set_ioctl_probing" 9 "libnvme_set_ioctl_probing" "August 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_set_ioctl_probing \- Set ioctl_probing.
.SH SYNOPSIS
.B "void" libnvme_set_ioctl_probing
.BI "(struct libnvme_global_ctx *p "  ","
.BI "bool ioctl_probing "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_global_ctx\fP instance to update.
.IP "ioctl_probing" 12
Value to assign to the ioctl_probing field.
