.TH "libnvme_fabric_options_set_queue_size" 9 "libnvme_fabric_options_set_queue_size" "April 2026" "libnvme API manual" LINUX
.SH NAME
libnvme_fabric_options_set_queue_size \- Set queue_size.
.SH SYNOPSIS
.B "void" libnvme_fabric_options_set_queue_size
.BI "(struct libnvme_fabric_options *p "  ","
.BI "bool queue_size "  ");"
.SH ARGUMENTS
.IP "p" 12
The \fIstruct libnvme_fabric_options\fP instance to update.
.IP "queue_size" 12
Value to assign to the queue_size field.
