.TH "libnvme" 9 "enum nbft_ssns_ext_info_nceec" "August 2026" "API Manual" LINUX
.SH NAME
enum nbft_ssns_ext_info_nceec \- Network and Connection Extended Error Codes (since rev. 1.1)
.SH SYNOPSIS
enum nbft_ssns_ext_info_nceec {
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_NO_ERROR"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_LINK_ERR"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_CARRIER_ERR"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_CONN_REFUSED"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_NO_ROUTE"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_FRAG_ERR"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_MTU_MISMATCH"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_NCEEC_NAME_RES"

};
.SH Constants
.IP "NBFT_SSNS_EXT_INFO_NCEEC_NO_ERROR" 12
No Extended Error Known.
.IP "NBFT_SSNS_EXT_INFO_NCEEC_LINK_ERR" 12
Link Error.
.IP "NBFT_SSNS_EXT_INFO_NCEEC_CARRIER_ERR" 12
Carrier Error.
.IP "NBFT_SSNS_EXT_INFO_NCEEC_CONN_REFUSED" 12
Connection Refused.
.IP "NBFT_SSNS_EXT_INFO_NCEEC_NO_ROUTE" 12
No Route to Host.
.IP "NBFT_SSNS_EXT_INFO_NCEEC_FRAG_ERR" 12
Packet Fragmentation Error.
.IP "NBFT_SSNS_EXT_INFO_NCEEC_MTU_MISMATCH" 12
MTU Mismatch.
.IP "NBFT_SSNS_EXT_INFO_NCEEC_NAME_RES" 12
Name Resolution Failure.
