.TH "libnvme" 9 "struct nbft_hfi_info_ext" "July 2026" "API Manual" LINUX
.SH NAME
struct nbft_hfi_info_ext \- HFI Transport Info Extended Information Descriptor (Figure 15, since rev. 1.1)
.SH SYNOPSIS
struct nbft_hfi_info_ext {
.br
.BI "    __u8 structure_id;"
.br
.BI "    __u8 version;"
.br
.BI "    __le16 hfi_trinfo_index;"
.br
.BI "    __le32 flags;"
.br
.BI "    struct nbft_heap_obj dhcp_iaid_obj;"
.br
.BI "    struct nbft_heap_obj dhcp_duid_obj;"
.br
.BI "
};
.br

.SH Members
.IP "structure_id" 12
Structure ID: This field shall be set to Ah
(i.e., HFI Ext Info; #NBFT_DESC_HFI_EXT_INFO).
.IP "version" 12
Version: This field shall be set to 1h.
.IP "hfi_trinfo_index" 12
HFI Transport Info Descriptor Index: This field shall
be set to the same value as the HFI Transport Info
Descriptor Index field of the referencing HFI Transport
Info Descriptor.
.IP "flags" 12
Flags, see \fIenum nbft_hfi_info_ext_flags\fP.
.IP "dhcp_iaid_obj" 12
IPv4 and IPv6 DHCP Client Identifier Heap IAID Object
Reference: If the DHCP Client Identifier bit is set to 1h,
then this heap object references the Identity Association
Identifier (IAID). This identifier shall be constructed
conformant to RFC4361. The IAID is stored in little endian
format within the heap object.
.IP "dhcp_duid_obj" 12
IPv4 and IPv6 DHCP Client Identifier Heap DUID Object
Reference: If the DHCP Client Identifier bit is set to 1h,
then this heap object references the DHCP Unique Identifier
(DUID). This identifier shall be constructed conformant
to RFC4361. The DUID is stored in little endian format
within the heap object.
