.TH "libnvme" 9 "struct nvme_ns_mgmt_args" "November 2025" "API Manual" LINUX
.SH NAME
struct nvme_ns_mgmt_args \- Arguments for NVMe Namespace Management command
.SH SYNOPSIS
struct nvme_ns_mgmt_args {
.br
.BI "    __u32 *result;"
.br
.BI "    struct nvme_id_ns *ns;"
.br
.BI "    int args_size;"
.br
.BI "    int fd;"
.br
.BI "    __u32 timeout;"
.br
.BI "    __u32 nsid;"
.br
.BI "    enum nvme_ns_mgmt_sel sel;"
.br
.BI "    __u8 csi;"
.br
.BI "    __u8 rsvd1[3];"
.br
.BI "    void *rsvd2;"
.br
.BI "    struct nvme_ns_mgmt_host_sw_specified *data;"
.br
.BI "
};
.br

.SH Members
.IP "result" 12
NVMe command result
.IP "ns" 12
Namespace identification descriptors
.IP "args_size" 12
Size of \fIstruct nvme_ns_mgmt_args\fP
.IP "fd" 12
File descriptor of nvme device
.IP "timeout" 12
Timeout in ms
.IP "nsid" 12
Namespace identifier
.IP "sel" 12
Type of management operation to perform
.IP "csi" 12
Command Set Identifier
.IP "rsvd1" 12
Reserved
.IP "rsvd2" 12
Reserved
.IP "data" 12
Host Software Specified Fields
