.TH "nvme_init_identify_csi_independent_identify_id_ns" 9 "nvme_init_identify_csi_independent_identify_id_ns" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_identify_csi_independent_identify_id_ns \- Initialize passthru command for I/O Command Set Independent Identify Namespace data structure
.SH SYNOPSIS
.B "void" nvme_init_identify_csi_independent_identify_id_ns
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u32 nsid "  ","
.BI "struct nvme_id_independent_id_ns *ns "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Command data structure to initialize
.IP "nsid" 12
Return namespaces greater than this identifier
.IP "ns" 12
I/O Command Set Independent Identify Namespace data
structure
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Identify command with
CNS value NVME_IDENTIFY_CNS_CSI_INDEPENDENT_ID_NS.
