.TH "nvme_init_ns_attach_ctrls" 9 "nvme_init_ns_attach_ctrls" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_ns_attach_ctrls \- Initialize passthru command to attach namespace to controllers
.SH SYNOPSIS
.B "void" nvme_init_ns_attach_ctrls
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u32 nsid "  ","
.BI "struct nvme_ctrl_list *ctrlist "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "nsid" 12
Namespace ID to attach
.IP "ctrlist" 12
Controller list buffer to modify attachment state of nsid
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Namespace Attach command
(NVME_NS_ATTACH_SEL_CTRL_ATTACH).
