.TH "nvme_init_lm_migration_recv" 9 "nvme_init_lm_migration_recv" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_lm_migration_recv \- Initialize passthru command for Migration Receive command
.SH SYNOPSIS
.B "void" nvme_init_lm_migration_recv
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u64 offset "  ","
.BI "__u16 mos "  ","
.BI "__u16 cntlid "  ","
.BI "__u16 csuuidi "  ","
.BI "__u8 sel "  ","
.BI "__u8 uidx "  ","
.BI "__u8 csuidxp "  ","
.BI "void *data "  ","
.BI "__u32 len "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "offset" 12
Offset: This field specifies the offset, in bytes, within
the data available to be returned and specifies the starting
point for that data for what is actually returned to the host.
.IP "mos" 12
Management Operation Specific (MOS): This field is specific to
the SEL type
.IP "cntlid" 12
Controller ID: This field specifies the identifier of the
controller to which the operation is performed.
.IP "csuuidi" 12
Controller State UUID Index (CSUUIDI)
.IP "sel" 12
Select (SEL): This field specifies the type of management
operation to perform
.IP "uidx" 12
UUID Index (UIDX)
.IP "csuidxp" 12
Controller State UUID Index Parameter (CSUIDXP)
.IP "data" 12
Pointer to data buffer
.IP "len" 12
Length of \fIdata\fP
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Migration Receive command.
