.TH "nvme_init_set_features_sanitize" 9 "nvme_init_set_features_sanitize" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_set_features_sanitize \- Initialize passthru command for Sanitize
.SH SYNOPSIS
.B "void" nvme_init_set_features_sanitize
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "bool sv "  ","
.BI "bool nodrm "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "sv" 12
Save value across power states
.IP "nodrm" 12
No-Deallocate Response Mode
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Set Features command with
FID value NVME_FEAT_FID_SANITIZE
