.TH "nvme_path_get_queue_depth" 9 "nvme_path_get_queue_depth" "November 2025" "libnvme API manual" LINUX
.SH NAME
nvme_path_get_queue_depth \- Queue depth of an nvme_path_t object
.SH SYNOPSIS
.B "int" nvme_path_get_queue_depth
.BI "(nvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fInvme_path_t\fP object
.SH "RETURN"
Queue depth of \fIp\fP
