.TH "nvme_init_resv_acquire" 9 "nvme_init_resv_acquire" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_resv_acquire \- Initialize passthru command for Reservation Acquire
.SH SYNOPSIS
.B "void" nvme_init_resv_acquire
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u32 nsid "  ","
.BI "enum nvme_resv_racqa racqa "  ","
.BI "bool iekey "  ","
.BI "bool disnsrs "  ","
.BI "enum nvme_resv_rtype rtype "  ","
.BI "__u64 crkey "  ","
.BI "__u64 prkey "  ","
.BI "__le64 *payload "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "nsid" 12
Namespace identifier
.IP "racqa" 12
The action that is performed by the command,
see \fIenum nvme_resv_racqa\fP
.IP "iekey" 12
Set to ignore the existing key
.IP "disnsrs" 12
Disperse Namespace Reservation Support
.IP "rtype" 12
The type of reservation to be create, see \fIenum nvme_resv_rtype\fP
.IP "crkey" 12
The current reservation key associated with the host
.IP "prkey" 12
Preempt Reservation Key
.IP "payload" 12
Data payload buffer to hold crkey and prkey
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Reservation Acquire command.
