.TH "nvme_init_get_log_pull_model_ddc_req" 9 "nvme_init_get_log_pull_model_ddc_req" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_log_pull_model_ddc_req \- Initialize passthru command for Pull Model DDC Request
.SH SYNOPSIS
.B "void" nvme_init_get_log_pull_model_ddc_req
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "struct nvme_pull_model_ddc_req_log *log "  ","
.BI "__u32 len "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "log" 12
User address to store the log page
.IP "len" 12
The allocated length of the log page
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Log command with
LID value NVME_LOG_LID_PULL_MODEL_DDC_REQ
