.TH "nvme_first_host" 9 "nvme_first_host" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvme_first_host \- Start host iterator
.SH SYNOPSIS
.B "nvme_host_t" nvme_first_host
.BI "(struct nvme_global_ctx *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct nvme_global_ctx object
.SH "RETURN"
First \fInvme_host_t\fP object in an iterator
