.TH "nvme_init_get_log_telemetry_host" 9 "nvme_init_get_log_telemetry_host" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_log_telemetry_host \- Initialize passthru command for Telemetry Host-Initiated
.SH SYNOPSIS
.B "void" nvme_init_get_log_telemetry_host
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u64 lpo "  ","
.BI "void *log "  ","
.BI "__u32 len "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "lpo" 12
Offset into the telemetry data
.IP "log" 12
User address for log page data
.IP "len" 12
Length of provided user buffer to hold the log data in bytes
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Log command with
LID value NVME_LOG_LID_TELEMETRY_HOST.
