.TH "libnvme" 9 "enum nvme_power_measurement_action" "March 2026" "API Manual" LINUX
.SH NAME
enum nvme_power_measurement_action \- Power measurement actions.
.SH SYNOPSIS
enum nvme_power_measurement_action {
.br
.BI "    NVME_PMA_STOP"
, 
.br
.br
.BI "    NVME_PMA_START"

};
.SH Constants
.IP "NVME_PMA_STOP" 12
Stop power measurement
.IP "NVME_PMA_START" 12
Start power measurement
