.TH "nvme_init_get_features_host_mem_buf" 9 "nvme_init_get_features_host_mem_buf" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_features_host_mem_buf \- Initialize passthru command for Get Features - Host Memory Buffer
.SH SYNOPSIS
.B "void" nvme_init_get_features_host_mem_buf
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "enum nvme_get_features_sel sel "  ","
.BI "struct nvme_host_mem_buf_attrs *attrs "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "sel" 12
Select which type of attribute to return,
see \fIenum nvme_get_features_sel\fP
.IP "attrs" 12
Buffer for returned Host Memory Buffer Attributes
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Features command with
FID value NVME_FEAT_FID_HOST_MEM_BUF
