.TH "nvme_init_get_log_fdp_stats" 9 "nvme_init_get_log_fdp_stats" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_log_fdp_stats \- Initialize passthru command for Get Flexible Data Placement Statistics
.SH SYNOPSIS
.B "void" nvme_init_get_log_fdp_stats
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u16 egid "  ","
.BI "__u64 lpo "  ","
.BI "void *log "  ","
.BI "__u32 len "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "egid" 12
Endurance group identifier
.IP "lpo" 12
Offset into log page
.IP "log" 12
Log page data buffer
.IP "len" 12
Length (in bytes) of provided user buffer to hold the log data
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Log command with
LID value NVME_LOG_LID_FDP_STATS
