.TH "nvme_init_get_log_host_discovery" 9 "nvme_init_get_log_host_discovery" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_log_host_discovery \- Initialize passthru command for Host Discover
.SH SYNOPSIS
.B "void" nvme_init_get_log_host_discovery
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "bool allhoste "  ","
.BI "struct nvme_host_discover_log *log "  ","
.BI "__u32 len "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "allhoste" 12
All host entries
.IP "log" 12
User address to store the log page
.IP "len" 12
The allocated length of the log page
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Log command with
LID value NVME_LOG_LID_HOST_DISCOVERY
