.TH "nvme_init_set_features_power_mgmt" 9 "nvme_init_set_features_power_mgmt" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_set_features_power_mgmt \- Initialize passthru command for Power Management
.SH SYNOPSIS
.B "void" nvme_init_set_features_power_mgmt
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "bool sv "  ","
.BI "__u8 ps "  ","
.BI "__u8 wh "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "sv" 12
Save value across power states
.IP "ps" 12
Power State
.IP "wh" 12
Workload Hint
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Set Features command with
FID value NVME_FEAT_FID_PWRMGMT_PS
