.TH "nvme_init_get_features_host_behavior" 9 "nvme_init_get_features_host_behavior" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_features_host_behavior \- Initialize passthru command for Get Features - Host Behavior
.SH SYNOPSIS
.B "void" nvme_init_get_features_host_behavior
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "enum nvme_get_features_sel sel "  ","
.BI "struct nvme_feat_host_behavior *fhb "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "sel" 12
Select which type of attribute to return,
see \fIenum nvme_get_features_sel\fP
.IP "fhb" 12
Pointer to structure nvme_feat_host_behavior
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Features command with
FID value NVME_FEAT_FID_HOST_BEHAVIOR
