.TH "nvme_ns_get_attr" 9 "nvme_ns_get_attr" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvme_ns_get_attr \- Read namespace sysfs attribute
.SH SYNOPSIS
.B "char *" nvme_ns_get_attr
.BI "(nvme_ns_t n "  ","
.BI "const char *attr "  ");"
.SH ARGUMENTS
.IP "n" 12
nvme_ns_t object
.IP "attr" 12
sysfs attribute name
.SH "RETURN"
String with the contents of \fIattr\fP or NULL in case of an empty value
or in case of an error.
