.TH "nvme_init_identify_csi_id_ns_data_structure" 9 "nvme_init_identify_csi_id_ns_data_structure" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_identify_csi_id_ns_data_structure \- Initialize passthru command for I/O Command Set specific Identify Namespace data structure
.SH SYNOPSIS
.B "void" nvme_init_identify_csi_id_ns_data_structure
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u32 nsid "  ","
.BI "enum nvme_csi csi "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Command data structure to initialize
.IP "nsid" 12
Return namespaces greater than this identifier
.IP "csi" 12
Command Set Identifier
.IP "data" 12
User space destination address to transfer the data
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Identify command with
CNS value NVME_IDENTIFY_CNS_CSI_ID_NS_DATA_STRUCTURE.
