.TH "nvme_init_directive_send_stream_release_identifier" 9 "nvme_init_directive_send_stream_release_identifier" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_directive_send_stream_release_identifier \- Initialize passthru command for Directive Send Stream release identifier
.SH SYNOPSIS
.B "void" nvme_init_directive_send_stream_release_identifier
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u32 nsid "  ","
.BI "__u16 stream_id "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "nsid" 12
Namespace ID
.IP "stream_id" 12
Stream identifier
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Directive Send - Stream
Release Identifier command.
