.TH "nvme_init_get_log_create_telemetry_host_mcda" 9 "nvme_init_get_log_create_telemetry_host_mcda" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_log_create_telemetry_host_mcda \- Initialize passthru command for Create Telemetry Host-Initiated
.SH SYNOPSIS
.B "void" nvme_init_get_log_create_telemetry_host_mcda
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "enum nvme_telemetry_da mcda "  ","
.BI "struct nvme_telemetry_log *log "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "mcda" 12
Maximum Created Data Area
.IP "log" 12
Userspace address of the log payload
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Log command with
LID value NVME_LOG_LID_TELEMETRY_HOST and
LSP value NVME_LOG_TELEM_HOST_LSP_CREATE.
