.TH "nvme_init_get_features_sw_progress" 9 "nvme_init_get_features_sw_progress" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_features_sw_progress \- Initialize passthru command for Get Features - Software Progress
.SH SYNOPSIS
.B "void" nvme_init_get_features_sw_progress
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "enum nvme_get_features_sel sel "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "sel" 12
Select which type of attribute to return,
see \fIenum nvme_get_features_sel\fP
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Features command with
FID value NVME_FEAT_FID_SW_PROGRESS
