.TH "nvme_import_tls_key" 9 "nvme_import_tls_key" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvme_import_tls_key \- Import a TLS key
.SH SYNOPSIS
.B "int" nvme_import_tls_key
.BI "(struct nvme_global_ctx *ctx "  ","
.BI "const char *encoded_key "  ","
.BI "int *key_len "  ","
.BI "unsigned int *hmac "  ","
.BI "unsigned char **key "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct nvme_global_ctx object
.IP "encoded_key" 12
TLS key in PSK interchange format
.IP "key_len" 12
Length of the resulting key data
.IP "hmac" 12
HMAC algorithm
.IP "key" 12
Key serial to return
.SH "DESCRIPTION"
Imports \fIkey_data\fP in the PSK Interchange format as defined in section
3.6.1.5 of the NVMe TCP Transport specification.

It is the responsibility of the caller to free the returned string.
.SH "RETURN"
0 on success or negative error code otherwise
