.TH "nvme_init_get_log_reclaim_unit_handle_usage" 9 "nvme_init_get_log_reclaim_unit_handle_usage" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_get_log_reclaim_unit_handle_usage \- Initialize passthru command for Reclaim Unit Handle Usage
.SH SYNOPSIS
.B "void" nvme_init_get_log_reclaim_unit_handle_usage
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u16 egid "  ","
.BI "__u64 lpo "  ","
.BI "void *log "  ","
.BI "__u32 len "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "egid" 12
Endurance group identifier
.IP "lpo" 12
Offset into log page
.IP "log" 12
Log page data buffer
.IP "len" 12
Length (in bytes) of provided user buffer to hold the log data
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Get Log command with
LID value NVME_LOG_LID_RUH_USAGE
