.TH "libnvme" 9 "enum nvme_id_ctrl_cdpa" "April 2026" "API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_cdpa \- Configurable Device Personality Attributes
.SH SYNOPSIS
enum nvme_id_ctrl_cdpa {
.br
.BI "    NVME_CTRL_CDPA_HMAC_SHA_384"

};
.SH Constants
.IP "NVME_CTRL_CDPA_HMAC_SHA_384" 12
If set, then the controller supports
the HMAC-SHA-384 standard.
