.TH "nvme_init_directive_recv_identify_parameters" 9 "nvme_init_directive_recv_identify_parameters" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_directive_recv_identify_parameters \- Initialize passthru command for Directive Receive Identify Parameters
.SH SYNOPSIS
.B "void" nvme_init_directive_recv_identify_parameters
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "__u32 nsid "  ","
.BI "struct nvme_id_directives *id "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "nsid" 12
Namespace ID
.IP "id" 12
Identify parameters buffer
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Directive Receive - Identify
Parameters command.
