.TH "nvme_init_set_features_plm_config" 9 "nvme_init_set_features_plm_config" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_set_features_plm_config \- Initialize passthru command for Predictable Latency Mode Config
.SH SYNOPSIS
.B "void" nvme_init_set_features_plm_config
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "bool sv "  ","
.BI "__u16 nvmsetid "  ","
.BI "bool lpe "  ","
.BI "struct nvme_plm_config *data "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Passthru command to use
.IP "sv" 12
Save value across power states
.IP "nvmsetid" 12
NVM Set Identifier
.IP "lpe" 12
Predictable Latency Enable
.IP "data" 12
Pointer to structure nvme_plm_config
.SH "DESCRIPTION"
Initializes the passthru command buffer for the Set Features command with
FID value NVME_FEAT_FID_PLM_CONFIG
