.TH "libnvme" 9 "enum nvme_mi_pda_dformat" "August 2026" "API Manual" LINUX
.SH NAME
enum nvme_mi_pda_dformat \- NVMe-MI PDA Command - Data Format (DFORMAT)
.SH SYNOPSIS
enum nvme_mi_pda_dformat {
.br
.BI "    nvme_mi_pda_dformat_4kib"
, 
.br
.br
.BI "    nvme_mi_pda_dformat_512b"
, 
.br
.br
.BI "    nvme_mi_pda_dformat_byte"

};
.SH Constants
.IP "nvme_mi_pda_dformat_4kib" 12
4KiB data format
.IP "nvme_mi_pda_dformat_512b" 12
512B data format
.IP "nvme_mi_pda_dformat_byte" 12
Byte Level data format
