.TH "nvme_init_zns_identify_ctrl" 9 "nvme_init_zns_identify_ctrl" "April 2026" "libnvme API manual" LINUX
.SH NAME
nvme_init_zns_identify_ctrl \- Initialize passthru command for ZNS identify controller data
.SH SYNOPSIS
.B "void" nvme_init_zns_identify_ctrl
.BI "(struct libnvme_passthru_cmd *cmd "  ","
.BI "struct nvme_zns_id_ctrl *id "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Command data structure to initialize
.IP "id" 12
User space destination address to transfer the data
