.TH "nvmf_nbft_read_files" 9 "nvmf_nbft_read_files" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvmf_nbft_read_files \- Read NBFT files from path
.SH SYNOPSIS
.B "int" nvmf_nbft_read_files
.BI "(struct nvme_global_ctx *ctx "  ","
.BI "char *path "  ","
.BI "struct nbft_file_entry **head "  ");"
.SH ARGUMENTS
.IP "ctx" 12
struct nvme_global_ctx object
.IP "path" 12
Path to NBFT files
.IP "head" 12
Pointer to store linked list of NBFT file entries
.SH "DESCRIPTION"
Reads NBFT files from the specified path and populates a linked list.
.SH "RETURN"
0 on success, or a negative error code on failure.
