.TH "nvmf_discovery_config_json" 9 "nvmf_discovery_config_json" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvmf_discovery_config_json \- Perform discovery using JSON config
.SH SYNOPSIS
.B "int" nvmf_discovery_config_json
.BI "(struct nvme_global_ctx *ctx "  ","
.BI "struct nvmf_context *fctx "  ","
.BI "bool connect "  ","
.BI "bool force "  ");"
.SH ARGUMENTS
.IP "ctx" 12
Global context
.IP "fctx" 12
Fabrics context
.IP "connect" 12
Whether to connect discovered subsystems
.IP "force" 12
Force discovery even if already connected
.SH "DESCRIPTION"
Performs discovery using a JSON configuration.
.SH "RETURN"
0 on success, or a negative error code on failure.
