.TH "nvmf_connect_config_json" 9 "nvmf_connect_config_json" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvmf_connect_config_json \- Connect using JSON config
.SH SYNOPSIS
.B "int" nvmf_connect_config_json
.BI "(struct nvme_global_ctx *ctx "  ","
.BI "struct nvmf_context *fctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
Global context
.IP "fctx" 12
Fabrics context
.SH "DESCRIPTION"
Connects to the fabrics subsystem using a JSON configuration.
.SH "RETURN"
0 on success, or a negative error code on failure.
