.TH "nvmf_free_uri" 9 "nvmf_free_uri" "March 2026" "libnvme API manual" LINUX
.SH NAME
nvmf_free_uri \- Free the URI structure
.SH SYNOPSIS
.B "void" nvmf_free_uri
.BI "(struct nvme_fabrics_uri *uri "  ");"
.SH ARGUMENTS
.IP "uri" 12
\fInvme_fabrics_uri\fP structure
.SH "DESCRIPTION"
Free an \fInvme_fabrics_uri\fP structure.
