# SPDX-License-Identifier: LGPL-2.1-or-later

/**
 * This file is part of libnvme.
 *
 * Copyright (c) 2025, Dell Technologies Inc. or its subsidiaries.
 * Authors: Martin Belanger <Martin.Belanger@dell.com>
 *
 */

LIBNVMF_ACCESSORS_3 {
	global:
		libnvmf_discovery_args_get_lsp;
		libnvmf_discovery_args_set_lsp;
		libnvmf_discovery_args_get_max_retries;
		libnvmf_discovery_args_set_max_retries;
};
