# SPDX-License-Identifier: Apache-2.0
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  apt_packages:
    - meson
    - python3-lxml
    - docbook-xsl
    - xsltproc
    - pandoc
    - asciidoc
  jobs:
    pre_build:
      - scripts/build.sh rst_docs

sphinx:
  configuration: .build-ci/libnvme/doc/conf.py
