# SPDX-License-Identifier: Apache-2.0
version: 2

build:
  os: debian
  image: ghcr.io/linux-nvme/debian:latest
  tools:
    python: "3.11"

  commands:
    - scripts/build.sh rst_docs

sphinx:
  configuration: .build-ci/libnvme/doc/conf.py
