.TH "libnvme" 2 "enum nvme_dsm_attributes" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_dsm_attributes \- 
.SH SYNOPSIS
enum nvme_dsm_attributes {
.br
.BI "    NVME_DSMGMT_IDR"
, 
.br
.br
.BI "    NVME_DSMGMT_IDW"
, 
.br
.br
.BI "    NVME_DSMGMT_AD"

};
.SH Constants
.IP "NVME_DSMGMT_IDR" 12
-- undescribed --
.IP "NVME_DSMGMT_IDW" 12
-- undescribed --
.IP "NVME_DSMGMT_AD" 12
-- undescribed --
