.TH "libnvme" 2 "enum nvme_ae_info_error" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_ae_info_error \- 
.SH SYNOPSIS
enum nvme_ae_info_error {
.br
.BI "    NVME_AER_ERROR_INVALID_DB_REG"
, 
.br
.br
.BI "    NVME_AER_ERROR_INVALID_DB_VAL"
, 
.br
.br
.BI "    NVME_AER_ERROR_DIAG_FAILURE"
, 
.br
.br
.BI "    NVME_AER_ERROR_PERSISTENT_INTERNAL_ERROR"
, 
.br
.br
.BI "    NVME_AER_ERROR_TRANSIENT_INTERNAL_ERROR"
, 
.br
.br
.BI "    NVME_AER_ERROR_FW_IMAGE_LOAD_ERROR"

};
.SH Constants
.IP "NVME_AER_ERROR_INVALID_DB_REG" 12
-- undescribed --
.IP "NVME_AER_ERROR_INVALID_DB_VAL" 12
-- undescribed --
.IP "NVME_AER_ERROR_DIAG_FAILURE" 12
-- undescribed --
.IP "NVME_AER_ERROR_PERSISTENT_INTERNAL_ERROR" 12
-- undescribed --
.IP "NVME_AER_ERROR_TRANSIENT_INTERNAL_ERROR" 12
-- undescribed --
.IP "NVME_AER_ERROR_FW_IMAGE_LOAD_ERROR" 12
-- undescribed --
