.TH "libnvme" 2 "enum nvme_cmd_format_ses" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_cmd_format_ses \- 
.SH SYNOPSIS
enum nvme_cmd_format_ses {
.br
.BI "    NVME_FORMAT_SES_NONE"
, 
.br
.br
.BI "    NVME_FORMAT_SES_USER_DATA_ERASE"
, 
.br
.br
.BI "    NVME_FORMAT_SES_CRYPTO_ERASE"

};
.SH Constants
.IP "NVME_FORMAT_SES_NONE" 12
-- undescribed --
.IP "NVME_FORMAT_SES_USER_DATA_ERASE" 12
-- undescribed --
.IP "NVME_FORMAT_SES_CRYPTO_ERASE" 12
-- undescribed --
