.TH "libnvme" 2 "enum nvme_reservation_rtype" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_reservation_rtype \- 
.SH SYNOPSIS
enum nvme_reservation_rtype {
.br
.BI "    NVME_RESERVATION_RTYPE_WE"
, 
.br
.br
.BI "    NVME_RESERVATION_RTYPE_EA"
, 
.br
.br
.BI "    NVME_RESERVATION_RTYPE_WERO"
, 
.br
.br
.BI "    NVME_RESERVATION_RTYPE_EARO"
, 
.br
.br
.BI "    NVME_RESERVATION_RTYPE_WEAR"
, 
.br
.br
.BI "    NVME_RESERVATION_RTYPE_EAAR"

};
.SH Constants
.IP "NVME_RESERVATION_RTYPE_WE" 12
-- undescribed --
.IP "NVME_RESERVATION_RTYPE_EA" 12
-- undescribed --
.IP "NVME_RESERVATION_RTYPE_WERO" 12
-- undescribed --
.IP "NVME_RESERVATION_RTYPE_EARO" 12
-- undescribed --
.IP "NVME_RESERVATION_RTYPE_WEAR" 12
-- undescribed --
.IP "NVME_RESERVATION_RTYPE_EAAR" 12
-- undescribed --
