.TH "libnvme" 2 "enum nvme_features_id" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_features_id \- 
.SH SYNOPSIS
enum nvme_features_id {
.br
.BI "    NVME_FEAT_FID_ARBITRATION"
, 
.br
.br
.BI "    NVME_FEAT_FID_POWER_MGMT"
, 
.br
.br
.BI "    NVME_FEAT_FID_LBA_RANGE"
, 
.br
.br
.BI "    NVME_FEAT_FID_TEMP_THRESH"
, 
.br
.br
.BI "    NVME_FEAT_FID_ERR_RECOVERY"
, 
.br
.br
.BI "    NVME_FEAT_FID_VOLATILE_WC"
, 
.br
.br
.BI "    NVME_FEAT_FID_NUM_QUEUES"
, 
.br
.br
.BI "    NVME_FEAT_FID_IRQ_COALESCE"
, 
.br
.br
.BI "    NVME_FEAT_FID_IRQ_CONFIG"
, 
.br
.br
.BI "    NVME_FEAT_FID_WRITE_ATOMIC"
, 
.br
.br
.BI "    NVME_FEAT_FID_ASYNC_EVENT"
, 
.br
.br
.BI "    NVME_FEAT_FID_AUTO_PST"
, 
.br
.br
.BI "    NVME_FEAT_FID_HOST_MEM_BUF"
, 
.br
.br
.BI "    NVME_FEAT_FID_TIMESTAMP"
, 
.br
.br
.BI "    NVME_FEAT_FID_KATO"
, 
.br
.br
.BI "    NVME_FEAT_FID_HCTM"
, 
.br
.br
.BI "    NVME_FEAT_FID_NOPSC"
, 
.br
.br
.BI "    NVME_FEAT_FID_RRL"
, 
.br
.br
.BI "    NVME_FEAT_FID_PLM_CONFIG"
, 
.br
.br
.BI "    NVME_FEAT_FID_PLM_WINDOW"
, 
.br
.br
.BI "    NVME_FEAT_FID_LBA_STS_INTERVAL"
, 
.br
.br
.BI "    NVME_FEAT_FID_HOST_BEHAVIOR"
, 
.br
.br
.BI "    NVME_FEAT_FID_SANITIZE"
, 
.br
.br
.BI "    NVME_FEAT_FID_ENDURANCE_EVT_CFG"
, 
.br
.br
.BI "    NVME_FEAT_FID_SW_PROGRESS"
, 
.br
.br
.BI "    NVME_FEAT_FID_HOST_ID"
, 
.br
.br
.BI "    NVME_FEAT_FID_RESV_MASK"
, 
.br
.br
.BI "    NVME_FEAT_RESV_PERSIST"
, 
.br
.br
.BI "    NVME_FEAT_FID_WRITE_PROTECT"

};
.SH Constants
.IP "NVME_FEAT_FID_ARBITRATION" 12
-- undescribed --
.IP "NVME_FEAT_FID_POWER_MGMT" 12
-- undescribed --
.IP "NVME_FEAT_FID_LBA_RANGE" 12
-- undescribed --
.IP "NVME_FEAT_FID_TEMP_THRESH" 12
-- undescribed --
.IP "NVME_FEAT_FID_ERR_RECOVERY" 12
-- undescribed --
.IP "NVME_FEAT_FID_VOLATILE_WC" 12
-- undescribed --
.IP "NVME_FEAT_FID_NUM_QUEUES" 12
-- undescribed --
.IP "NVME_FEAT_FID_IRQ_COALESCE" 12
-- undescribed --
.IP "NVME_FEAT_FID_IRQ_CONFIG" 12
-- undescribed --
.IP "NVME_FEAT_FID_WRITE_ATOMIC" 12
-- undescribed --
.IP "NVME_FEAT_FID_ASYNC_EVENT" 12
-- undescribed --
.IP "NVME_FEAT_FID_AUTO_PST" 12
-- undescribed --
.IP "NVME_FEAT_FID_HOST_MEM_BUF" 12
-- undescribed --
.IP "NVME_FEAT_FID_TIMESTAMP" 12
-- undescribed --
.IP "NVME_FEAT_FID_KATO" 12
-- undescribed --
.IP "NVME_FEAT_FID_HCTM" 12
-- undescribed --
.IP "NVME_FEAT_FID_NOPSC" 12
-- undescribed --
.IP "NVME_FEAT_FID_RRL" 12
-- undescribed --
.IP "NVME_FEAT_FID_PLM_CONFIG" 12
-- undescribed --
.IP "NVME_FEAT_FID_PLM_WINDOW" 12
-- undescribed --
.IP "NVME_FEAT_FID_LBA_STS_INTERVAL" 12
-- undescribed --
.IP "NVME_FEAT_FID_HOST_BEHAVIOR" 12
-- undescribed --
.IP "NVME_FEAT_FID_SANITIZE" 12
-- undescribed --
.IP "NVME_FEAT_FID_ENDURANCE_EVT_CFG" 12
-- undescribed --
.IP "NVME_FEAT_FID_SW_PROGRESS" 12
-- undescribed --
.IP "NVME_FEAT_FID_HOST_ID" 12
-- undescribed --
.IP "NVME_FEAT_FID_RESV_MASK" 12
-- undescribed --
.IP "NVME_FEAT_RESV_PERSIST" 12
-- undescribed --
.IP "NVME_FEAT_FID_WRITE_PROTECT" 12
-- undescribed --
