.TH "libnvme" 2 "enum nvme_dst_stc" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_dst_stc \- 
.SH SYNOPSIS
enum nvme_dst_stc {
.br
.BI "    NVME_DST_STC_SHORT"
, 
.br
.br
.BI "    NVME_DST_STC_LONG"
, 
.br
.br
.BI "    NVME_DST_STC_VS"
, 
.br
.br
.BI "    NVME_DST_STC_ABORT"

};
.SH Constants
.IP "NVME_DST_STC_SHORT" 12
-- undescribed --
.IP "NVME_DST_STC_LONG" 12
-- undescribed --
.IP "NVME_DST_STC_VS" 12
-- undescribed --
.IP "NVME_DST_STC_ABORT" 12
-- undescribed --
