.TH "libnvme" 2 "enum nvme_ae_type" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_ae_type \- 
.SH SYNOPSIS
enum nvme_ae_type {
.br
.BI "    NVME_AER_ERROR"
, 
.br
.br
.BI "    NVME_AER_SMART"
, 
.br
.br
.BI "    NVME_AER_NOTICE"
, 
.br
.br
.BI "    NVME_AER_CSS"
, 
.br
.br
.BI "    NVME_AER_VS"

};
.SH Constants
.IP "NVME_AER_ERROR" 12
-- undescribed --
.IP "NVME_AER_SMART" 12
-- undescribed --
.IP "NVME_AER_NOTICE" 12
-- undescribed --
.IP "NVME_AER_CSS" 12
-- undescribed --
.IP "NVME_AER_VS" 12
-- undescribed --
