.TH "libnvme" 2 "enum nvme_io_opcode" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_io_opcode \- 
.SH SYNOPSIS
enum nvme_io_opcode {
.br
.BI "    nvme_cmd_flush"
, 
.br
.br
.BI "    nvme_cmd_write"
, 
.br
.br
.BI "    nvme_cmd_read"
, 
.br
.br
.BI "    nvme_cmd_write_uncor"
, 
.br
.br
.BI "    nvme_cmd_compare"
, 
.br
.br
.BI "    nvme_cmd_write_zeroes"
, 
.br
.br
.BI "    nvme_cmd_dsm"
, 
.br
.br
.BI "    nvme_cmd_verify"
, 
.br
.br
.BI "    nvme_cmd_resv_register"
, 
.br
.br
.BI "    nvme_cmd_resv_report"
, 
.br
.br
.BI "    nvme_cmd_resv_acquire"
, 
.br
.br
.BI "    nvme_cmd_resv_release"

};
.SH Constants
.IP "nvme_cmd_flush" 12
-- undescribed --
.IP "nvme_cmd_write" 12
-- undescribed --
.IP "nvme_cmd_read" 12
-- undescribed --
.IP "nvme_cmd_write_uncor" 12
-- undescribed --
.IP "nvme_cmd_compare" 12
-- undescribed --
.IP "nvme_cmd_write_zeroes" 12
-- undescribed --
.IP "nvme_cmd_dsm" 12
-- undescribed --
.IP "nvme_cmd_verify" 12
-- undescribed --
.IP "nvme_cmd_resv_register" 12
-- undescribed --
.IP "nvme_cmd_resv_report" 12
-- undescribed --
.IP "nvme_cmd_resv_acquire" 12
-- undescribed --
.IP "nvme_cmd_resv_release" 12
-- undescribed --
