.TH "libnvme" 2 "enum nvme_cmd_get_log_lid" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_cmd_get_log_lid \- 
.SH SYNOPSIS
enum nvme_cmd_get_log_lid {
.br
.BI "    NVME_LOG_LID_ERROR"
, 
.br
.br
.BI "    NVME_LOG_LID_SMART"
, 
.br
.br
.BI "    NVME_LOG_LID_FW_SLOT"
, 
.br
.br
.BI "    NVME_LOG_LID_CHANGED_NS"
, 
.br
.br
.BI "    NVME_LOG_LID_CMD_EFFECTS"
, 
.br
.br
.BI "    NVME_LOG_LID_DEVICE_SELF_TEST"
, 
.br
.br
.BI "    NVME_LOG_LID_TELEMETRY_HOST"
, 
.br
.br
.BI "    NVME_LOG_LID_TELEMETRY_CTRL"
, 
.br
.br
.BI "    NVME_LOG_LID_ENDURANCE_GROUP"
, 
.br
.br
.BI "    NVME_LOG_LID_PREDICTABLE_LAT_NVMSET"
, 
.br
.br
.BI "    NVME_LOG_LID_PREDICTABLE_LAT_AGG"
, 
.br
.br
.BI "    NVME_LOG_LID_ANA"
, 
.br
.br
.BI "    NVME_LOG_LID_PERSISTENT_EVENT"
, 
.br
.br
.BI "    NVME_LOG_LID_LBA_STATUS"
, 
.br
.br
.BI "    NVME_LOG_LID_ENDURANCE_GRP_EVT"
, 
.br
.br
.BI "    NVME_LOG_LID_DISCOVER"
, 
.br
.br
.BI "    NVME_LOG_LID_RESERVATION"
, 
.br
.br
.BI "    NVME_LOG_LID_SANITIZE"

};
.SH Constants
.IP "NVME_LOG_LID_ERROR" 12
-- undescribed --
.IP "NVME_LOG_LID_SMART" 12
-- undescribed --
.IP "NVME_LOG_LID_FW_SLOT" 12
-- undescribed --
.IP "NVME_LOG_LID_CHANGED_NS" 12
-- undescribed --
.IP "NVME_LOG_LID_CMD_EFFECTS" 12
-- undescribed --
.IP "NVME_LOG_LID_DEVICE_SELF_TEST" 12
-- undescribed --
.IP "NVME_LOG_LID_TELEMETRY_HOST" 12
-- undescribed --
.IP "NVME_LOG_LID_TELEMETRY_CTRL" 12
-- undescribed --
.IP "NVME_LOG_LID_ENDURANCE_GROUP" 12
-- undescribed --
.IP "NVME_LOG_LID_PREDICTABLE_LAT_NVMSET" 12
-- undescribed --
.IP "NVME_LOG_LID_PREDICTABLE_LAT_AGG" 12
-- undescribed --
.IP "NVME_LOG_LID_ANA" 12
-- undescribed --
.IP "NVME_LOG_LID_PERSISTENT_EVENT" 12
-- undescribed --
.IP "NVME_LOG_LID_LBA_STATUS" 12
-- undescribed --
.IP "NVME_LOG_LID_ENDURANCE_GRP_EVT" 12
-- undescribed --
.IP "NVME_LOG_LID_DISCOVER" 12
-- undescribed --
.IP "NVME_LOG_LID_RESERVATION" 12
-- undescribed --
.IP "NVME_LOG_LID_SANITIZE" 12
-- undescribed --
