.TH "libnvme" 2 "enum nvme_io_control_flags" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_io_control_flags \- 
.SH SYNOPSIS
enum nvme_io_control_flags {
.br
.BI "    NVME_IO_DTYPE_STREAMS"
, 
.br
.br
.BI "    NVME_IO_DEAC"
, 
.br
.br
.BI "    NVME_IO_PRINFO_PRCHK_REF"
, 
.br
.br
.BI "    NVME_IO_PRINFO_PRCHK_APP"
, 
.br
.br
.BI "    NVME_IO_PRINFO_PRCHK_GUARD"
, 
.br
.br
.BI "    NVME_IO_PRINFO_PRACT"
, 
.br
.br
.BI "    NVME_IO_FUA"
, 
.br
.br
.BI "    NVME_IO_LR"

};
.SH Constants
.IP "NVME_IO_DTYPE_STREAMS" 12
-- undescribed --
.IP "NVME_IO_DEAC" 12
-- undescribed --
.IP "NVME_IO_PRINFO_PRCHK_REF" 12
-- undescribed --
.IP "NVME_IO_PRINFO_PRCHK_APP" 12
-- undescribed --
.IP "NVME_IO_PRINFO_PRCHK_GUARD" 12
-- undescribed --
.IP "NVME_IO_PRINFO_PRACT" 12
-- undescribed --
.IP "NVME_IO_FUA" 12
-- undescribed --
.IP "NVME_IO_LR" 12
-- undescribed --
