.TH "libnvme" 2 "enum nvme_id_ctrl_ctratt" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_ctratt \- 
.SH SYNOPSIS
enum nvme_id_ctrl_ctratt {
.br
.BI "    NVME_CTRL_CTRATT_128_ID"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_NON_OP_PSP"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_NVM_SETS"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_READ_RECV_LVLS"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_ENDURANCE_GROUPS"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_PREDICTABLE_LAT"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_TBKAS"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_NAMESPACE_GRANULARITY"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_SQ_ASSOCIATIONS"
, 
.br
.br
.BI "    NVME_CTRL_CTRATT_UUID_LIST"

};
.SH Constants
.IP "NVME_CTRL_CTRATT_128_ID" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_NON_OP_PSP" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_NVM_SETS" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_READ_RECV_LVLS" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_ENDURANCE_GROUPS" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_PREDICTABLE_LAT" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_TBKAS" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_NAMESPACE_GRANULARITY" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_SQ_ASSOCIATIONS" 12
-- undescribed --
.IP "NVME_CTRL_CTRATT_UUID_LIST" 12
-- undescribed --
