.TH "libnvme" 2 "enum nvme_feat_tmpthresh_thsel" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_feat_tmpthresh_thsel \- 
.SH SYNOPSIS
enum nvme_feat_tmpthresh_thsel {
.br
.BI "    NVME_FEATURE_TEMPTHRESH_THSEL_OVER"
, 
.br
.br
.BI "    NVME_FEATURETEMPTHRESH__THSEL_UNDER"

};
.SH Constants
.IP "NVME_FEATURE_TEMPTHRESH_THSEL_OVER" 12
-- undescribed --
.IP "NVME_FEATURETEMPTHRESH__THSEL_UNDER" 12
-- undescribed --
