.TH "libnvme" 2 "enum nvme_id_ctrl_cntrltype" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_cntrltype \- 
.SH SYNOPSIS
enum nvme_id_ctrl_cntrltype {
.br
.BI "    NVME_CTRL_CNTRLTYPE_IO"
, 
.br
.br
.BI "    NVME_CTRL_CNTRLTYPE_DISCOVERY"
, 
.br
.br
.BI "    NVME_CTRL_CNTRLTYPE_ADMIN"

};
.SH Constants
.IP "NVME_CTRL_CNTRLTYPE_IO" 12
-- undescribed --
.IP "NVME_CTRL_CNTRLTYPE_DISCOVERY" 12
-- undescribed --
.IP "NVME_CTRL_CNTRLTYPE_ADMIN" 12
-- undescribed --
