.TH "libnvme" 2 "enum nvme_fw_commit_ca" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_fw_commit_ca \- 
.SH SYNOPSIS
enum nvme_fw_commit_ca {
.br
.BI "    NVME_FW_COMMIT_CA_REPLACE"
, 
.br
.br
.BI "    NVME_FW_COMMIT_CA_REPLACE_AND_ACTIVATE"
, 
.br
.br
.BI "    NVME_FW_COMMIT_CA_SET_ACTIVE"
, 
.br
.br
.BI "    NVME_FW_COMMIT_CA_REPLACE_AND_ACTIVATE_IMMEDIATE"
, 
.br
.br
.BI "    NVME_FW_COMMIT_CA_REPLACE_BOOT_PARTITION"
, 
.br
.br
.BI "    NVME_FW_COMMIT_CA_ACTIVATE_BOOT_PARTITION"

};
.SH Constants
.IP "NVME_FW_COMMIT_CA_REPLACE" 12
-- undescribed --
.IP "NVME_FW_COMMIT_CA_REPLACE_AND_ACTIVATE" 12
-- undescribed --
.IP "NVME_FW_COMMIT_CA_SET_ACTIVE" 12
-- undescribed --
.IP "NVME_FW_COMMIT_CA_REPLACE_AND_ACTIVATE_IMMEDIATE" 12
-- undescribed --
.IP "NVME_FW_COMMIT_CA_REPLACE_BOOT_PARTITION" 12
-- undescribed --
.IP "NVME_FW_COMMIT_CA_ACTIVATE_BOOT_PARTITION" 12
-- undescribed --
