.TH "libnvme" 2 "enum nvme_eg_critical_warning_flags" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_eg_critical_warning_flags \- 
.SH SYNOPSIS
enum nvme_eg_critical_warning_flags {
.br
.BI "    NVME_EG_CRITICAL_WARNING_SPARE"
, 
.br
.br
.BI "    NVME_EG_CRITICAL_WARNING_DEGRADED"
, 
.br
.br
.BI "    NVME_EG_CRITICAL_WARNING_READ_ONLY"

};
.SH Constants
.IP "NVME_EG_CRITICAL_WARNING_SPARE" 12
-- undescribed --
.IP "NVME_EG_CRITICAL_WARNING_DEGRADED" 12
-- undescribed --
.IP "NVME_EG_CRITICAL_WARNING_READ_ONLY" 12
-- undescribed --
