.TH "libnvme" 2 "enum nvme_subsys_type" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_subsys_type \- 
.SH SYNOPSIS
enum nvme_subsys_type {
.br
.BI "    NVME_NQN_DISC"
, 
.br
.br
.BI "    NVME_NQN_NVME"

};
.SH Constants
.IP "NVME_NQN_DISC" 12
Discovery type target subsystem
.IP "NVME_NQN_NVME" 12
NVME type target subsystem
