.TH "libnvme" 2 "enum nvme_reservation_cptpl" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_reservation_cptpl \- 
.SH SYNOPSIS
enum nvme_reservation_cptpl {
.br
.BI "    NVME_RESERVATION_CPTPL_NO_CHANGE"
, 
.br
.br
.BI "    NVME_RESERVATION_CPTPL_CLEAR"
, 
.br
.br
.BI "    NVME_RESERVATION_CPTPL_PERSIST"

};
.SH Constants
.IP "NVME_RESERVATION_CPTPL_NO_CHANGE" 12
-- undescribed --
.IP "NVME_RESERVATION_CPTPL_CLEAR" 12
-- undescribed --
.IP "NVME_RESERVATION_CPTPL_PERSIST" 12
-- undescribed --
