.TH "libnvme" 2 "enum nvme_ns_mgmt_sel" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_ns_mgmt_sel \- 
.SH SYNOPSIS
enum nvme_ns_mgmt_sel {
.br
.BI "    NVME_NS_MGMT_SEL_CREATE"
, 
.br
.br
.BI "    NVME_NS_MGMT_SEL_DELETE"

};
.SH Constants
.IP "NVME_NS_MGMT_SEL_CREATE" 12
-- undescribed --
.IP "NVME_NS_MGMT_SEL_DELETE" 12
-- undescribed --
