.TH "libnvme" 2 "enum nvme_admin_opcode" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_admin_opcode \- Known NVMe admin opcodes
.SH SYNOPSIS
enum nvme_admin_opcode {
.br
.BI "    nvme_admin_delete_sq"
, 
.br
.br
.BI "    nvme_admin_create_sq"
, 
.br
.br
.BI "    nvme_admin_get_log_page"
, 
.br
.br
.BI "    nvme_admin_delete_cq"
, 
.br
.br
.BI "    nvme_admin_create_cq"
, 
.br
.br
.BI "    nvme_admin_identify"
, 
.br
.br
.BI "    nvme_admin_abort_cmd"
, 
.br
.br
.BI "    nvme_admin_set_features"
, 
.br
.br
.BI "    nvme_admin_get_features"
, 
.br
.br
.BI "    nvme_admin_async_event"
, 
.br
.br
.BI "    nvme_admin_ns_mgmt"
, 
.br
.br
.BI "    nvme_admin_fw_commit"
, 
.br
.br
.BI "    nvme_admin_fw_download"
, 
.br
.br
.BI "    nvme_admin_dev_self_test"
, 
.br
.br
.BI "    nvme_admin_ns_attach"
, 
.br
.br
.BI "    nvme_admin_keep_alive"
, 
.br
.br
.BI "    nvme_admin_directive_send"
, 
.br
.br
.BI "    nvme_admin_directive_recv"
, 
.br
.br
.BI "    nvme_admin_virtual_mgmt"
, 
.br
.br
.BI "    nvme_admin_nvme_mi_send"
, 
.br
.br
.BI "    nvme_admin_nvme_mi_recv"
, 
.br
.br
.BI "    nvme_admin_dbbuf"
, 
.br
.br
.BI "    nvme_admin_fabrics"
, 
.br
.br
.BI "    nvme_admin_format_nvm"
, 
.br
.br
.BI "    nvme_admin_security_send"
, 
.br
.br
.BI "    nvme_admin_security_recv"
, 
.br
.br
.BI "    nvme_admin_sanitize_nvm"
, 
.br
.br
.BI "    nvme_admin_get_lba_status"

};
.SH Constants
.IP "nvme_admin_delete_sq" 12
-- undescribed --
.IP "nvme_admin_create_sq" 12
-- undescribed --
.IP "nvme_admin_get_log_page" 12
-- undescribed --
.IP "nvme_admin_delete_cq" 12
-- undescribed --
.IP "nvme_admin_create_cq" 12
-- undescribed --
.IP "nvme_admin_identify" 12
-- undescribed --
.IP "nvme_admin_abort_cmd" 12
-- undescribed --
.IP "nvme_admin_set_features" 12
-- undescribed --
.IP "nvme_admin_get_features" 12
-- undescribed --
.IP "nvme_admin_async_event" 12
-- undescribed --
.IP "nvme_admin_ns_mgmt" 12
-- undescribed --
.IP "nvme_admin_fw_commit" 12
-- undescribed --
.IP "nvme_admin_fw_download" 12
-- undescribed --
.IP "nvme_admin_dev_self_test" 12
-- undescribed --
.IP "nvme_admin_ns_attach" 12
-- undescribed --
.IP "nvme_admin_keep_alive" 12
-- undescribed --
.IP "nvme_admin_directive_send" 12
-- undescribed --
.IP "nvme_admin_directive_recv" 12
-- undescribed --
.IP "nvme_admin_virtual_mgmt" 12
-- undescribed --
.IP "nvme_admin_nvme_mi_send" 12
-- undescribed --
.IP "nvme_admin_nvme_mi_recv" 12
-- undescribed --
.IP "nvme_admin_dbbuf" 12
-- undescribed --
.IP "nvme_admin_fabrics" 12
-- undescribed --
.IP "nvme_admin_format_nvm" 12
-- undescribed --
.IP "nvme_admin_security_send" 12
-- undescribed --
.IP "nvme_admin_security_recv" 12
-- undescribed --
.IP "nvme_admin_sanitize_nvm" 12
-- undescribed --
.IP "nvme_admin_get_lba_status" 12
-- undescribed --
