.TH "libnvme" 2 "enum nvme_reservation_racqa" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_reservation_racqa \- 
.SH SYNOPSIS
enum nvme_reservation_racqa {
.br
.BI "    NVME_RESERVATION_RACQA_ACQUIRE"
, 
.br
.br
.BI "    NVME_RESERVATION_RACQA_PREEMPT"
, 
.br
.br
.BI "    NVME_RESERVATION_RACQA_PREEMPT_AND_ABORT"

};
.SH Constants
.IP "NVME_RESERVATION_RACQA_ACQUIRE" 12
-- undescribed --
.IP "NVME_RESERVATION_RACQA_PREEMPT" 12
-- undescribed --
.IP "NVME_RESERVATION_RACQA_PREEMPT_AND_ABORT" 12
-- undescribed --
