.TH "libnvme" 2 "enum nvme_id_ctrl_lpa" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_lpa \- Flags indicating optional attributes for log pages that are accessed via the Get Log Page command.
.SH SYNOPSIS
enum nvme_id_ctrl_lpa {
.br
.BI "    NVME_CTRL_LPA_SMART_PER_NS"
, 
.br
.br
.BI "    NVME_CTRL_LPA_CMD_EFFECTS"
, 
.br
.br
.BI "    NVME_CTRL_LPA_EXTENDED"
, 
.br
.br
.BI "    NVME_CTRL_LPA_TELEMETRY"
, 
.br
.br
.BI "    NVME_CTRL_LPA_PERSETENT_EVENT"

};
.SH Constants
.IP "NVME_CTRL_LPA_SMART_PER_NS" 12
-- undescribed --
.IP "NVME_CTRL_LPA_CMD_EFFECTS" 12
-- undescribed --
.IP "NVME_CTRL_LPA_EXTENDED" 12
-- undescribed --
.IP "NVME_CTRL_LPA_TELEMETRY" 12
-- undescribed --
.IP "NVME_CTRL_LPA_PERSETENT_EVENT" 12
-- undescribed --
