.TH "libnvme" 2 "enum nvme_identify_cns" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_identify_cns \- 
.SH SYNOPSIS
enum nvme_identify_cns {
.br
.BI "    NVME_IDENTIFY_CNS_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CTRL"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_ACTIVE_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_DESC_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NVMSET_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ALLOCATED_NS_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ALLOCATED_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_PRIMARY_CTRL_CAP"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_SECONDARY_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_GRANULARITY"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_UUID_LIST"

};
.SH Constants
.IP "NVME_IDENTIFY_CNS_NS" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_CTRL" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_NS_ACTIVE_LIST" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_NS_DESC_LIST" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_NVMSET_LIST" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_ALLOCATED_NS_LIST" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_ALLOCATED_NS" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_NS_CTRL_LIST" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_CTRL_LIST" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_PRIMARY_CTRL_CAP" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_SECONDARY_CTRL_LIST" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_NS_GRANULARITY" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_UUID_LIST" 12
-- undescribed --
