.TH "libnvme" 2 "enum nvme_reservation_rrela" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_reservation_rrela \- 
.SH SYNOPSIS
enum nvme_reservation_rrela {
.br
.BI "    NVME_RESERVATION_RRELA_RELEASE"
, 
.br
.br
.BI "    NVME_RESERVATION_RRELA_CLEAR"

};
.SH Constants
.IP "NVME_RESERVATION_RRELA_RELEASE" 12
-- undescribed --
.IP "NVME_RESERVATION_RRELA_CLEAR" 12
-- undescribed --
