.TH "libnvme" 2 "enum nvme_cmd_format_pi" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_cmd_format_pi \- 
.SH SYNOPSIS
enum nvme_cmd_format_pi {
.br
.BI "    NVME_FORMAT_PI_DISABLE"
, 
.br
.br
.BI "    NVME_FORMAT_PI_TYPE1"
, 
.br
.br
.BI "    NVME_FORMAT_PI_TYPE2"
, 
.br
.br
.BI "    NVME_FORMAT_PI_TYPE3"

};
.SH Constants
.IP "NVME_FORMAT_PI_DISABLE" 12
-- undescribed --
.IP "NVME_FORMAT_PI_TYPE1" 12
-- undescribed --
.IP "NVME_FORMAT_PI_TYPE2" 12
-- undescribed --
.IP "NVME_FORMAT_PI_TYPE3" 12
-- undescribed --
