.TH "libnvme" 2 "enum nvme_ns_attach_sel" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_ns_attach_sel \-  NVME_NS_ATTACH_SEL_CTRL_ATTACH: NVME_NP_ATTACH_SEL_CTRL_DEATTACH:
.SH SYNOPSIS
enum nvme_ns_attach_sel {
.br
.BI "    NVME_NS_ATTACH_SEL_CTRL_ATTACH"
, 
.br
.br
.BI "    NVME_NS_ATTACH_SEL_CTRL_DEATTACH"

};
.SH Constants
.IP "NVME_NS_ATTACH_SEL_CTRL_ATTACH" 12
-- undescribed --
.IP "NVME_NS_ATTACH_SEL_CTRL_DEATTACH" 12
-- undescribed --
