.TH "libnvme" 2 "enum nvme_feat_plm_window_select" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_feat_plm_window_select \- 
.SH SYNOPSIS
enum nvme_feat_plm_window_select {
.br
.BI "    NVME_FEATURE_PLM_DTWIN"
, 
.br
.br
.BI "    NVME_FEATURE_PLM_NDWIN"

};
.SH Constants
.IP "NVME_FEATURE_PLM_DTWIN" 12
-- undescribed --
.IP "NVME_FEATURE_PLM_NDWIN" 12
-- undescribed --
