.TH "libnvme" 2 "enum nvme_ae_info_smart" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_ae_info_smart \- 
.SH SYNOPSIS
enum nvme_ae_info_smart {
.br
.BI "    NVME_AER_SMART_SUBSYSTEM_RELIABILITY"
, 
.br
.br
.BI "    NVME_AER_SMART_TEMPERATURE_THRESHOLD"
, 
.br
.br
.BI "    NVME_AER_SMART_SPARE_THRESHOLD"

};
.SH Constants
.IP "NVME_AER_SMART_SUBSYSTEM_RELIABILITY" 12
-- undescribed --
.IP "NVME_AER_SMART_TEMPERATURE_THRESHOLD" 12
-- undescribed --
.IP "NVME_AER_SMART_SPARE_THRESHOLD" 12
-- undescribed --
