.TH "libnvme" 2 "enum nvme_directive_send_doper" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_directive_send_doper \- 
.SH SYNOPSIS
enum nvme_directive_send_doper {
.br
.BI "    NVME_DIRECTIVE_SEND_IDENTIFY_DOPER_ENDIR"
, 
.br
.br
.BI "    NVME_DIRECTIVE_SEND_STREAMS_DOPER_RELEASE_IDENTIFIER"
, 
.br
.br
.BI "    NVME_DIRECTIVE_SEND_STREAMS_DOPER_RELEASE_RESOURCE"

};
.SH Constants
.IP "NVME_DIRECTIVE_SEND_IDENTIFY_DOPER_ENDIR" 12
-- undescribed --
.IP "NVME_DIRECTIVE_SEND_STREAMS_DOPER_RELEASE_IDENTIFIER" 12
-- undescribed --
.IP "NVME_DIRECTIVE_SEND_STREAMS_DOPER_RELEASE_RESOURCE" 12
-- undescribed --
