.TH "libnvme" 2 "enum nvme_lba_status_atype" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_lba_status_atype \- 
.SH SYNOPSIS
enum nvme_lba_status_atype {
.br
.BI "    NVME_LBA_STATUS_ATYPE_SCAN_UNTRACKED"
, 
.br
.br
.BI "    NVME_LBA_STATUS_ATYPE_SCAN_TRACKED"

};
.SH Constants
.IP "NVME_LBA_STATUS_ATYPE_SCAN_UNTRACKED" 12
-- undescribed --
.IP "NVME_LBA_STATUS_ATYPE_SCAN_TRACKED" 12
-- undescribed --
