.TH "libnvme" 2 "enum nvme_id_ctrl_oaes" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_oaes \- The typical latency in microseconds to enter Runtime D3
.SH SYNOPSIS
enum nvme_id_ctrl_oaes {
.br
.BI "    NVME_CTRL_OAES_NA"
, 
.br
.br
.BI "    NVME_CTRL_OAES_FA"
, 
.br
.br
.BI "    NVME_CTRL_OAES_ANA"
, 
.br
.br
.BI "    NVME_CTRL_OAES_PLEA"
, 
.br
.br
.BI "    NVME_CTRL_OAES_LBAS"
, 
.br
.br
.BI "    NVME_CTRL_OAES_EGE"

};
.SH Constants
.IP "NVME_CTRL_OAES_NA" 12
-- undescribed --
.IP "NVME_CTRL_OAES_FA" 12
-- undescribed --
.IP "NVME_CTRL_OAES_ANA" 12
-- undescribed --
.IP "NVME_CTRL_OAES_PLEA" 12
-- undescribed --
.IP "NVME_CTRL_OAES_LBAS" 12
:
.IP "NVME_CTRL_OAES_EGE" 12
-- undescribed --
