.TH "libnvme" 2 "enum nvme_virt_mgmt_rt" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_virt_mgmt_rt \- 
.SH SYNOPSIS
enum nvme_virt_mgmt_rt {
.br
.BI "    NVME_VIRT_MGMT_RT_VQ_RESOURCE"
, 
.br
.br
.BI "    NVME_VIRT_MGMT_RT_VI_RESOURCE"

};
.SH Constants
.IP "NVME_VIRT_MGMT_RT_VQ_RESOURCE" 12
-- undescribed --
.IP "NVME_VIRT_MGMT_RT_VI_RESOURCE" 12
-- undescribed --
