.TH "libnvme" 2 "enum nvme_directive_send_identify_endir" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_directive_send_identify_endir \- 
.SH SYNOPSIS
enum nvme_directive_send_identify_endir {
.br
.BI "    NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_DISABLE"
, 
.br
.br
.BI "    NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_ENABLE"

};
.SH Constants
.IP "NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_DISABLE" 12
-- undescribed --
.IP "NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_ENABLE" 12
-- undescribed --
