.TH "libnvme" 2 "enum nvme_directive_dtype" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_directive_dtype \- 
.SH SYNOPSIS
enum nvme_directive_dtype {
.br
.BI "    NVME_DIRECTIVE_DTYPE_IDENTIFY"
, 
.br
.br
.BI "    NVME_DIRECTIVE_DTYPE_STREAMS"

};
.SH Constants
.IP "NVME_DIRECTIVE_DTYPE_IDENTIFY" 12
-- undescribed --
.IP "NVME_DIRECTIVE_DTYPE_STREAMS" 12
-- undescribed --
