.TH "libnvme" 2 "enum nvme_id_ctrl_cmic" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_cmic \- 
.SH SYNOPSIS
enum nvme_id_ctrl_cmic {
.br
.BI "    NVME_CTRL_CMIC_MULTI_PORT"
, 
.br
.br
.BI "    NVME_CTRL_CMIC_MULTI_CTRL"
, 
.br
.br
.BI "    NVME_CTRL_CMIC_MULTI_SRIOV"
, 
.br
.br
.BI "    NVME_CTRL_CMIC_MULTI_ANA_REPORTING"

};
.SH Constants
.IP "NVME_CTRL_CMIC_MULTI_PORT" 12
-- undescribed --
.IP "NVME_CTRL_CMIC_MULTI_CTRL" 12
-- undescribed --
.IP "NVME_CTRL_CMIC_MULTI_SRIOV" 12
-- undescribed --
.IP "NVME_CTRL_CMIC_MULTI_ANA_REPORTING" 12
-- undescribed --
