.TH "libnvme" 9 "enum nbft_control_flags" "May 2025" "API Manual" LINUX
.SH NAME
enum nbft_control_flags \- Control Descriptor Flags
.SH SYNOPSIS
enum nbft_control_flags {
.br
.BI "    NBFT_CONTROL_VALID"

};
.SH Constants
.IP "NBFT_CONTROL_VALID" 12
Block Valid: indicates that the structure is valid.
