.TH "libnvme" 9 "enum nbft_info_nid_type" "May 2025" "API Manual" LINUX
.SH NAME
enum nbft_info_nid_type \- Namespace Identifier Type (NIDT)
.SH SYNOPSIS
enum nbft_info_nid_type {
.br
.BI "    NBFT_INFO_NID_TYPE_NONE"
, 
.br
.br
.BI "    NBFT_INFO_NID_TYPE_EUI64"
, 
.br
.br
.BI "    NBFT_INFO_NID_TYPE_NGUID"
, 
.br
.br
.BI "    NBFT_INFO_NID_TYPE_NS_UUID"

};
.SH Constants
.IP "NBFT_INFO_NID_TYPE_NONE" 12
No identifier available.
.IP "NBFT_INFO_NID_TYPE_EUI64" 12
The EUI-64 identifier.
.IP "NBFT_INFO_NID_TYPE_NGUID" 12
The NSGUID identifier.
.IP "NBFT_INFO_NID_TYPE_NS_UUID" 12
The UUID identifier.
