.TH "libnvme" 9 "enum nbft_ssns_ext_info_flags" "May 2025" "API Manual" LINUX
.SH NAME
enum nbft_ssns_ext_info_flags \- Subsystem and Namespace Extended Information Descriptor Flags
.SH SYNOPSIS
enum nbft_ssns_ext_info_flags {
.br
.BI "    NBFT_SSNS_EXT_INFO_VALID"
, 
.br
.br
.BI "    NBFT_SSNS_EXT_INFO_ADMIN_ASQSZ"

};
.SH Constants
.IP "NBFT_SSNS_EXT_INFO_VALID" 12
Descriptor Valid: If set to 1h, then this descriptor
is valid. If cleared to 0h, then this descriptor
is reserved.
.IP "NBFT_SSNS_EXT_INFO_ADMIN_ASQSZ" 12
Administrative ASQSZ: If set to 1h, then the value
of the ASQSZ field was provided by administrative
configuration for this SSNS record. If cleared
to 0h, then the value of the ASQSZ field was
either obtained by discovery or assumed
by the driver.
