.TH "libnvme" 9 "struct nbft_info_security" "May 2025" "API Manual" LINUX
.SH NAME
struct nbft_info_security \- Security Profile Descriptor
.SH SYNOPSIS
struct nbft_info_security {
.br
.BI "    int index;"
.br
.BI "
};
.br

.SH Members
.IP "index" 12
The number of this Security Profile Descriptor in the Security
Profile Descriptor List.
