.TH "libnvme" 9 "struct nbft_info_discovery" "May 2025" "API Manual" LINUX
.SH NAME
struct nbft_info_discovery \- Discovery Descriptor
.SH SYNOPSIS
struct nbft_info_discovery {
.br
.BI "    int index;"
.br
.BI "    struct nbft_info_security *security;"
.br
.BI "    struct nbft_info_hfi *hfi;"
.br
.BI "    char *uri;"
.br
.BI "    char *nqn;"
.br
.BI "
};
.br

.SH Members
.IP "index" 12
The number of this Discovery Descriptor in the Discovery
Descriptor List.
.IP "security" 12
The Security Profile Descriptor, see \fIstruct nbft_info_security\fP.
.IP "hfi" 12
The HFI Descriptor associated with this Discovery Descriptor.
See \fIstruct nbft_info_hfi\fP.
.IP "uri" 12
A URI which indicates an NVMe Discovery controller associated
with this Discovery Descriptor.
.IP "nqn" 12
An NVMe Discovery controller NQN.
