.TH "libnvme" 9 "enum nbft_discovery_flags" "May 2025" "API Manual" LINUX
.SH NAME
enum nbft_discovery_flags \- Discovery Descriptor Flags
.SH SYNOPSIS
enum nbft_discovery_flags {
.br
.BI "    NBFT_DISCOVERY_VALID"

};
.SH Constants
.IP "NBFT_DISCOVERY_VALID" 12
Descriptor Valid: if set to 1h, then this descriptor
is valid. If cleared to 0h, then this descriptor
is reserved.
