.TH "libnvme" 9 "enum nbft_security_secret_type" "May 2025" "API Manual" LINUX
.SH NAME
enum nbft_security_secret_type \- Security Profile Descriptor Secret Type
.SH SYNOPSIS
enum nbft_security_secret_type {
.br
.BI "    NBFT_SECURITY_SECRET_REDFISH_HOST_IFACE_URI"

};
.SH Constants
.IP "NBFT_SECURITY_SECRET_REDFISH_HOST_IFACE_URI" 12
Redfish Host Interface URI:
If set to 1h, then the Secret Keypath
Object Reference is a URI pointing
to a Redfish Key Collection Object
that contains the PSK.
