.TH "nvme_mi_aem_aemti_get_aemgn" 9 "nvme_mi_aem_aemti_get_aemgn" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_aemti_get_aemgn \- return aemgn from aemti field
.SH SYNOPSIS
.B "__u8" nvme_mi_aem_aemti_get_aemgn
.BI "(__u8 aemti "  ");"
.SH ARGUMENTS
.IP "aemti" 12
aemti field from \fInvme_mi_aem_occ_list_hdr\fP
.SH "RETURN"
aemgn value
