.TH "nvme_mi_aem_aeolli_get_aeoltl" 9 "nvme_mi_aem_aeolli_get_aeoltl" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_aeolli_get_aeoltl \- return aeoltl from aeolli field
.SH SYNOPSIS
.B "__u32" nvme_mi_aem_aeolli_get_aeoltl
.BI "(__u8 *aeolli "  ");"
.SH ARGUMENTS
.IP "aeolli" 12
Pointer to 3 byte aeolli field from \fInvme_mi_aem_occ_list_hdr\fP
.SH "RETURN"
aeoltl value
