.TH "libnvme" 9 "struct nvme_mi_port_pcie" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_mi_port_pcie \- PCIe Port Specific Data
.SH SYNOPSIS
struct nvme_mi_port_pcie {
.br
.BI "    __u8 mps;"
.br
.BI "    __u8 sls;"
.br
.BI "    __u8 cls;"
.br
.BI "    __u8 mlw;"
.br
.BI "    __u8 nlw;"
.br
.BI "    __u8 pn;"
.br
.BI "    __u8 rsvd14[18];"
.br
.BI "
};
.br

.SH Members
.IP "mps" 12
PCIe Maximum Payload Size
.IP "sls" 12
PCIe Supported Link Speeds Vector
.IP "cls" 12
PCIe Current Link Speed
.IP "mlw" 12
PCIe Maximum Link Width
.IP "nlw" 12
PCIe Negotiated Link Width
.IP "pn" 12
PCIe Port Number
.IP "rsvd14" 12
Reserved
