.TH "libnvme" 9 "struct nvme_lbas_ns_element" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_lbas_ns_element \- 
.SH SYNOPSIS
struct nvme_lbas_ns_element {
.br
.BI "    __le32 neid;"
.br
.BI "    __le32 nlrd;"
.br
.BI "    __u8 ratype;"
.br
.BI "    __u8 rsvd8[7];"
.br
.BI "    struct nvme_lba_rd lba_rd[];"
.br
.BI "
};
.br

.SH Members
.IP "neid" 12
.IP "nlrd" 12
.IP "ratype" 12
.IP "rsvd8" 12
.IP "lba_rd" 12
