.TH "libnvme" 9 "enum nvme_fdp_event_realloc_flags" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_fdp_event_realloc_flags \- Media Reallocated Event Type Specific Flags
.SH SYNOPSIS
enum nvme_fdp_event_realloc_flags {
.br
.BI "    NVME_FDP_EVENT_REALLOC_F_LBAV"

};
.SH Constants
.IP "NVME_FDP_EVENT_REALLOC_F_LBAV" 12
LBA Valid
