.TH "nvme_fw_download_seq" 2 "nvme_fw_download_seq" "February 2020" "libnvme Manual"
.SH NAME
nvme_fw_download_seq \- 
.SH SYNOPSIS
.B "int" nvme_fw_download_seq
.BI "(int " fd ","
.BI "__u32 " size ","
.BI "__u32 " xfer ","
.BI "__u32 " offset ","
.BI "void *" buf ");"
.SH ARGUMENTS
.IP "fd" 12
-- undescribed --
.IP "size" 12
-- undescribed --
.IP "xfer" 12
-- undescribed --
.IP "offset" 12
-- undescribed --
.IP "buf" 12
