.TH "nvme_ctrl_is_persistent" 9 "nvme_ctrl_is_persistent" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_is_persistent \- Returns the value of the 'persistent' flag
.SH SYNOPSIS
.B "bool" nvme_ctrl_is_persistent
.BI "(nvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
Value of the 'persistent' flag of \fIc\fP
