.TH "nvme_ctrl_get_address" 9 "nvme_ctrl_get_address" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_get_address \- Address string of an nvme_ctrl_t
.SH SYNOPSIS
.B "const char *" nvme_ctrl_get_address
.BI "(nvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
nvme_ctrl_t object
.SH "RETURN"
NVMe-over-Fabrics address string of \fIc\fP or empty string
of no address is present.
