.TH "nvme_directive_send_id_endir" 9 "nvme_directive_send_id_endir" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_directive_send_id_endir \- Directive Send Enable Directive
.SH SYNOPSIS
.B "int" nvme_directive_send_id_endir
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "bool endir "  ","
.BI "enum nvme_directive_dtype dtype "  ","
.BI "struct nvme_id_directives *id "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace Identifier
.IP "endir" 12
Enable Directive
.IP "dtype" 12
Directive Type
.IP "id" 12
Pointer to structure nvme_id_directives
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
