.TH "libnvme" 9 "struct nvme_secondary_ctrl" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_secondary_ctrl \- Secondary Controller Entry
.SH SYNOPSIS
struct nvme_secondary_ctrl {
.br
.BI "    __le16 scid;"
.br
.BI "    __le16 pcid;"
.br
.BI "    __u8 scs;"
.br
.BI "    __u8 rsvd5[3];"
.br
.BI "    __le16 vfn;"
.br
.BI "    __le16 nvq;"
.br
.BI "    __le16 nvi;"
.br
.BI "    __u8 rsvd14[18];"
.br
.BI "
};
.br

.SH Members
.IP "scid" 12
Secondary Controller Identifier
.IP "pcid" 12
Primary Controller Identifier
.IP "scs" 12
Secondary Controller State
.IP "rsvd5" 12
Reserved
.IP "vfn" 12
Virtual Function Number
.IP "nvq" 12
Number of VQ Flexible Resources Assigned
.IP "nvi" 12
Number of VI Flexible Resources Assigned
.IP "rsvd14" 12
Reserved
