.TH "nvme_mi_admin_get_log_changed_alloc_ns_list" 9 "nvme_mi_admin_get_log_changed_alloc_ns_list" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_changed_alloc_ns_list \- Retrieve Changed Allocated Namespace List Log
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_changed_alloc_ns_list
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "bool rae "  ","
.BI "__u32 len "  ","
.BI "struct nvme_ns_list *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "rae" 12
Retain asynchronous events
.IP "len" 12
The allocated length of the log page
.IP "log" 12
User address to store the log page
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise
