.TH "libnvme" 9 "enum nvme_id_ctrl_sgls" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_sgls \- This field indicates if SGLs are supported for the NVM Command Set and the particular SGL types supported.
.SH SYNOPSIS
enum nvme_id_ctrl_sgls {
.br
.BI "    NVME_CTRL_SGLS_SUPPORTED"
, 
.br
.br
.BI "    NVME_CTRL_SGLS_KEYED"
, 
.br
.br
.BI "    NVME_CTRL_SGLS_BIT_BUCKET"
, 
.br
.br
.BI "    NVME_CTRL_SGLS_MPTR_BYTE_ALIGNED"
, 
.br
.br
.BI "    NVME_CTRL_SGLS_OVERSIZE"
, 
.br
.br
.BI "    NVME_CTRL_SGLS_MPTR_SGL"
, 
.br
.br
.BI "    NVME_CTRL_SGLS_OFFSET"
, 
.br
.br
.BI "    NVME_CTRL_SGLS_TPORT"

};
.SH Constants
.IP "NVME_CTRL_SGLS_SUPPORTED" 12
.IP "NVME_CTRL_SGLS_KEYED" 12
.IP "NVME_CTRL_SGLS_BIT_BUCKET" 12
.IP "NVME_CTRL_SGLS_MPTR_BYTE_ALIGNED" 12
.IP "NVME_CTRL_SGLS_OVERSIZE" 12
.IP "NVME_CTRL_SGLS_MPTR_SGL" 12
.IP "NVME_CTRL_SGLS_OFFSET" 12
.IP "NVME_CTRL_SGLS_TPORT" 12
