.TH "nvme_get_log_predictable_lat_event" 9 "nvme_get_log_predictable_lat_event" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_predictable_lat_event \- Retrieve Predictable Latency Event Aggregate Log Page
.SH SYNOPSIS
.B "int" nvme_get_log_predictable_lat_event
.BI "(int fd "  ","
.BI "bool rae "  ","
.BI "__u32 offset "  ","
.BI "__u32 len "  ","
.BI "void *log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "rae" 12
Retain asynchronous events
.IP "offset" 12
Offset into the predictable latency event
.IP "len" 12
Length of provided user buffer to hold the log data in bytes
.IP "log" 12
User address for log page data
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
