.TH "nvme_scan_ctrl_namespace_paths" 2 "nvme_scan_ctrl_namespace_paths" "February 2020" "libnvme Manual"
.SH NAME
nvme_scan_ctrl_namespace_paths \- 
.SH SYNOPSIS
.B "int" nvme_scan_ctrl_namespace_paths
.BI "(nvme_ctrl_t " c ","
.BI "struct dirent ***" namespaces ");"
.SH ARGUMENTS
.IP "c" 12
-- undescribed --
.IP "namespaces" 12
