.TH "nvme_subsystem_for_each_ctrl" 9 "nvme_subsystem_for_each_ctrl" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_for_each_ctrl \- Traverse controllers
.SH SYNOPSIS
.B "nvme_subsystem_for_each_ctrl
.BI "(s "  ","
.BI "c "  ");"
.SH ARGUMENTS
.IP "s" 12
\fInvme_subsystem_t\fP object
.IP "c" 12
Controller instance
