.TH "nvme_subsystem_for_each_ctrl" 9 "nvme_subsystem_for_each_ctrl" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_for_each_ctrl \- traverse controllers
.SH SYNOPSIS
.B "nvme_subsystem_for_each_ctrl
.BI "(s "  ","
.BI "c "  ");"
.SH ARGUMENTS
.IP "s" 12
nvme_subsystem_t object
.IP "c" 12
nvme_ctrl_t object
