.TH "nvme_ns_get_subsystem" 9 "nvme_ns_get_subsystem" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ns_get_subsystem \- &nvme_subsystem_t of a namespace
.SH SYNOPSIS
.B "nvme_subsystem_t" nvme_ns_get_subsystem
.BI "(nvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.SH "RETURN"
nvme_subsystem_t object of \fIn\fP
