.TH "nvme_subsystem_get_host" 9 "nvme_subsystem_get_host" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_get_host \- Returns nvme_host_t object
.SH SYNOPSIS
.B "nvme_host_t" nvme_subsystem_get_host
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
subsystem
.SH "RETURN"
\fInvme_host_t\fP object from \fIs\fP
