.TH "libnvme" 9 "enum nvme_fdp_config_fdpa" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_fdp_config_fdpa \- FDP Attributes
.SH SYNOPSIS
enum nvme_fdp_config_fdpa {
.br
.BI "    NVME_FDP_CONFIG_FDPA_RGIF_SHIFT"
, 
.br
.br
.BI "    NVME_FDP_CONFIG_FDPA_RGIF_MASK"
, 
.br
.br
.BI "    NVME_FDP_CONFIG_FDPA_FDPVWC_SHIFT"
, 
.br
.br
.BI "    NVME_FDP_CONFIG_FDPA_FDPVWC_MASK"
, 
.br
.br
.BI "    NVME_FDP_CONFIG_FDPA_VALID_SHIFT"
, 
.br
.br
.BI "    NVME_FDP_CONFIG_FDPA_VALID_MASK"

};
.SH Constants
.IP "NVME_FDP_CONFIG_FDPA_RGIF_SHIFT" 12
Reclaim Group Identifier Format Shift
.IP "NVME_FDP_CONFIG_FDPA_RGIF_MASK" 12
Reclaim Group Identifier Format Mask
.IP "NVME_FDP_CONFIG_FDPA_FDPVWC_SHIFT" 12
FDP Volatile Write Cache Shift
.IP "NVME_FDP_CONFIG_FDPA_FDPVWC_MASK" 12
FDP Volatile Write Cache Mask
.IP "NVME_FDP_CONFIG_FDPA_VALID_SHIFT" 12
FDP Configuration Valid Shift
.IP "NVME_FDP_CONFIG_FDPA_VALID_MASK" 12
FDP Configuration Valid Mask
