.TH "nvme_mi_admin_get_log_device_self_test" 9 "nvme_mi_admin_get_log_device_self_test" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_device_self_test \- Retrieve the device self test log
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_device_self_test
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "struct nvme_self_test_log *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "log" 12
Userspace address of the log payload
.SH "DESCRIPTION"
The log page indicates the status of an in progress self test and the
percent complete of that operation, and the results of the previous 20
self-test operations.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
