.TH "libnvme" 9 "struct nvme_mi_read_nvm_ss_info" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_mi_read_nvm_ss_info \- NVM Subsystem Information Data Structure
.SH SYNOPSIS
struct nvme_mi_read_nvm_ss_info {
.br
.BI "    __u8 nump;"
.br
.BI "    __u8 mjr;"
.br
.BI "    __u8 mnr;"
.br
.BI "    __u8 rsvd3[29];"
.br
.BI "
};
.br

.SH Members
.IP "nump" 12
Number of Ports
.IP "mjr" 12
NVMe-MI Major Version Number
.IP "mnr" 12
NVMe-MI Minor Version Number
.IP "rsvd3" 12
Reserved
