.TH "nvme_ns_head_get_sysfs_dir" 9 "nvme_ns_head_get_sysfs_dir" "July 2025" "libnvme API manual" LINUX
.SH NAME
nvme_ns_head_get_sysfs_dir \- sysfs dir of namespave head
.SH SYNOPSIS
.B "const char *" nvme_ns_head_get_sysfs_dir
.BI "(nvme_ns_head_t head "  ");"
.SH ARGUMENTS
.IP "head" 12
namespace head instance
.SH "RETURN"
sysfs directory name of \fIhead\fP
