.TH "libnvme" 9 "enum nvme_ae_info_error" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_ae_info_error \- Asynchronous Event Information - Error Status
.SH SYNOPSIS
enum nvme_ae_info_error {
.br
.BI "    NVME_AER_ERROR_INVALID_DB_REG"
, 
.br
.br
.BI "    NVME_AER_ERROR_INVALID_DB_VAL"
, 
.br
.br
.BI "    NVME_AER_ERROR_DIAG_FAILURE"
, 
.br
.br
.BI "    NVME_AER_ERROR_PERSISTENT_INTERNAL_ERROR"
, 
.br
.br
.BI "    NVME_AER_ERROR_TRANSIENT_INTERNAL_ERROR"
, 
.br
.br
.BI "    NVME_AER_ERROR_FW_IMAGE_LOAD_ERROR"

};
.SH Constants
.IP "NVME_AER_ERROR_INVALID_DB_REG" 12
Write to Invalid Doorbell Register
.IP "NVME_AER_ERROR_INVALID_DB_VAL" 12
Invalid Doorbell Write Value
.IP "NVME_AER_ERROR_DIAG_FAILURE" 12
Diagnostic Failure
.IP "NVME_AER_ERROR_PERSISTENT_INTERNAL_ERROR" 12
Persistent Internal Error
.IP "NVME_AER_ERROR_TRANSIENT_INTERNAL_ERROR" 12
Transient Internal Error
.IP "NVME_AER_ERROR_FW_IMAGE_LOAD_ERROR" 12
Firmware Image Load Error
