.TH "nvme_namespace_for_each_path_safe" 9 "nvme_namespace_for_each_path_safe" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_namespace_for_each_path_safe \- Traverse paths
.SH SYNOPSIS
.B "nvme_namespace_for_each_path_safe
.BI "(n "  ","
.BI "p "  ","
.BI "_p "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.IP "p" 12
\fInvme_path_t\fP object
.IP "_p" 12
A \fInvme_path_t_node\fP to use as temporary storage
