.TH "nvme_namespace_first_path" 9 "nvme_namespace_first_path" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_namespace_first_path \- Start path iterator
.SH SYNOPSIS
.B "nvme_path_t" nvme_namespace_first_path
.BI "(nvme_ns_t ns "  ");"
.SH ARGUMENTS
.IP "ns" 12
Namespace instance
.SH "RETURN"
First \fInvme_path_t\fP object of an \fIns\fP iterator
