.TH "nvme_path_get_ctrl" 9 "nvme_path_get_ctrl" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_path_get_ctrl \- Parent controller of an nvme_path_t object
.SH SYNOPSIS
.B "nvme_ctrl_t" nvme_path_get_ctrl
.BI "(nvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fInvme_path_t\fP object
.SH "RETURN"
Parent controller if present
