.TH "libnvme" 9 "enum nvme_io_mgmt_send_mo" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_io_mgmt_send_mo \- I/O Management Send - Management Operation
.SH SYNOPSIS
enum nvme_io_mgmt_send_mo {
.br
.BI "    NVME_IO_MGMT_SEND_RUH_UPDATE"

};
.SH Constants
.IP "NVME_IO_MGMT_SEND_RUH_UPDATE" 12
Reclaim Unit Handle Update
