.TH "nvme_default_host" 9 "nvme_default_host" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_default_host \- Initializes the default host
.SH SYNOPSIS
.B "nvme_host_t" nvme_default_host
.BI "(nvme_root_t r "  ");"
.SH ARGUMENTS
.IP "r" 12
\fInvme_root_t\fP object
.SH "DESCRIPTION"
Initializes the default host object based on the values in
/etc/nvme/hostnqn and /etc/nvme/hostid and attaches it to \fIr\fP.
.SH "RETURN"
\fInvme_host_t\fP object
