.TH "nvme_set_features_nopsc" 2 "nvme_set_features_nopsc" "February 2020" "libnvme Manual"
.SH NAME
nvme_set_features_nopsc \- 
.SH SYNOPSIS
.B "int" nvme_set_features_nopsc
.BI "(int " fd ","
.BI "bool " noppme ","
.BI "bool " save ","
.BI "__u32 *" result ");"
.SH ARGUMENTS
.IP "fd" 12
-- undescribed --
.IP "noppme" 12
-- undescribed --
.IP "save" 12
-- undescribed --
.IP "result" 12
-- undescribed --
