.TH "libnvme" 9 "struct nvme_id_ctrl_nvm" "May 2025" "API Manual" LINUX
.SH NAME
struct nvme_id_ctrl_nvm \- I/O Command Set Specific Identify Controller data structure
.SH SYNOPSIS
struct nvme_id_ctrl_nvm {
.br
.BI "    __u8 vsl;"
.br
.BI "    __u8 wzsl;"
.br
.BI "    __u8 wusl;"
.br
.BI "    __u8 dmrl;"
.br
.BI "    __le32 dmrsl;"
.br
.BI "    __le64 dmsl;"
.br
.BI "    __u8 kpiocap;"
.br
.BI "    __u8 wzdsl;"
.br
.BI "    __le16 aocs;"
.br
.BI "    __le32 ver;"
.br
.BI "    __u8 lbamqf;"
.br
.BI "    __u8 rsvd25[4071];"
.br
.BI "
};
.br

.SH Members
.IP "vsl" 12
Verify Size Limit
.IP "wzsl" 12
Write Zeroes Size Limit
.IP "wusl" 12
Write Uncorrectable Size Limit
.IP "dmrl" 12
Dataset Management Ranges Limit
.IP "dmrsl" 12
Dataset Management Range Size Limit
.IP "dmsl" 12
Dataset Management Size Limit
.IP "kpiocap" 12
Key Per I/O Capabilities
.IP "wzdsl" 12
Write Zeroes With Deallocate Size Limit
.IP "aocs" 12
Admin Optional Command Support
.IP "ver" 12
Version
.IP "lbamqf" 12
LBA Migration Queue Format
.IP "rsvd25" 12
Reserved
