.TH "libnvme" 9 "enum nvme_feat_perfc_attri" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_feat_perfc_attri \- performance characteristics attribute index
.SH SYNOPSIS
enum nvme_feat_perfc_attri {
.br
.BI "    NVME_FEAT_PERFC_ATTRI_STD"
, 
.br
.br
.BI "    NVME_FEAT_PERFC_ATTRI_ID_LIST"
, 
.br
.br
.BI "    NVME_FEAT_PERFC_ATTRI_VS_MIN"
, 
.br
.br
.BI "    NVME_FEAT_PERFC_ATTRI_VS_MAX"

};
.SH Constants
.IP "NVME_FEAT_PERFC_ATTRI_STD" 12
standard performance attribute
.IP "NVME_FEAT_PERFC_ATTRI_ID_LIST" 12
performance attribute identifier list
.IP "NVME_FEAT_PERFC_ATTRI_VS_MIN" 12
vendor specific performance attribute minimum index
.IP "NVME_FEAT_PERFC_ATTRI_VS_MAX" 12
vendor specific performance attribute maximum index
