.TH "nvme_mi_aem_aeei_get_aeeid" 9 "nvme_mi_aem_aeei_get_aeeid" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_aeei_get_aeeid \- return aeeid from aeei field
.SH SYNOPSIS
.B "__u8" nvme_mi_aem_aeei_get_aeeid
.BI "(__le16 aeei "  ");"
.SH ARGUMENTS
.IP "aeei" 12
aeei field from \fInvme_mi_aem_enable_item\fP
.SH "RETURN"
aeeid value
