.TH "nvme_get_features_resv_persist" 9 "nvme_get_features_resv_persist" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_features_resv_persist \- Get reservation persist feature
.SH SYNOPSIS
.B "int" nvme_get_features_resv_persist
.BI "(int fd "  ","
.BI "enum nvme_get_features_sel sel "  ","
.BI "__u32 *result "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "sel" 12
Select which type of attribute to return, see \fIenum nvme_get_features_sel\fP
.IP "result" 12
The command completion result from CQE dword0
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
