.TH "nvme_scan_ctrls" 9 "nvme_scan_ctrls" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_scan_ctrls \- Scan for controllers
.SH SYNOPSIS
.B "int" nvme_scan_ctrls
.BI "(struct dirent ***ctrls "  ");"
.SH ARGUMENTS
.IP "ctrls" 12
Pointer to array of dirents
.SH "RETURN"
number of entries in \fIctrls\fP
