.TH "nvme_ns_attach_ctrls" 9 "nvme_ns_attach_ctrls" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ns_attach_ctrls \- Attach namespace to controllers
.SH SYNOPSIS
.B "int" nvme_ns_attach_ctrls
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "struct nvme_ctrl_list *ctrlist "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace ID to attach
.IP "ctrlist" 12
Controller list to modify attachment state of nsid
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
