.TH "nvme_ctrl_set_persistent" 9 "nvme_ctrl_set_persistent" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_set_persistent \- Set the 'persistent' flag
.SH SYNOPSIS
.B "void" nvme_ctrl_set_persistent
.BI "(nvme_ctrl_t c "  ","
.BI "bool persistent "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "persistent" 12
value of the 'persistent' flag
.SH "DESCRIPTION"
Set the 'persistent' flag of \fIc\fP to \fIpersistent\fP
