.TH "nvme_subsystem_get_sysfs_dir" 9 "nvme_subsystem_get_sysfs_dir" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_get_sysfs_dir \- sysfs directory of an nvme_subsystem_t object
.SH SYNOPSIS
.B "const char *" nvme_subsystem_get_sysfs_dir
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
nvme_subsystem_t object
.SH "RETURN"
sysfs directory name of \fIs\fP
