.TH "nvme_ctrl_next_ns" 9 "nvme_ctrl_next_ns" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_next_ns \- Next namespace iterator
.SH SYNOPSIS
.B "nvme_ns_t" nvme_ctrl_next_ns
.BI "(nvme_ctrl_t c "  ","
.BI "nvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "c" 12
nvme_ctrl_t object
.IP "n" 12
previous nvme_ns_t iterator
.SH "RETURN"
next nvme_ns_t object of an \fIc\fP iterator
