.TH "libnvme" 9 "enum nvme_ns_attach_sel" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_ns_attach_sel \- Namespace Attachment - Select
.SH SYNOPSIS
enum nvme_ns_attach_sel {
.br
.BI "    NVME_NS_ATTACH_SEL_CTRL_ATTACH"
, 
.br
.br
.BI "    NVME_NS_ATTACH_SEL_CTRL_DEATTACH"

};
.SH Constants
.IP "NVME_NS_ATTACH_SEL_CTRL_ATTACH" 12
Namespace attach selection
.IP "NVME_NS_ATTACH_SEL_CTRL_DEATTACH" 12
Namespace detach selection
