.TH "nvme_for_each_subsystem" 9 "nvme_for_each_subsystem" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_for_each_subsystem \- Traverse subsystems
.SH SYNOPSIS
.B "nvme_for_each_subsystem
.BI "(h "  ","
.BI "s "  ");"
.SH ARGUMENTS
.IP "h" 12
\fInvme_host_t\fP object
.IP "s" 12
\fInvme_subsystem_t\fP object
