.TH "nvme_set_features_err_recovery" 9 "nvme_set_features_err_recovery" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_set_features_err_recovery \- Set error recovery feature
.SH SYNOPSIS
.B "int" nvme_set_features_err_recovery
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "__u16 tler "  ","
.BI "bool dulbe "  ","
.BI "bool save "  ","
.BI "__u32 *result "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace ID
.IP "tler" 12
Time-limited error recovery value
.IP "dulbe" 12
Deallocated or Unwritten Logical Block Error Enable
.IP "save" 12
Save value across power states
.IP "result" 12
The command completion result from CQE dword0
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
