.TH "nvme_init_id_ns" 9 "nvme_init_id_ns" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_init_id_ns \- Initialize an Identify Namepsace structure for creation.
.SH SYNOPSIS
.B "void" nvme_init_id_ns
.BI "(struct nvme_id_ns *ns "  ","
.BI "__u64 nsze "  ","
.BI "__u64 ncap "  ","
.BI "__u8 flbas "  ","
.BI "__u8 dps "  ","
.BI "__u8 nmic "  ","
.BI "__u32 anagrpid "  ","
.BI "__u16 nvmsetid "  ");"
.SH ARGUMENTS
.IP "ns" 12
Address of the Identify Namespace structure to initialize
.IP "nsze" 12
Namespace size
.IP "ncap" 12
namespace capacity
.IP "flbas" 12
formatted logical block size settings
.IP "dps" 12
Data protection settings
.IP "nmic" 12
Namespace sharing capabilities
.IP "anagrpid" 12
ANA group identifier
.IP "nvmsetid" 12
NVM Set identifer
.SH "DESCRIPTION"
This is intended to be used with a namespace management "create", see
\fBnvme_ns_mgmt_create\fP.
