.TH "nvme_is_64bit_reg" 9 "nvme_is_64bit_reg" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_is_64bit_reg \- Checks if offset of the controller register is a know 64bit value.
.SH SYNOPSIS
.B "bool" nvme_is_64bit_reg
.BI "(__u32 offset "  ");"
.SH ARGUMENTS
.IP "offset" 12
Offset of controller register field in bytes
.SH "DESCRIPTION"
This function does not care about transport so that the offset is not going
to be checked inside of this function for the unsupported fields in a
specific transport. For example, BPMBL(Boot Partition Memory Buffer
Location) register is not supported by fabrics, but it can be checked here.
.SH "RETURN"
true if given offset is 64bit register, otherwise it returns false.
