.TH "libnvme" 9 "enum nvme_virt_mgmt_act" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_virt_mgmt_act \- Virtualization Management - Action
.SH SYNOPSIS
enum nvme_virt_mgmt_act {
.br
.BI "    NVME_VIRT_MGMT_ACT_PRIM_CTRL_FLEX_ALLOC"
, 
.br
.br
.BI "    NVME_VIRT_MGMT_ACT_OFFLINE_SEC_CTRL"
, 
.br
.br
.BI "    NVME_VIRT_MGMT_ACT_ASSIGN_SEC_CTRL"
, 
.br
.br
.BI "    NVME_VIRT_MGMT_ACT_ONLINE_SEC_CTRL"

};
.SH Constants
.IP "NVME_VIRT_MGMT_ACT_PRIM_CTRL_FLEX_ALLOC" 12
Primary Controller Flexible
Allocation
.IP "NVME_VIRT_MGMT_ACT_OFFLINE_SEC_CTRL" 12
Secondary Controller Offline
.IP "NVME_VIRT_MGMT_ACT_ASSIGN_SEC_CTRL" 12
Secondary Controller Assign
.IP "NVME_VIRT_MGMT_ACT_ONLINE_SEC_CTRL" 12
Secondary Controller Online
