.TH "nvme_resv_acquire" 9 "nvme_resv_acquire" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_resv_acquire \- Send an nvme reservation acquire
.SH SYNOPSIS
.B "int" nvme_resv_acquire
.BI "(struct nvme_resv_acquire_args *args "  ");"
.SH ARGUMENTS
.IP "args" 12
\fIstruct nvme_resv_acquire\fP argument structure
.SH "DESCRIPTION"
The Reservation Acquire command acquires a reservation on a namespace,
preempt a reservation held on a namespace, and abort a reservation held on a
namespace.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
