.TH "nvme_ctrl_for_each_ns_safe" 2 "nvme_ctrl_for_each_ns_safe" "February 2020" "libnvme Manual"
.SH NAME
nvme_ctrl_for_each_ns_safe \- 
.SH SYNOPSIS
.B "nvme_ctrl_for_each_ns_safe
.BI "(" c ","
.BI "" n ","
.BI "" _n ");"
.SH ARGUMENTS
.IP "c" 12
-- undescribed --
.IP "n" 12
-- undescribed --
.IP "_n" 12
-- undescribed --
