.TH "libnvme" 9 "enum nvme_identify_cns" "February 2022" "API Manual" LINUX
.SH NAME
enum nvme_identify_cns \- 
.SH SYNOPSIS
enum nvme_identify_cns {
.br
.BI "    NVME_IDENTIFY_CNS_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CTRL"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_ACTIVE_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_DESC_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NVMSET_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_CTRL"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_NS_ACTIVE_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_INDEPENDENT_ID_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_USER_DATA_FORMAT"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_NS_USER_DATA_FORMAT"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ALLOCATED_NS_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ALLOCATED_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_PRIMARY_CTRL_CAP"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_SECONDARY_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_GRANULARITY"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_UUID_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_DOMAIN_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ENDURANCE_GROUP_ID"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSS_ALLOCATED_NS_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_COMMAND_SET_STRUCTURE"

};
.SH Constants
.IP "NVME_IDENTIFY_CNS_NS" 12
.IP "NVME_IDENTIFY_CNS_CTRL" 12
.IP "NVME_IDENTIFY_CNS_NS_ACTIVE_LIST" 12
.IP "NVME_IDENTIFY_CNS_NS_DESC_LIST" 12
.IP "NVME_IDENTIFY_CNS_NVMSET_LIST" 12
.IP "NVME_IDENTIFY_CNS_CSI_NS" 12
.IP "NVME_IDENTIFY_CNS_CSI_CTRL" 12
.IP "NVME_IDENTIFY_CNS_CSI_NS_ACTIVE_LIST" 12
.IP "NVME_IDENTIFY_CNS_CSI_INDEPENDENT_ID_NS" 12
.IP "NVME_IDENTIFY_CNS_NS_USER_DATA_FORMAT" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_CSI_NS_USER_DATA_FORMAT" 12
-- undescribed --
.IP "NVME_IDENTIFY_CNS_ALLOCATED_NS_LIST" 12
.IP "NVME_IDENTIFY_CNS_ALLOCATED_NS" 12
.IP "NVME_IDENTIFY_CNS_NS_CTRL_LIST" 12
.IP "NVME_IDENTIFY_CNS_CTRL_LIST" 12
.IP "NVME_IDENTIFY_CNS_PRIMARY_CTRL_CAP" 12
.IP "NVME_IDENTIFY_CNS_SECONDARY_CTRL_LIST" 12
.IP "NVME_IDENTIFY_CNS_NS_GRANULARITY" 12
.IP "NVME_IDENTIFY_CNS_UUID_LIST" 12
.IP "NVME_IDENTIFY_CNS_DOMAIN_LIST" 12
.IP "NVME_IDENTIFY_CNS_ENDURANCE_GROUP_ID" 12
.IP "NVME_IDENTIFY_CNS_CSS_ALLOCATED_NS_LIST" 12
.IP "NVME_IDENTIFY_CNS_COMMAND_SET_STRUCTURE" 12
Base Specification 2.0a section 5.17.2.21
