.TH "nvme_mi_admin_ns_attach" 9 "nvme_mi_admin_ns_attach" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_ns_attach \- Attach or detach namespace to controller(s)
.SH SYNOPSIS
.B "int" nvme_mi_admin_ns_attach
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "struct nvme_ns_attach_args *args "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to send command to
.IP "args" 12
Namespace Attach command arguments
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
