.TH "libnvme" 9 "struct nvme_copy_range" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_copy_range \- Copy - Source Range Entries Descriptor Format
.SH SYNOPSIS
struct nvme_copy_range {
.br
.BI "    __u8 rsvd0[8];"
.br
.BI "    __le64 slba;"
.br
.BI "    __le16 nlb;"
.br
.BI "    __u8 rsvd18[6];"
.br
.BI "    __le32 eilbrt;"
.br
.BI "    __le16 elbatm;"
.br
.BI "    __le16 elbat;"
.br
.BI "
};
.br

.SH Members
.IP "rsvd0" 12
Reserved
.IP "slba" 12
Starting LBA
.IP "nlb" 12
Number of Logical Blocks
.IP "rsvd18" 12
Reserved
.IP "eilbrt" 12
Expected Initial Logical Block Reference Tag /
Expected Logical Block Storage Tag
.IP "elbatm" 12
Expected Logical Block Application Tag Mask
.IP "elbat" 12
Expected Logical Block Application Tag
