.TH "nvme_get_log_fdp_stats" 9 "nvme_get_log_fdp_stats" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_fdp_stats \- Get Flexible Data Placement statistics
.SH SYNOPSIS
.B "int" nvme_get_log_fdp_stats
.BI "(int fd "  ","
.BI "__u16 egid "  ","
.BI "__u32 offset "  ","
.BI "__u32 len "  ","
.BI "void *log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "egid" 12
Endurance group identifier
.IP "offset" 12
Offset into log page
.IP "len" 12
Length (in bytes) of provided user buffer to hold the log data
.IP "log" 12
Log page data buffer
