.TH "nvme_ctrl_get_ana_state" 9 "nvme_ctrl_get_ana_state" "April 2022" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_get_ana_state \- ANA state of a controller path
.SH SYNOPSIS
.B "const char *" nvme_ctrl_get_ana_state
.BI "(nvme_ctrl_t c "  ","
.BI "__u32 nsid "  ");"
.SH ARGUMENTS
.IP "c" 12
Constroller instance
.IP "nsid" 12
Namespace ID to evaluate
.SH "RETURN"
ANA state of the namespace \fInsid\fP on controller \fIc\fP.
