.TH "nvme_ctrl_get_dhchap_key" 9 "nvme_ctrl_get_dhchap_key" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_get_dhchap_key \- Return controller key
.SH SYNOPSIS
.B "const char *" nvme_ctrl_get_dhchap_key
.BI "(nvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller for which the key should be set
.SH "RETURN"
DH-HMAC-CHAP controller key or NULL if not set
