.TH "nvme_mi_admin_get_log_discovery" 9 "nvme_mi_admin_get_log_discovery" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_discovery \- Retrieve Discovery log page
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_discovery
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "bool rae "  ","
.BI "__u32 offset "  ","
.BI "__u32 len "  ","
.BI "void *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "rae" 12
Retain asynchronous events
.IP "offset" 12
Offset of this log to retrieve
.IP "len" 12
The allocated size for this portion of the log
.IP "log" 12
User address to store the discovery log
.SH "DESCRIPTION"
Supported only by fabrics discovery controllers, returning discovery
records.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
