.TH "nvme_mi_aem_open" 9 "nvme_mi_aem_open" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_open \- Prepare an existing endpoint to receive AEMs
.SH SYNOPSIS
.B "int" nvme_mi_aem_open
.BI "(nvme_mi_ep_t ep "  ");"
.SH ARGUMENTS
.IP "ep" 12
Endpoint to configure for AEMs
.SH "RETURN"
0 if success, -1 otherwise
