.TH "nvme_identify_nvmset_list" 9 "nvme_identify_nvmset_list" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_identify_nvmset_list \- Retrieves NVM Set List
.SH SYNOPSIS
.B "int" nvme_identify_nvmset_list
.BI "(int fd "  ","
.BI "__u16 nvmsetid "  ","
.BI "struct nvme_id_nvmset_list *nvmset "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nvmsetid" 12
NVM Set Identifier
.IP "nvmset" 12
User space destination address to transfer the data
.SH "DESCRIPTION"
Retrieves an NVM Set List, \fIstruct nvme_id_nvmset_list\fP. The data structure
is an ordered list by NVM Set Identifier, starting with the first NVM Set
Identifier supported by the NVM subsystem that is equal to or greater than
the NVM Set Identifier.

See \fIstruct nvme_id_nvmset_list\fP for the definition of the returned structure.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
