.TH "nvme_subsystem_for_each_ns_safe" 2 "nvme_subsystem_for_each_ns_safe" "February 2020" "libnvme Manual"
.SH NAME
nvme_subsystem_for_each_ns_safe \- 
.SH SYNOPSIS
.B "nvme_subsystem_for_each_ns_safe
.BI "(" s ","
.BI "" n ","
.BI "" _n ");"
.SH ARGUMENTS
.IP "s" 12
-- undescribed --
.IP "n" 12
-- undescribed --
.IP "_n" 12
-- undescribed --
