.TH "nvme_ns_get_generic_name" 9 "nvme_ns_get_generic_name" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ns_get_generic_name \- Returns name of generic namespace chardev.
.SH SYNOPSIS
.B "const char *" nvme_ns_get_generic_name
.BI "(nvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.SH "RETURN"
Name of generic namespace chardev
