.TH "nvme_subsystem_first_ctrl" 9 "nvme_subsystem_first_ctrl" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_first_ctrl \- First ctrl iterator
.SH SYNOPSIS
.B "nvme_ctrl_t" nvme_subsystem_first_ctrl
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
\fInvme_subsystem_t\fP object
.SH "RETURN"
First controller of an \fIs\fP iterator
