.TH "libnvme" 9 "enum nvme_zns_report_options" "February 2022" "API Manual" LINUX
.SH NAME
enum nvme_zns_report_options \- 
.SH SYNOPSIS
enum nvme_zns_report_options {
.br
.BI "    NVME_ZNS_ZRAS_REPORT_ALL"
, 
.br
.br
.BI "    NVME_ZNS_ZRAS_REPORT_EMPTY"
, 
.br
.br
.BI "    NVME_ZNS_ZRAS_REPORT_IMPL_OPENED"
, 
.br
.br
.BI "    NVME_ZNS_ZRAS_REPORT_EXPL_OPENED"
, 
.br
.br
.BI "    NVME_ZNS_ZRAS_REPORT_CLOSED"
, 
.br
.br
.BI "    NVME_ZNS_ZRAS_REPORT_FULL"
, 
.br
.br
.BI "    NVME_ZNS_ZRAS_REPORT_READ_ONLY"
, 
.br
.br
.BI "    NVME_ZNS_ZRAS_REPORT_OFFLINE"

};
.SH Constants
.IP "NVME_ZNS_ZRAS_REPORT_ALL" 12
.IP "NVME_ZNS_ZRAS_REPORT_EMPTY" 12
.IP "NVME_ZNS_ZRAS_REPORT_IMPL_OPENED" 12
.IP "NVME_ZNS_ZRAS_REPORT_EXPL_OPENED" 12
.IP "NVME_ZNS_ZRAS_REPORT_CLOSED" 12
.IP "NVME_ZNS_ZRAS_REPORT_FULL" 12
.IP "NVME_ZNS_ZRAS_REPORT_READ_ONLY" 12
.IP "NVME_ZNS_ZRAS_REPORT_OFFLINE" 12
