.TH "libnvme" 9 "struct nvme_lm_controller_state_data" "May 2025" "API Manual" LINUX
.SH NAME
struct nvme_lm_controller_state_data \- Controller State data structure contains data on the controller's state.
.SH SYNOPSIS
struct nvme_lm_controller_state_data {
.br
.BI "    struct nvme_lm_controller_state_data_header hdr;"
.br
.BI "    struct nvme_lm_nvme_controller_state_data   data;"
.br
.BI "
};
.br

.SH Members
.IP "hdr" 12
Header
.IP "data" 12
Data
