.TH "nvme_ns_get_serial" 9 "nvme_ns_get_serial" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_ns_get_serial \- Serial number of an nvme_ns_t object
.SH SYNOPSIS
.B "const char *" nvme_ns_get_serial
.BI "(nvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "n" 12
nvme_ns_t object
.SH "RETURN"
Serial number string of \fIn\fP
