.TH "nvme_copy" 9 "nvme_copy" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_copy \- Copy command
.SH SYNOPSIS
.B "int" nvme_copy
.BI "(struct nvme_copy_args *args "  ");"
.SH ARGUMENTS
.IP "args" 12
\fIstruct nvme_copy_args\fP argument structure
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
