.TH "libnvme" 9 "enum nvme_mi_elem" "February 2022" "API Manual" LINUX
.SH NAME
enum nvme_mi_elem \- 
.SH SYNOPSIS
enum nvme_mi_elem {
.br
.BI "    NVME_MI_ELEM_EED"
, 
.br
.br
.BI "    NVME_MI_ELEM_USCE"
, 
.br
.br
.BI "    NVME_MI_ELEM_ECED"
, 
.br
.br
.BI "    NVME_MI_ELEM_LED"
, 
.br
.br
.BI "    NVME_MI_ELEM_SMBMED"
, 
.br
.br
.BI "    NVME_MI_ELEM_PCIESED"
, 
.br
.br
.BI "    NVME_MI_ELEM_NVMED"

};
.SH Constants
.IP "NVME_MI_ELEM_EED" 12
.IP "NVME_MI_ELEM_USCE" 12
.IP "NVME_MI_ELEM_ECED" 12
.IP "NVME_MI_ELEM_LED" 12
.IP "NVME_MI_ELEM_SMBMED" 12
.IP "NVME_MI_ELEM_PCIESED" 12
.IP "NVME_MI_ELEM_NVMED" 12
