.TH "nvme_get_ana_log_len" 9 "nvme_get_ana_log_len" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_ana_log_len \- Retrieve size of the current ANA log
.SH SYNOPSIS
.B "int" nvme_get_ana_log_len
.BI "(int fd "  ","
.BI "size_t *analen "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "analen" 12
Pointer to where the length will be set on success
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
