.TH "libnvme" 9 "enum nvme_id_ctrl_nvm_lbamqf" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_nvm_lbamqf \- LBA Migration Queue Format
.SH SYNOPSIS
enum nvme_id_ctrl_nvm_lbamqf {
.br
.BI "    NVME_ID_CTRL_NVM_LBAMQF_TYPE_0"
, 
.br
.br
.BI "    NVME_ID_CTRL_NVM_LBAMQF_VENDOR_MIN"
, 
.br
.br
.BI "    NVME_ID_CTRL_NVM_LBAMQF_VENDOR_MAX"

};
.SH Constants
.IP "NVME_ID_CTRL_NVM_LBAMQF_TYPE_0" 12
.IP "NVME_ID_CTRL_NVM_LBAMQF_VENDOR_MIN" 12
.IP "NVME_ID_CTRL_NVM_LBAMQF_VENDOR_MAX" 12
