.TH "libnvme" 9 "struct nvme_reachability_associations_log" "May 2025" "API Manual" LINUX
.SH NAME
struct nvme_reachability_associations_log \- Reachability Associations Log
.SH SYNOPSIS
struct nvme_reachability_associations_log {
.br
.BI "    __le64 chngc;"
.br
.BI "    __le16 nrad;"
.br
.BI "    __u8 rsvd10[6];"
.br
.BI "    struct nvme_reachability_association_desc       rad[];"
.br
.BI "
};
.br

.SH Members
.IP "chngc" 12
Change Count
.IP "nrad" 12
Number of Reachability Association Descriptors
.IP "rsvd10" 12
Reserved
.IP "rad" 12
Reachability Association Descriptor List
