.TH "libnvme" 9 "enum nvme_log_ana_lsp" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_log_ana_lsp \- Asymmetric Namespace Access - Return Groups Only
.SH SYNOPSIS
enum nvme_log_ana_lsp {
.br
.BI "    NVME_LOG_ANA_LSP_RGO_NAMESPACES"
, 
.br
.br
.BI "    NVME_LOG_ANA_LSP_RGO_GROUPS_ONLY"

};
.SH Constants
.IP "NVME_LOG_ANA_LSP_RGO_NAMESPACES" 12
.IP "NVME_LOG_ANA_LSP_RGO_GROUPS_ONLY" 12
