.TH "nvme_ctrl_for_each_ns_safe" 9 "nvme_ctrl_for_each_ns_safe" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_for_each_ns_safe \- Traverse namespaces
.SH SYNOPSIS
.B "nvme_ctrl_for_each_ns_safe
.BI "(c "  ","
.BI "n "  ","
.BI "_n "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "n" 12
\fInvme_ns_t\fP object
.IP "_n" 12
A \fInvme_ns_t_node\fP to use as temporary storage
