.TH "nvme_get_new_host_telemetry" 9 "nvme_get_new_host_telemetry" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_new_host_telemetry \- Get new host telemetry log
.SH SYNOPSIS
.B "int" nvme_get_new_host_telemetry
.BI "(int fd "  ","
.BI "struct nvme_telemetry_log **log "  ","
.BI "enum nvme_telemetry_da da "  ","
.BI "size_t *size "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "log" 12
On success, set to the value of the allocated and retrieved log.
.IP "da" 12
Log page data area, valid values: \fIenum nvme_telemetry_da\fP
.IP "size" 12
Ptr to the telemetry log size, so it can be returned
.SH "DESCRIPTION"
The total size allocated can be calculated as:
(nvme_telemetry_log da size  + 1) * NVME_LOG_TELEM_BLOCK_SIZE.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
