.TH "libnvme" 9 "enum nvme_feat_nswpcfg_state" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_feat_nswpcfg_state \- Write Protection - Write Protection State
.SH SYNOPSIS
enum nvme_feat_nswpcfg_state {
.br
.BI "    NVME_FEAT_NS_NO_WRITE_PROTECT"
, 
.br
.br
.BI "    NVME_FEAT_NS_WRITE_PROTECT"
, 
.br
.br
.BI "    NVME_FEAT_NS_WRITE_PROTECT_PWR_CYCLE"
, 
.br
.br
.BI "    NVME_FEAT_NS_WRITE_PROTECT_PERMANENT"

};
.SH Constants
.IP "NVME_FEAT_NS_NO_WRITE_PROTECT" 12
No Write Protect
.IP "NVME_FEAT_NS_WRITE_PROTECT" 12
Write Protect
.IP "NVME_FEAT_NS_WRITE_PROTECT_PWR_CYCLE" 12
Write Protect Until Power Cycle
.IP "NVME_FEAT_NS_WRITE_PROTECT_PERMANENT" 12
Permanent Write Protect
