.TH "nvme_paths_filter" 9 "nvme_paths_filter" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_paths_filter \- Filter for paths
.SH SYNOPSIS
.B "int" nvme_paths_filter
.BI "(const struct dirent *d "  ");"
.SH ARGUMENTS
.IP "d" 12
dirent to check
.SH "RETURN"
1 if \fId\fP matches, 0 otherwise
