.TH "nvme_set_features_lba_sts_interval" 9 "nvme_set_features_lba_sts_interval" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_set_features_lba_sts_interval \- Set LBA status information feature
.SH SYNOPSIS
.B "int" nvme_set_features_lba_sts_interval
.BI "(int fd "  ","
.BI "__u16 lsiri "  ","
.BI "__u16 lsipi "  ","
.BI "bool save "  ","
.BI "__u32 *result "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "lsiri" 12
LBA Status Information Report Interval
.IP "lsipi" 12
LBA Status Information Poll Interval
.IP "save" 12
Save value across power states
.IP "result" 12
The command completion result from CQE dword0
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
