.TH "libnvme" 9 "enum nvme_virt_mgmt_rt" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_virt_mgmt_rt \- Virtualization Management - Resource Type
.SH SYNOPSIS
enum nvme_virt_mgmt_rt {
.br
.BI "    NVME_VIRT_MGMT_RT_VQ_RESOURCE"
, 
.br
.br
.BI "    NVME_VIRT_MGMT_RT_VI_RESOURCE"

};
.SH Constants
.IP "NVME_VIRT_MGMT_RT_VQ_RESOURCE" 12
VQ Resources
.IP "NVME_VIRT_MGMT_RT_VI_RESOURCE" 12
VI Resources
