.TH "nvme_scan_namespace" 9 "nvme_scan_namespace" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_scan_namespace \- scan namespace based on sysfs name
.SH SYNOPSIS
.B "nvme_ns_t" nvme_scan_namespace
.BI "(const char *name "  ");"
.SH ARGUMENTS
.IP "name" 12
sysfs name of the namespace to scan
.SH "RETURN"
nvme_ns_t object or NULL if not found.
