.TH "libnvme" 9 "enum nvme_lbart" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_lbart \- LBA Range Type - Data Structure Entry
.SH SYNOPSIS
enum nvme_lbart {
.br
.BI "    NVME_LBART_TYPE_GP"
, 
.br
.br
.BI "    NVME_LBART_TYPE_FS"
, 
.br
.br
.BI "    NVME_LBART_TYPE_RAID"
, 
.br
.br
.BI "    NVME_LBART_TYPE_CACHE"
, 
.br
.br
.BI "    NVME_LBART_TYPE_SWAP"
, 
.br
.br
.BI "    NVME_LBART_ATTRIB_TEMP"
, 
.br
.br
.BI "    NVME_LBART_ATTRIB_HIDE"

};
.SH Constants
.IP "NVME_LBART_TYPE_GP" 12
General Purpose
.IP "NVME_LBART_TYPE_FS" 12
Filesystem
.IP "NVME_LBART_TYPE_RAID" 12
RAID
.IP "NVME_LBART_TYPE_CACHE" 12
Cache
.IP "NVME_LBART_TYPE_SWAP" 12
Page / swap file
.IP "NVME_LBART_ATTRIB_TEMP" 12
Temp
.IP "NVME_LBART_ATTRIB_HIDE" 12
Hidden
