.TH "nvme_ns_read" 9 "nvme_ns_read" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ns_read \- Read from a namespace
.SH SYNOPSIS
.B "int" nvme_ns_read
.BI "(nvme_ns_t n "  ","
.BI "void *buf "  ","
.BI "off_t offset "  ","
.BI "size_t count "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.IP "buf" 12
Buffer into which the data will be transferred
.IP "offset" 12
LBA offset of \fIn\fP
.IP "count" 12
Number of sectors in \fIbuf\fP
.SH "RETURN"
Number of sectors read or -1 on error.
