.TH "nvme_get_log_cmd_effects" 9 "nvme_get_log_cmd_effects" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_cmd_effects \- Retrieve nvme command effects log
.SH SYNOPSIS
.B "int" nvme_get_log_cmd_effects
.BI "(int fd "  ","
.BI "enum nvme_csi csi "  ","
.BI "struct nvme_cmd_effects_log *effects_log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "csi" 12
Command Set Identifier
.IP "effects_log" 12
User address to store the effects log
.SH "DESCRIPTION"
This log page describes the commands that the controller supports and the
effects of those commands on the state of the NVM subsystem.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
