.TH "libnvme" 9 "struct nvme_mi_vpd_telem" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_telem \- 
.SH SYNOPSIS
struct nvme_mi_vpd_telem {
.br
.BI "    __u8 type;"
.br
.BI "    __u8 rev;"
.br
.BI "    __u8 len;"
.br
.BI "    __u8 data[0];"
.br
.BI "
};
.br

.SH Members
.IP "type" 12
.IP "rev" 12
.IP "len" 12
.IP "data" 12
