.TH "nvme_ns_mgmt_create" 9 "nvme_ns_mgmt_create" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ns_mgmt_create \- Create a non attached namespace
.SH SYNOPSIS
.B "int" nvme_ns_mgmt_create
.BI "(int fd "  ","
.BI "struct nvme_id_ns *ns "  ","
.BI "__u32 *nsid "  ","
.BI "__u32 timeout "  ","
.BI "__u8 csi "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "ns" 12
Namespace identification that defines ns creation parameters
.IP "nsid" 12
On success, set to the namespace id that was created
.IP "timeout" 12
Override the default timeout to this value in milliseconds;
set to 0 to use the system default.
.IP "csi" 12
Command Set Identifier
.SH "DESCRIPTION"
On successful creation, the namespace exists in the subsystem, but is not
attached to any controller. Use the \fBnvme_ns_attach_ctrls\fP to assign the
namespace to one or more controllers.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
