.TH "nvme_get_log_page" 2 "nvme_get_log_page" "February 2020" "libnvme Manual"
.SH NAME
nvme_get_log_page \- 
.SH SYNOPSIS
.B "int" nvme_get_log_page
.BI "(int " fd ","
.BI "__u32 " nsid ","
.BI "__u8 " log_id ","
.BI "bool " rae ","
.BI "__u32 " data_len ","
.BI "void *" data ");"
.SH ARGUMENTS
.IP "fd" 12
-- undescribed --
.IP "nsid" 12
-- undescribed --
.IP "log_id" 12
-- undescribed --
.IP "rae" 12
-- undescribed --
.IP "data_len" 12
-- undescribed --
.IP "data" 12
.SH "DESCRIPTION"
Calls \fB__nvme_get_log_page\fP with a default 4k transfer length.
