.TH "libnvme" 9 "enum nvme_directive_dtype" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_directive_dtype \- Directive Types
.SH SYNOPSIS
enum nvme_directive_dtype {
.br
.BI "    NVME_DIRECTIVE_DTYPE_IDENTIFY"
, 
.br
.br
.BI "    NVME_DIRECTIVE_DTYPE_STREAMS"

};
.SH Constants
.IP "NVME_DIRECTIVE_DTYPE_IDENTIFY" 12
Identify directive type
.IP "NVME_DIRECTIVE_DTYPE_STREAMS" 12
Streams directive type
