.TH "libnvme" 9 "struct nvme_mi_nvm_ss_health_status" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_mi_nvm_ss_health_status \- 
.SH SYNOPSIS
struct nvme_mi_nvm_ss_health_status {
.br
.BI "    __u8 nss;"
.br
.BI "    __u8 sw;"
.br
.BI "    __u8 ctemp;"
.br
.BI "    __u8 pdlu;"
.br
.BI "    __le16 ccs;"
.br
.BI "    __u8 rsvd8[2];"
.br
.BI "
};
.br

.SH Members
.IP "nss" 12
.IP "sw" 12
.IP "ctemp" 12
.IP "pdlu" 12
.IP "ccs" 12
.IP "rsvd8" 12
