.TH "nvme_get_log_telemetry_host" 9 "nvme_get_log_telemetry_host" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_telemetry_host \- Get Telemetry Host-Initiated log page
.SH SYNOPSIS
.B "int" nvme_get_log_telemetry_host
.BI "(int fd "  ","
.BI "__u64 offset "  ","
.BI "__u32 len "  ","
.BI "void *log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "offset" 12
Offset into the telemetry data
.IP "len" 12
Length of provided user buffer to hold the log data in bytes
.IP "log" 12
User address for log page data
.SH "DESCRIPTION"
Retrieves the Telemetry Host-Initiated log page at the requested offset
using the previously existing capture.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
