.TH "nvme_resv_register" 9 "nvme_resv_register" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_resv_register \- Send an nvme reservation register
.SH SYNOPSIS
.B "int" nvme_resv_register
.BI "(struct nvme_resv_register_args *args "  ");"
.SH ARGUMENTS
.IP "args" 12
\fIstruct nvme_resv_register_args\fP argument structure
.SH "DESCRIPTION"
The Reservation Register command registers, unregisters, or replaces a
reservation key.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
