.TH "nvme_io_mgmt_recv" 9 "nvme_io_mgmt_recv" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_io_mgmt_recv \- I/O Management Receive command
.SH SYNOPSIS
.B "int" nvme_io_mgmt_recv
.BI "(struct nvme_io_mgmt_recv_args *args "  ");"
.SH ARGUMENTS
.IP "args" 12
\fIstruct nvme_io_mgmt_recv_args\fP argument structure
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
