.TH "nvme_mi_aem_aesi_get_aesid" 9 "nvme_mi_aem_aesi_get_aesid" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_aesi_get_aesid \- return aesid from aesi field
.SH SYNOPSIS
.B "__u8" nvme_mi_aem_aesi_get_aesid
.BI "(__le16 aesi "  ");"
.SH ARGUMENTS
.IP "aesi" 12
aesi field from \fInvme_mi_aem_supported_item\fP
.SH "RETURN"
aesid value
