.TH "nvme_identify_secondary_ctrl_list" 9 "nvme_identify_secondary_ctrl_list" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_identify_secondary_ctrl_list \- Retrieves secondary controller list
.SH SYNOPSIS
.B "int" nvme_identify_secondary_ctrl_list
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "__u16 cntid "  ","
.BI "struct nvme_secondary_ctrl_list *sc_list "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace identifier
.IP "cntid" 12
Return controllers starting at this identifier
.IP "sc_list" 12
User space destination address to transfer the data
.SH "DESCRIPTION"
A Secondary Controller List is returned to the host for up to 127 secondary
controllers associated with the primary controller processing this command.
The list contains entries for controller identifiers greater than or equal
to the value specified in the Controller Identifier (cntid).

See \fIstruct nvme_secondary_ctrls_list\fP for a definition of the returned
structure.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
