.TH "nvme_get_log_page_padded" 9 "nvme_get_log_page_padded" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_page_padded \- 
.SH SYNOPSIS
.B "int" nvme_get_log_page_padded
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "__u8 log_id "  ","
.BI "bool rae "  ","
.BI "__u32 data_len "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace Identifier, if applicable.
.IP "log_id" 12
Log Identifier, see \fIenum nvme_cmd_get_log_lid\fP.
.IP "rae" 12
Retain asynchronous events
.IP "data_len" 12
Total length of the log to transfer.
.IP "data" 12
User address of at least \fIdata_len\fP to store the log.
.SH "DESCRIPTION"
Calls \fBnvme_get_log_page\fP with a default 4k transfer length, as that is
guarnateed by the protocol to be a safe transfer size.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
