.TH "libnvme" 9 "enum nvme_lm_ctrl_data_queue_fid" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_lm_ctrl_data_queue_fid \- Controller Data Queue - Set Feature
.SH SYNOPSIS
enum nvme_lm_ctrl_data_queue_fid {
.br
.BI "    NVME_LM_CTRL_DATA_QUEUE_ETPT_MASK"
, 
.br
.br
.BI "    NVME_LM_CTRL_DATA_QUEUE_ETPT_SHIFT"

};
.SH Constants
.IP "NVME_LM_CTRL_DATA_QUEUE_ETPT_MASK" 12
Mask to set Enable Tail Pointer Trigger (ETPT)
.IP "NVME_LM_CTRL_DATA_QUEUE_ETPT_SHIFT" 12
Shift to set ETPT
