.TH "libnvme" 9 "enum nvme_dst_stc" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_dst_stc \- Action taken by the Device Self-test command
.SH SYNOPSIS
enum nvme_dst_stc {
.br
.BI "    NVME_DST_STC_SHORT"
, 
.br
.br
.BI "    NVME_DST_STC_LONG"
, 
.br
.br
.BI "    NVME_DST_STC_VS"
, 
.br
.br
.BI "    NVME_DST_STC_ABORT"

};
.SH Constants
.IP "NVME_DST_STC_SHORT" 12
Start a short device self-test operation
.IP "NVME_DST_STC_LONG" 12
Start an extended device self-test operation
.IP "NVME_DST_STC_VS" 12
Start a vendor specific device self-test operation
.IP "NVME_DST_STC_ABORT" 12
Abort device self-test operation
