.TH "nvme_mi_close" 9 "nvme_mi_close" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_close \- Close an endpoint connection and release resources, including controller objects.
.SH SYNOPSIS
.B "void" nvme_mi_close
.BI "(nvme_mi_ep_t ep "  ");"
.SH ARGUMENTS
.IP "ep" 12
Endpoint object to close
