.TH "libnvme" 9 "struct nvme_mgmt_addr_list_log" "May 2025" "API Manual" LINUX
.SH NAME
struct nvme_mgmt_addr_list_log \- Management Address List Log
.SH SYNOPSIS
struct nvme_mgmt_addr_list_log {
.br
.BI "    struct nvme_mgmt_addr_desc      mad[8];"
.br
.BI "
};
.br

.SH Members
.IP "mad" 12
Management Address Descriptor
