.TH "nvme_mi_admin_get_log_lba_status" 9 "nvme_mi_admin_get_log_lba_status" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_lba_status \- Retrieve LBA Status
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_lba_status
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "bool rae "  ","
.BI "__u64 offset "  ","
.BI "__u32 len "  ","
.BI "void *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "rae" 12
Retain asynchronous events
.IP "offset" 12
Offset to the start of the log page
.IP "len" 12
The allocated length of the log page
.IP "log" 12
User address to store the log page
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
