.TH "libnvme" 9 "enum nvme_feat_tmpthresh_thsel" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_feat_tmpthresh_thsel \- Temperature Threshold - Threshold Type Select
.SH SYNOPSIS
enum nvme_feat_tmpthresh_thsel {
.br
.BI "    NVME_FEATURE_TEMPTHRESH_THSEL_OVER"
, 
.br
.br
.BI "    NVME_FEATURE_TEMPTHRESH_THSEL_UNDER"

};
.SH Constants
.IP "NVME_FEATURE_TEMPTHRESH_THSEL_OVER" 12
Over temperature threshold select
.IP "NVME_FEATURE_TEMPTHRESH_THSEL_UNDER" 12
Under temperature threshold select
