.TH "libnvme" 9 "enum nvme_mi_css" "April 2022" "API Manual" LINUX
.SH NAME
enum nvme_mi_css \- 
.SH SYNOPSIS
enum nvme_mi_css {
.br
.BI "    NVME_MI_CCS_RDY"
, 
.br
.br
.BI "    NVME_MI_CSS_CFS"
, 
.br
.br
.BI "    NVME_MI_CSS_SHST"
, 
.br
.br
.BI "    NVME_MI_CSS_NSSRO"
, 
.br
.br
.BI "    NVME_MI_CSS_CECO"
, 
.br
.br
.BI "    NVME_MI_CSS_NAC"
, 
.br
.br
.BI "    NVME_MI_CSS_FA"
, 
.br
.br
.BI "    NVME_MI_CSS_CSTS"
, 
.br
.br
.BI "    NVME_MI_CSS_CTEMP"
, 
.br
.br
.BI "    NVME_MI_CSS_PDLU"
, 
.br
.br
.BI "    NVME_MI_CSS_SPARE"
, 
.br
.br
.BI "    NVME_MI_CSS_CCWARN"

};
.SH Constants
.IP "NVME_MI_CCS_RDY" 12
Ready
.IP "NVME_MI_CSS_CFS" 12
Controller Fatal Status
.IP "NVME_MI_CSS_SHST" 12
Shutdown Status
.IP "NVME_MI_CSS_NSSRO" 12
NVM Subsystem Reset Occurred
.IP "NVME_MI_CSS_CECO" 12
Controller Enable Change Occurred
.IP "NVME_MI_CSS_NAC" 12
Namespace Attribute Changed
.IP "NVME_MI_CSS_FA" 12
Firmware Activated
.IP "NVME_MI_CSS_CSTS" 12
Controller Status Change
.IP "NVME_MI_CSS_CTEMP" 12
Composite Temperature Change
.IP "NVME_MI_CSS_PDLU" 12
Percentage Used
.IP "NVME_MI_CSS_SPARE" 12
Available Spare
.IP "NVME_MI_CSS_CCWARN" 12
Critical Warning
