.TH "libnvme" 9 "enum nvme_features_async_event_config_flags" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_features_async_event_config_flags \- Asynchronous Event Configuration configuration flags
.SH SYNOPSIS
enum nvme_features_async_event_config_flags {
.br
.BI "    NVME_FEATURE_AENCFG_SMART_CRIT_SPARE"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_SMART_CRIT_TEMPERATURE"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_SMART_CRIT_DEGRADED"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_SMART_CRIT_READ_ONLY"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_SMART_CRIT_VOLATILE_BACKUP"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_SMART_CRIT_READ_ONLY_PMR"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_NAMESPACE_ATTRIBUTES"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_FIRMWARE_ACTIVATION"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_TELEMETRY_LOG"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_ANA_CHANGE"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_PL_EVENT"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_LBA_STATUS"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_EG_EVENT"
, 
.br
.br
.BI "    NVME_FEATURE_AENCFG_NOTICE_DISCOVERY_CHANGE"

};
.SH Constants
.IP "NVME_FEATURE_AENCFG_SMART_CRIT_SPARE" 12
.IP "NVME_FEATURE_AENCFG_SMART_CRIT_TEMPERATURE" 12
.IP "NVME_FEATURE_AENCFG_SMART_CRIT_DEGRADED" 12
.IP "NVME_FEATURE_AENCFG_SMART_CRIT_READ_ONLY" 12
.IP "NVME_FEATURE_AENCFG_SMART_CRIT_VOLATILE_BACKUP" 12
.IP "NVME_FEATURE_AENCFG_SMART_CRIT_READ_ONLY_PMR" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_NAMESPACE_ATTRIBUTES" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_FIRMWARE_ACTIVATION" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_TELEMETRY_LOG" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_ANA_CHANGE" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_PL_EVENT" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_LBA_STATUS" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_EG_EVENT" 12
.IP "NVME_FEATURE_AENCFG_NOTICE_DISCOVERY_CHANGE" 12
