.TH "nvme_path_get_ns" 9 "nvme_path_get_ns" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_path_get_ns \- Parent namespace of an nvme_path_t object
.SH SYNOPSIS
.B "nvme_ns_t" nvme_path_get_ns
.BI "(nvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fInvme_path_t\fP object
.SH "RETURN"
Parent namespace if present
