.TH "libnvme" 9 "enum nvme_copy_range_sopt" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_copy_range_sopt \- NVMe Copy Range Source Options
.SH SYNOPSIS
enum nvme_copy_range_sopt {
.br
.BI "    NVME_COPY_SOPT_FCO"

};
.SH Constants
.IP "NVME_COPY_SOPT_FCO" 12
NVMe Copy Source Option Fast Copy Only
