.TH "nvme_nvm_identify_ctrl" 9 "nvme_nvm_identify_ctrl" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_nvm_identify_ctrl \- Identify controller data
.SH SYNOPSIS
.B "int" nvme_nvm_identify_ctrl
.BI "(int fd "  ","
.BI "struct nvme_id_ctrl_nvm *id "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "id" 12
User space destination address to transfer the data
.SH "DESCRIPTION"
Return an identify controller data structure to the host of
processing controller.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
