.TH "nvme_mi_aem_aeei_get_aee" 9 "nvme_mi_aem_aeei_get_aee" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_aeei_get_aee \- return aee from aeei field
.SH SYNOPSIS
.B "bool" nvme_mi_aem_aeei_get_aee
.BI "(__le16 aeei "  ");"
.SH ARGUMENTS
.IP "aeei" 12
aeei field from \fInvme_mi_aem_enable_item\fP
.SH "RETURN"
aee value
