.TH "nvme_mi_admin_get_log_telemetry_ctrl" 9 "nvme_mi_admin_get_log_telemetry_ctrl" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_telemetry_ctrl \- Get Telemetry Controller-Initiated log page
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_telemetry_ctrl
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "bool rae "  ","
.BI "__u64 offset "  ","
.BI "__u32 len "  ","
.BI "void *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "rae" 12
Retain asynchronous events
.IP "offset" 12
Offset into the telemetry data
.IP "len" 12
Length of provided user buffer to hold the log data in bytes
.IP "log" 12
User address for log page data
.SH "DESCRIPTION"
Retrieves the Telemetry Controller-Initiated log page at the requested offset
using the previously existing capture.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
