.TH "libnvme" 9 "struct nvme_fw_commit_event" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_fw_commit_event \- 
.SH SYNOPSIS
struct nvme_fw_commit_event {
.br
.BI "    __le64 old_fw_rev;"
.br
.BI "    __le64 new_fw_rev;"
.br
.BI "    __u8 fw_commit_action;"
.br
.BI "    __u8 fw_slot;"
.br
.BI "    __u8 sct_fw;"
.br
.BI "    __u8 sc_fw;"
.br
.BI "    __le16 vndr_assign_fw_commit_rc;"
.br
.BI "
};
.br

.SH Members
.IP "old_fw_rev" 12
.IP "new_fw_rev" 12
.IP "fw_commit_action" 12
.IP "fw_slot" 12
.IP "sct_fw" 12
.IP "sc_fw" 12
.IP "vndr_assign_fw_commit_rc" 12
