.TH "nvme_ctrl_for_each_path_safe" 9 "nvme_ctrl_for_each_path_safe" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_for_each_path_safe \- Traverse paths
.SH SYNOPSIS
.B "nvme_ctrl_for_each_path_safe
.BI "(c "  ","
.BI "p "  ","
.BI "_p "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "p" 12
\fInvme_path_t\fP object
.IP "_p" 12
A \fInvme_path_t_node\fP to use as temporary storage
