.TH "nvme_get_directive_receive_length" 9 "nvme_get_directive_receive_length" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_directive_receive_length \- Get directive receive length
.SH SYNOPSIS
.B "int" nvme_get_directive_receive_length
.BI "(enum nvme_directive_dtype dtype "  ","
.BI "enum nvme_directive_receive_doper doper "  ","
.BI "__u32 *len "  ");"
.SH ARGUMENTS
.IP "dtype" 12
Directive type, see \fIenum nvme_directive_dtype\fP
.IP "doper" 12
Directive receive operation, see \fIenum nvme_directive_receive_doper\fP
.IP "len" 12
On success, set to this directives payload length in bytes.
.SH "RETURN"
0 on success, -1 with errno set to EINVAL if the function did not
recognize \fIdtype\fP or \fIdoper\fP.
