.TH "libnvme" 9 "struct nvme_fdp_ruh_desc" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_fdp_ruh_desc \- Reclaim Unit Handle Descriptor
.SH SYNOPSIS
struct nvme_fdp_ruh_desc {
.br
.BI "    __u8 ruht;"
.br
.BI "    __u8 rsvd1[3];"
.br
.BI "
};
.br

.SH Members
.IP "ruht" 12
Reclaim Unit Handle Type
.IP "rsvd1" 12
Reserved
