.TH "nvme_mi_admin_get_log_endurance_group" 9 "nvme_mi_admin_get_log_endurance_group" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_endurance_group \- Get Endurance Group log
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_endurance_group
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "__u16 endgid "  ","
.BI "struct nvme_endurance_group_log *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "endgid" 12
Starting group identifier to return in the list
.IP "log" 12
User address to store the endurance log
.SH "DESCRIPTION"
This log page indicates if an Endurance Group Event has occurred for a
particular Endurance Group. If an Endurance Group Event has occurred, the
details of the particular event are included in the Endurance Group
Information log page for that Endurance Group. An asynchronous event is
generated when an entry for an Endurance Group is newly added to this log
page.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
