.TH "nvme_subsystem_next_ns" 9 "nvme_subsystem_next_ns" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_next_ns \- Next namespace iterator
.SH SYNOPSIS
.B "nvme_ns_t" nvme_subsystem_next_ns
.BI "(nvme_subsystem_t s "  ","
.BI "nvme_ns_t n "  ");"
.SH ARGUMENTS
.IP "s" 12
\fInvme_subsystem_t\fP object
.IP "n" 12
Previous \fInvme_ns_t\fP iterator
.SH "RETURN"
Next \fInvme_ns_t\fP object of an \fIs\fP iterator
