.TH "libnvme" 9 "enum nvme_sanitize_sanact" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_sanitize_sanact \- Sanitize Action
.SH SYNOPSIS
enum nvme_sanitize_sanact {
.br
.BI "    NVME_SANITIZE_SANACT_EXIT_FAILURE"
, 
.br
.br
.BI "    NVME_SANITIZE_SANACT_START_BLOCK_ERASE"
, 
.br
.br
.BI "    NVME_SANITIZE_SANACT_START_OVERWRITE"
, 
.br
.br
.BI "    NVME_SANITIZE_SANACT_START_CRYPTO_ERASE"

};
.SH Constants
.IP "NVME_SANITIZE_SANACT_EXIT_FAILURE" 12
Exit Failure Mode.
.IP "NVME_SANITIZE_SANACT_START_BLOCK_ERASE" 12
Start a Block Erase sanitize operation.
.IP "NVME_SANITIZE_SANACT_START_OVERWRITE" 12
Start an Overwrite sanitize operation.
.IP "NVME_SANITIZE_SANACT_START_CRYPTO_ERASE" 12
Start a Crypto Erase sanitize operation.
