.TH "nvme_setup_id_ns" 2 "nvme_setup_id_ns" "February 2020" "libnvme Manual"
.SH NAME
nvme_setup_id_ns \- 
.SH SYNOPSIS
.B "void" nvme_setup_id_ns
.BI "(struct nvme_id_ns *" ns ","
.BI "__u64 " nsze ","
.BI "__u64 " ncap ","
.BI "__u8 " flbas ","
.BI "__u8 " dps ","
.BI "__u8 " nmic ","
.BI "__u32 " anagrpid ","
.BI "__u16 " nvmsetid ");"
.SH ARGUMENTS
.IP "ns" 12
-- undescribed --
.IP "nsze" 12
-- undescribed --
.IP "ncap" 12
-- undescribed --
.IP "flbas" 12
-- undescribed --
.IP "dps" 12
-- undescribed --
.IP "nmic" 12
-- undescribed --
.IP "anagrpid" 12
-- undescribed --
.IP "nvmsetid" 12
-- undescribed --
