.TH "nvme_subsystem_first_ns" 9 "nvme_subsystem_first_ns" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_first_ns \- Start namespace iterator
.SH SYNOPSIS
.B "nvme_ns_t" nvme_subsystem_first_ns
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
\fInvme_subsystem_t\fP object
.SH "RETURN"
First \fInvme_ns_t\fP object of an \fIs\fP iterator
