.TH "libnvme" 9 "enum nvme_host_behavior_support" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_host_behavior_support \- Enable Advanced Command
.SH SYNOPSIS
enum nvme_host_behavior_support {
.br
.BI "    NVME_ENABLE_ACRE"

};
.SH Constants
.IP "NVME_ENABLE_ACRE" 12
Enable Advanced Command Retry Enable
