.TH "nvme_get_log_predictable_lat_nvmset" 9 "nvme_get_log_predictable_lat_nvmset" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_predictable_lat_nvmset \- Predictable Latency Per NVM Set
.SH SYNOPSIS
.B "int" nvme_get_log_predictable_lat_nvmset
.BI "(int fd "  ","
.BI "__u16 nvmsetid "  ","
.BI "struct nvme_nvmset_predictable_lat_log *log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nvmsetid" 12
NVM set id
.IP "log" 12
User address to store the predictable latency log
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
