.TH "libnvme" 9 "enum nvme_nvmeset_pl_status" "April 2022" "API Manual" LINUX
.SH NAME
enum nvme_nvmeset_pl_status \- 
.SH SYNOPSIS
enum nvme_nvmeset_pl_status {
.br
.BI "    NVME_NVMSET_PL_STATUS_DISABLED"
, 
.br
.br
.BI "    NVME_NVMSET_PL_STATUS_DTWIN"
, 
.br
.br
.BI "    NVME_NVMSET_PL_STATUS_NDWIN"

};
.SH Constants
.IP "NVME_NVMSET_PL_STATUS_DISABLED" 12
.IP "NVME_NVMSET_PL_STATUS_DTWIN" 12
.IP "NVME_NVMSET_PL_STATUS_NDWIN" 12
