.TH "nvme_ns_attach" 9 "nvme_ns_attach" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ns_attach \- Attach or detach namespace to controller(s)
.SH SYNOPSIS
.B "int" nvme_ns_attach
.BI "(struct nvme_ns_attach_args *args "  ");"
.SH ARGUMENTS
.IP "args" 12
\fIstruct nvme_ns_attach_args\fP Argument structure
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
