.TH "libnvme" 9 "enum nvme_cmd_get_log_lid" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_cmd_get_log_lid \- Get Log Page -Log Page Identifiers
.SH SYNOPSIS
enum nvme_cmd_get_log_lid {
.br
.BI "    NVME_LOG_LID_SUPPORTED_LOG_PAGES"
, 
.br
.br
.BI "    NVME_LOG_LID_ERROR"
, 
.br
.br
.BI "    NVME_LOG_LID_SMART"
, 
.br
.br
.BI "    NVME_LOG_LID_FW_SLOT"
, 
.br
.br
.BI "    NVME_LOG_LID_CHANGED_NS"
, 
.br
.br
.BI "    NVME_LOG_LID_CMD_EFFECTS"
, 
.br
.br
.BI "    NVME_LOG_LID_DEVICE_SELF_TEST"
, 
.br
.br
.BI "    NVME_LOG_LID_TELEMETRY_HOST"
, 
.br
.br
.BI "    NVME_LOG_LID_TELEMETRY_CTRL"
, 
.br
.br
.BI "    NVME_LOG_LID_ENDURANCE_GROUP"
, 
.br
.br
.BI "    NVME_LOG_LID_PREDICTABLE_LAT_NVMSET"
, 
.br
.br
.BI "    NVME_LOG_LID_PREDICTABLE_LAT_AGG"
, 
.br
.br
.BI "    NVME_LOG_LID_ANA"
, 
.br
.br
.BI "    NVME_LOG_LID_PERSISTENT_EVENT"
, 
.br
.br
.BI "    NVME_LOG_LID_LBA_STATUS"
, 
.br
.br
.BI "    NVME_LOG_LID_ENDURANCE_GRP_EVT"
, 
.br
.br
.BI "    NVME_LOG_LID_MEDIA_UNIT_STATUS"
, 
.br
.br
.BI "    NVME_LOG_LID_SUPPORTED_CAP_CONFIG_LIST"
, 
.br
.br
.BI "    NVME_LOG_LID_FID_SUPPORTED_EFFECTS"
, 
.br
.br
.BI "    NVME_LOG_LID_MI_CMD_SUPPORTED_EFFECTS"
, 
.br
.br
.BI "    NVME_LOG_LID_BOOT_PARTITION"
, 
.br
.br
.BI "    NVME_LOG_LID_FDP_CONFIGS"
, 
.br
.br
.BI "    NVME_LOG_LID_FDP_RUH_USAGE"
, 
.br
.br
.BI "    NVME_LOG_LID_FDP_STATS"
, 
.br
.br
.BI "    NVME_LOG_LID_FDP_EVENTS"
, 
.br
.br
.BI "    NVME_LOG_LID_DISCOVER"
, 
.br
.br
.BI "    NVME_LOG_LID_RESERVATION"
, 
.br
.br
.BI "    NVME_LOG_LID_SANITIZE"
, 
.br
.br
.BI "    NVME_LOG_LID_ZNS_CHANGED_ZONES"

};
.SH Constants
.IP "NVME_LOG_LID_SUPPORTED_LOG_PAGES" 12
Supported Log Pages
.IP "NVME_LOG_LID_ERROR" 12
Error Information
.IP "NVME_LOG_LID_SMART" 12
SMART / Health Information
.IP "NVME_LOG_LID_FW_SLOT" 12
Firmware Slot Information
.IP "NVME_LOG_LID_CHANGED_NS" 12
Changed Namespace List
.IP "NVME_LOG_LID_CMD_EFFECTS" 12
Commands Supported and Effects
.IP "NVME_LOG_LID_DEVICE_SELF_TEST" 12
Device Self-test
.IP "NVME_LOG_LID_TELEMETRY_HOST" 12
Telemetry Host-Initiated
.IP "NVME_LOG_LID_TELEMETRY_CTRL" 12
Telemetry Controller-Initiated
.IP "NVME_LOG_LID_ENDURANCE_GROUP" 12
Endurance Group Information
.IP "NVME_LOG_LID_PREDICTABLE_LAT_NVMSET" 12
Predictable Latency Per NVM Set
.IP "NVME_LOG_LID_PREDICTABLE_LAT_AGG" 12
Predictable Latency Event Aggregate
.IP "NVME_LOG_LID_ANA" 12
Asymmetric Namespace Access
.IP "NVME_LOG_LID_PERSISTENT_EVENT" 12
Persistent Event Log
.IP "NVME_LOG_LID_LBA_STATUS" 12
LBA Status Information
.IP "NVME_LOG_LID_ENDURANCE_GRP_EVT" 12
Endurance Group Event Aggregate
.IP "NVME_LOG_LID_MEDIA_UNIT_STATUS" 12
Media Unit Status
.IP "NVME_LOG_LID_SUPPORTED_CAP_CONFIG_LIST" 12
Supported Capacity Configuration Lis
.IP "NVME_LOG_LID_FID_SUPPORTED_EFFECTS" 12
Feature Identifiers Supported and Effects
.IP "NVME_LOG_LID_MI_CMD_SUPPORTED_EFFECTS" 12
NVMe-MI Commands Supported and Effects
.IP "NVME_LOG_LID_BOOT_PARTITION" 12
Boot Partition
.IP "NVME_LOG_LID_FDP_CONFIGS" 12
FDP Configurations
.IP "NVME_LOG_LID_FDP_RUH_USAGE" 12
Reclaim Unit Handle Usage
.IP "NVME_LOG_LID_FDP_STATS" 12
FDP Statistics
.IP "NVME_LOG_LID_FDP_EVENTS" 12
FDP Events
.IP "NVME_LOG_LID_DISCOVER" 12
Discovery
.IP "NVME_LOG_LID_RESERVATION" 12
Reservation Notification
.IP "NVME_LOG_LID_SANITIZE" 12
Sanitize Status
.IP "NVME_LOG_LID_ZNS_CHANGED_ZONES" 12
Changed Zone List
