.TH "nvme_mi_aem_aesi_set_aee" 9 "nvme_mi_aem_aesi_set_aee" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_aesi_set_aee \- set aee in the aesi field
.SH SYNOPSIS
.B "void" nvme_mi_aem_aesi_set_aee
.BI "(struct nvme_mi_aem_supported_item *item "  ","
.BI "bool enabled "  ");"
.SH ARGUMENTS
.IP "item" 12
Pointer to \fInvme_mi_aem_supported_item\fP to update the aesi field
.IP "enabled" 12
aee value to use
