.TH "libnvme" 9 "enum nvme_id_ctrl_apsta" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_apsta \- Flags indicating the attributes of the autonomous power state transition feature.
.SH SYNOPSIS
enum nvme_id_ctrl_apsta {
.br
.BI "    NVME_CTRL_APSTA_APST"

};
.SH Constants
.IP "NVME_CTRL_APSTA_APST" 12
If set, then the controller supports autonomous power
state transitions.
