.TH "nvme_ctrl_set_dhchap_host_key" 9 "nvme_ctrl_set_dhchap_host_key" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_set_dhchap_host_key \- Set host key
.SH SYNOPSIS
.B "void" nvme_ctrl_set_dhchap_host_key
.BI "(nvme_ctrl_t c "  ","
.BI "const char *key "  ");"
.SH ARGUMENTS
.IP "c" 12
Host for which the key should be set
.IP "key" 12
DH-HMAC-CHAP Key to set or NULL to clear existing key
