.TH "nvme_scan_ctrl_namespaces" 9 "nvme_scan_ctrl_namespaces" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_scan_ctrl_namespaces \- Scan for namespaces in a controller
.SH SYNOPSIS
.B "int" nvme_scan_ctrl_namespaces
.BI "(nvme_ctrl_t c "  ","
.BI "struct dirent ***ns "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller to scan
.IP "ns" 12
Pointer to array of dirents
.SH "RETURN"
number of entries in \fIns\fP
