.TH "nvme_for_each_host_safe" 9 "nvme_for_each_host_safe" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_for_each_host_safe \- Traverse host list
.SH SYNOPSIS
.B "nvme_for_each_host_safe
.BI "(r "  ","
.BI "h "  ","
.BI "_h "  ");"
.SH ARGUMENTS
.IP "r" 12
\fInvme_root_t\fP object
.IP "h" 12
\fInvme_host_t\fP object
.IP "_h" 12
Temporary \fInvme_host_t\fP object
