.TH "libnvme" 9 "struct nvme_set_feature_event" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_set_feature_event \- Set Feature Event Data
.SH SYNOPSIS
struct nvme_set_feature_event {
.br
.BI "    __le32 layout;"
.br
.BI "    __le32 cdw_mem[0];"
.br
.BI "
};
.br

.SH Members
.IP "layout" 12
Set Feature Event Layout
.IP "cdw_mem" 12
Command Dwords Memory buffer
