.TH "nvme_setup_ctrl_list" 2 "nvme_setup_ctrl_list" "February 2020" "libnvme Manual"
.SH NAME
nvme_setup_ctrl_list \- 
.SH SYNOPSIS
.B "void" nvme_setup_ctrl_list
.BI "(struct nvme_ctrl_list *" cntlist ","
.BI "__u16 " num_ctrls ","
.BI "__u16 *" ctrlist ");"
.SH ARGUMENTS
.IP "cntlist" 12
-- undescribed --
.IP "num_ctrls" 12
-- undescribed --
.IP "ctrlist" 12
-- undescribed --
