.TH "libnvme" 9 "enum nvme_io_mgmt_recv_mo" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_io_mgmt_recv_mo \- I/O Management Receive - Management Operation
.SH SYNOPSIS
enum nvme_io_mgmt_recv_mo {
.br
.BI "    NVME_IO_MGMT_RECV_RUH_STATUS"

};
.SH Constants
.IP "NVME_IO_MGMT_RECV_RUH_STATUS" 12
Reclaim Unit Handle Status
