.TH "nvme_get_log_page" 9 "nvme_get_log_page" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_page \- Get log page data
.SH SYNOPSIS
.B "int" nvme_get_log_page
.BI "(int fd "  ","
.BI "__u32 xfer_len "  ","
.BI "struct nvme_get_log_args *args "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "xfer_len" 12
Max log transfer size per request to split the total.
.IP "args" 12
\fIstruct nvme_get_log_args\fP argument structure
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
