.TH "nvme_ctrl_for_each_path_safe" 2 "nvme_ctrl_for_each_path_safe" "February 2020" "libnvme Manual"
.SH NAME
nvme_ctrl_for_each_path_safe \- 
.SH SYNOPSIS
.B "nvme_ctrl_for_each_path_safe
.BI "(" c ","
.BI "" p ","
.BI "" _p ");"
.SH ARGUMENTS
.IP "c" 12
-- undescribed --
.IP "p" 12
-- undescribed --
.IP "_p" 12
-- undescribed --
