.TH "libnvme" 9 "enum nvme_fdp_ruha" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_fdp_ruha \- Reclaim Unit Handle Attributes
.SH SYNOPSIS
enum nvme_fdp_ruha {
.br
.BI "    NVME_FDP_RUHA_HOST_SHIFT"
, 
.br
.br
.BI "    NVME_FDP_RUHA_HOST_MASK"
, 
.br
.br
.BI "    NVME_FDP_RUHA_CTRL_SHIFT"
, 
.br
.br
.BI "    NVME_FDP_RUHA_CTRL_MASK"

};
.SH Constants
.IP "NVME_FDP_RUHA_HOST_SHIFT" 12
Host Specified Reclaim Unit Handle Shift
.IP "NVME_FDP_RUHA_HOST_MASK" 12
Host Specified Reclaim Unit Handle Mask
.IP "NVME_FDP_RUHA_CTRL_SHIFT" 12
Controller Specified Reclaim Unit Handle Shift
.IP "NVME_FDP_RUHA_CTRL_MASK" 12
Controller Specified Reclaim Unit Handle Mask
