.TH "nvme_scan_ctrl_namespace_paths" 9 "nvme_scan_ctrl_namespace_paths" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_scan_ctrl_namespace_paths \- Scan for namespace paths in a controller
.SH SYNOPSIS
.B "int" nvme_scan_ctrl_namespace_paths
.BI "(nvme_ctrl_t c "  ","
.BI "struct dirent ***paths "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller to scan
.IP "paths" 12
Pointer to array of dirents
.SH "RETURN"
number of entries in \fIpaths\fP
