.TH "libnvme" 9 "struct nvme_zns_id_ctrl" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_zns_id_ctrl \- I/O Command Set Specific Identify Controller Data Structure for the Zoned Namespace Command Set
.SH SYNOPSIS
struct nvme_zns_id_ctrl {
.br
.BI "    __u8 zasl;"
.br
.BI "    __u8 rsvd1[4095];"
.br
.BI "
};
.br

.SH Members
.IP "zasl" 12
Zone Append Size Limit
.IP "rsvd1" 12
Reserved
