.TH "libnvme" 9 "struct nvme_mi_vpd_mra" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_mra \- 
.SH SYNOPSIS
struct nvme_mi_vpd_mra {
.br
.BI "    __u8 nmravn;"
.br
.BI "    __u8 ff;"
.br
.BI "    __u8 rsvd7[6];"
.br
.BI "    __u8 i18vpwr;"
.br
.BI "    __u8 m18vpwr;"
.br
.BI "    __u8 i33vpwr;"
.br
.BI "    __u8 m33vpwr;"
.br
.BI "    __u8 rsvd17;"
.br
.BI "    __u8 m33vapsr;"
.br
.BI "    __u8 i5vapsr;"
.br
.BI "    __u8 m5vapsr;"
.br
.BI "    __u8 i12vapsr;"
.br
.BI "    __u8 m12vapsr;"
.br
.BI "    __u8 mtl;"
.br
.BI "    __u8 tnvmcap[16];"
.br
.BI "    __u8 rsvd37[27];"
.br
.BI "
};
.br

.SH Members
.IP "nmravn" 12
.IP "ff" 12
.IP "rsvd7" 12
.IP "i18vpwr" 12
.IP "m18vpwr" 12
.IP "i33vpwr" 12
.IP "m33vpwr" 12
.IP "rsvd17" 12
.IP "m33vapsr" 12
.IP "i5vapsr" 12
.IP "m5vapsr" 12
.IP "i12vapsr" 12
.IP "m12vapsr" 12
.IP "mtl" 12
.IP "tnvmcap" 12
.IP "rsvd37" 12
