.TH "nvme_first_subsystem" 9 "nvme_first_subsystem" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_first_subsystem \- Start subsystem iterator
.SH SYNOPSIS
.B "nvme_subsystem_t" nvme_first_subsystem
.BI "(nvme_host_t h "  ");"
.SH ARGUMENTS
.IP "h" 12
\fInvme_host_t\fP object
.SH "RETURN"
first \fInvme_subsystem_t\fP object in an iterator
