.TH "libnvme" 9 "struct nvme_mi_vpd_tra" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_tra \- Vital Product Data Topology MultiRecord
.SH SYNOPSIS
struct nvme_mi_vpd_tra {
.br
.BI "    __u8 vn;"
.br
.BI "    __u8 rsvd6;"
.br
.BI "    __u8 ec;"
.br
.BI "    struct nvme_mi_vpd_telem elems[0];"
.br
.BI "
};
.br

.SH Members
.IP "vn" 12
Version Number
.IP "rsvd6" 12
Reserved
.IP "ec" 12
Element Count
.IP "elems" 12
Element Descriptor
