.TH "nvme_for_each_subsystem_safe" 2 "nvme_for_each_subsystem_safe" "February 2020" "libnvme Manual"
.SH NAME
nvme_for_each_subsystem_safe \- 
.SH SYNOPSIS
.B "nvme_for_each_subsystem_safe
.BI "(" r ","
.BI "" s ","
.BI "" _s ");"
.SH ARGUMENTS
.IP "r" 12
-- undescribed --
.IP "s" 12
-- undescribed --
.IP "_s" 12
-- undescribed --
