.TH "libnvme" 9 "struct nvme_persistent_event_entry" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_persistent_event_entry \- 
.SH SYNOPSIS
struct nvme_persistent_event_entry {
.br
.BI "    __u8 etype;"
.br
.BI "    __u8 etype_rev;"
.br
.BI "    __u8 ehl;"
.br
.BI "    __u8 rsvd3;"
.br
.BI "    __le16 cntlid;"
.br
.BI "    __le64 ets;"
.br
.BI "    __u8 rsvd14[6];"
.br
.BI "    __le16 vsil;"
.br
.BI "    __le16 el;"
.br
.BI "
};
.br

.SH Members
.IP "etype" 12
Event Type
.IP "etype_rev" 12
Event Type Revision
.IP "ehl" 12
Event Header Length
.IP "rsvd3" 12
Reserved
.IP "cntlid" 12
Controller Identifier
.IP "ets" 12
Event Timestamp
.IP "rsvd14" 12
Reserved
.IP "vsil" 12
Vendor Specific Information Length
.IP "el" 12
Event Length
