.TH "nvme_subsystem_get_fw_rev" 9 "nvme_subsystem_get_fw_rev" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_get_fw_rev \- Return the firmware rev of subsystem
.SH SYNOPSIS
.B "const char *" nvme_subsystem_get_fw_rev
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
nvme_subsystem_t object
.SH "RETURN"
Firmware revision of the current subsystem
