.TH "nvme_namespace_for_each_path" 9 "nvme_namespace_for_each_path" "April 2022" "libnvme API manual" LINUX
.SH NAME
nvme_namespace_for_each_path \- Traverse paths
.SH SYNOPSIS
.B "nvme_namespace_for_each_path
.BI "(c "  ","
.BI "p "  ");"
.SH ARGUMENTS
.IP "c" 12
-- undescribed --
.IP "p" 12
\fInvme_path_t\fP object
