.TH "nvme_set_features_irq_config" 9 "nvme_set_features_irq_config" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_set_features_irq_config \- Set IRQ config feature
.SH SYNOPSIS
.B "int" nvme_set_features_irq_config
.BI "(int fd "  ","
.BI "__u16 iv "  ","
.BI "bool cd "  ","
.BI "bool save "  ","
.BI "__u32 *result "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "iv" 12
Interrupt Vector
.IP "cd" 12
Coalescing Disable
.IP "save" 12
Save value across power states
.IP "result" 12
The command completion result from CQE dword0
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
