.TH "libnvme" 9 "enum nvme_directive_send_identify_endir" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_directive_send_identify_endir \- Enable Directive
.SH SYNOPSIS
enum nvme_directive_send_identify_endir {
.br
.BI "    NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_DISABLE"
, 
.br
.br
.BI "    NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_ENABLE"

};
.SH Constants
.IP "NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_DISABLE" 12
.IP "NVME_DIRECTIVE_SEND_IDENTIFY_ENDIR_ENABLE" 12
