.TH "libnvme" 9 "enum nvme_fctype" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_fctype \- Fabrics Command Types
.SH SYNOPSIS
enum nvme_fctype {
.br
.BI "    nvme_fabrics_type_property_set"
, 
.br
.br
.BI "    nvme_fabrics_type_connect"
, 
.br
.br
.BI "    nvme_fabrics_type_property_get"
, 
.br
.br
.BI "    nvme_fabrics_type_auth_send"
, 
.br
.br
.BI "    nvme_fabrics_type_auth_receive"
, 
.br
.br
.BI "    nvme_fabrics_type_disconnect"

};
.SH Constants
.IP "nvme_fabrics_type_property_set" 12
Property set
.IP "nvme_fabrics_type_connect" 12
Connect
.IP "nvme_fabrics_type_property_get" 12
Property Get
.IP "nvme_fabrics_type_auth_send" 12
Authentication Send
.IP "nvme_fabrics_type_auth_receive" 12
Authentication Receive
.IP "nvme_fabrics_type_disconnect" 12
Disconnect
