.TH "libnvme" 9 "enum nvme_ns_mgmt_sel" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_ns_mgmt_sel \- Namespace Management - Select
.SH SYNOPSIS
enum nvme_ns_mgmt_sel {
.br
.BI "    NVME_NS_MGMT_SEL_CREATE"
, 
.br
.br
.BI "    NVME_NS_MGMT_SEL_DELETE"

};
.SH Constants
.IP "NVME_NS_MGMT_SEL_CREATE" 12
Namespace Create selection
.IP "NVME_NS_MGMT_SEL_DELETE" 12
Namespace Delete selection
