.TH "nvme_subsystem_for_each_ns_safe" 9 "nvme_subsystem_for_each_ns_safe" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_for_each_ns_safe \- Traverse namespaces
.SH SYNOPSIS
.B "nvme_subsystem_for_each_ns_safe
.BI "(s "  ","
.BI "n "  ","
.BI "_n "  ");"
.SH ARGUMENTS
.IP "s" 12
nvme_subsystem_t object
.IP "n" 12
nvme_ns_t object
.IP "_n" 12
temporary nvme_ns_t object
