.TH "nvme_psd_power_scale" 9 "nvme_psd_power_scale" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_psd_power_scale \- power scale occupies the upper 3 bits
.SH SYNOPSIS
.B "unsigned int" nvme_psd_power_scale
.BI "(__u8 ps "  ");"
.SH ARGUMENTS
.IP "ps" 12
power scale value
.SH "RETURN"
power scale value
