.TH "libnvme" 9 "enum nvme_apst_entry" "April 2022" "API Manual" LINUX
.SH NAME
enum nvme_apst_entry \- 
.SH SYNOPSIS
enum nvme_apst_entry {
.br
.BI "    NVME_APST_ENTRY_ITPS_SHIFT"
, 
.br
.br
.BI "    NVME_APST_ENTRY_ITPT_SHIFT"
, 
.br
.br
.BI "    NVME_APST_ENTRY_ITPS_MASK"
, 
.br
.br
.BI "    NVME_APST_ENTRY_ITPT_MASK"

};
.SH Constants
.IP "NVME_APST_ENTRY_ITPS_SHIFT" 12
.IP "NVME_APST_ENTRY_ITPT_SHIFT" 12
.IP "NVME_APST_ENTRY_ITPS_MASK" 12
.IP "NVME_APST_ENTRY_ITPT_MASK" 12
