.TH "libnvme" 9 "struct nvme_id_iocs" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_id_iocs \- NVMe Identify IO Command Set data structure
.SH SYNOPSIS
struct nvme_id_iocs {
.br
.BI "    __u64 iocsc[512];"
.br
.BI "
};
.br

.SH Members
.IP "iocsc" 12
List of supported IO Command Set Combination vectors
