.TH "nvme_update_config" 9 "nvme_update_config" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_update_config \- Update JSON configuration
.SH SYNOPSIS
.B "int" nvme_update_config
.BI "(nvme_root_t r "  ");"
.SH ARGUMENTS
.IP "r" 12
nvme_root_t object
.SH "DESCRIPTION"
Updates the JSON configuration file with the contents of \fIr\fP.
.SH "RETURN"
0 on success, -1 on failure.
