.TH "libnvme" 9 "enum nvme_dsm_attributes" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_dsm_attributes \- Dataset Management attributes
.SH SYNOPSIS
enum nvme_dsm_attributes {
.br
.BI "    NVME_DSMGMT_IDR"
, 
.br
.br
.BI "    NVME_DSMGMT_IDW"
, 
.br
.br
.BI "    NVME_DSMGMT_AD"

};
.SH Constants
.IP "NVME_DSMGMT_IDR" 12
Attribute -Integral Dataset for Read
.IP "NVME_DSMGMT_IDW" 12
Attribute - Integral Dataset for Write
.IP "NVME_DSMGMT_AD" 12
Attribute - Deallocate
