.TH "libnvme" 9 "enum nvme_identify_cns" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_identify_cns \- Identify - CNS Values
.SH SYNOPSIS
enum nvme_identify_cns {
.br
.BI "    NVME_IDENTIFY_CNS_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CTRL"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_ACTIVE_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_DESC_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NVMSET_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_CTRL"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_NS_ACTIVE_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_INDEPENDENT_ID_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_USER_DATA_FORMAT"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_NS_USER_DATA_FORMAT"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ALLOCATED_NS_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ALLOCATED_NS"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_PRIMARY_CTRL_CAP"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_SECONDARY_CTRL_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_NS_GRANULARITY"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_UUID_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_DOMAIN_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_ENDURANCE_GROUP_ID"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_ALLOCATED_NS_LIST"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_CSI_ID_NS_DATA_STRUCTURE"
, 
.br
.br
.BI "    NVME_IDENTIFY_CNS_COMMAND_SET_STRUCTURE"

};
.SH Constants
.IP "NVME_IDENTIFY_CNS_NS" 12
Identify Namespace data structure
.IP "NVME_IDENTIFY_CNS_CTRL" 12
Identify Controller data structure
.IP "NVME_IDENTIFY_CNS_NS_ACTIVE_LIST" 12
Active Namespace ID list
.IP "NVME_IDENTIFY_CNS_NS_DESC_LIST" 12
Namespace Identification Descriptor list
.IP "NVME_IDENTIFY_CNS_NVMSET_LIST" 12
NVM Set List
.IP "NVME_IDENTIFY_CNS_CSI_NS" 12
I/O Command Set specific Identify
Namespace data structure
.IP "NVME_IDENTIFY_CNS_CSI_CTRL" 12
I/O Command Set specific Identify
Controller data structure
.IP "NVME_IDENTIFY_CNS_CSI_NS_ACTIVE_LIST" 12
Active Namespace ID list associated
with the specified I/O Command Set
.IP "NVME_IDENTIFY_CNS_CSI_INDEPENDENT_ID_NS" 12
I/O Command Set Independent Identify
.IP "NVME_IDENTIFY_CNS_NS_USER_DATA_FORMAT" 12
Namespace user data format
.IP "NVME_IDENTIFY_CNS_CSI_NS_USER_DATA_FORMAT" 12
I/O Command Set specific user data
format
Namespace data structure
.IP "NVME_IDENTIFY_CNS_ALLOCATED_NS_LIST" 12
Allocated Namespace ID list
.IP "NVME_IDENTIFY_CNS_ALLOCATED_NS" 12
Identify Namespace data structure for
the specified allocated NSID
.IP "NVME_IDENTIFY_CNS_NS_CTRL_LIST" 12
Controller List of controllers attached
to the specified NSID
.IP "NVME_IDENTIFY_CNS_CTRL_LIST" 12
Controller List of controllers that exist
in the NVM subsystem
.IP "NVME_IDENTIFY_CNS_PRIMARY_CTRL_CAP" 12
Primary Controller Capabilities data
structure for the specified primary controller
.IP "NVME_IDENTIFY_CNS_SECONDARY_CTRL_LIST" 12
Secondary Controller list of controllers
associated with the primary controller
processing the command
.IP "NVME_IDENTIFY_CNS_NS_GRANULARITY" 12
A Namespace Granularity List
.IP "NVME_IDENTIFY_CNS_UUID_LIST" 12
A UUID List
.IP "NVME_IDENTIFY_CNS_DOMAIN_LIST" 12
Domain List
.IP "NVME_IDENTIFY_CNS_ENDURANCE_GROUP_ID" 12
Endurance Group List
.IP "NVME_IDENTIFY_CNS_CSI_ALLOCATED_NS_LIST" 12
I/O Command Set specific Allocated Namespace
ID list
.IP "NVME_IDENTIFY_CNS_CSI_ID_NS_DATA_STRUCTURE" 12
I/O Command Set specific ID Namespace
Data Structure for Allocated Namespace ID
.IP "NVME_IDENTIFY_CNS_COMMAND_SET_STRUCTURE" 12
Base Specification 2.0a section 5.17.2.21
