.TH "nvme_lm_track_send" 9 "nvme_lm_track_send" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_lm_track_send \- Track Send command
.SH SYNOPSIS
.B "int" nvme_lm_track_send
.BI "(struct nvme_lm_track_send_args *args "  ");"
.SH ARGUMENTS
.IP "args" 12
\fIstruct nvme_lm_track_send_args\fP argument structure
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
