.TH "libnvme" 9 "struct nvme_zns_lbafe" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_zns_lbafe \- 
.SH SYNOPSIS
struct nvme_zns_lbafe {
.br
.BI "    __le64 zsze;"
.br
.BI "    __u8 zdes;"
.br
.BI "    __u8 rsvd9[7];"
.br
.BI "
};
.br

.SH Members
.IP "zsze" 12
.IP "zdes" 12
.IP "rsvd9" 12
