.TH "libnvme" 9 "enum nvme_bpmbl" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_bpmbl \- This field indicates the boot partition memory buffer location
.SH SYNOPSIS
enum nvme_bpmbl {
.br
.BI "    NVME_BPMBL_BMBBA_SHIFT"

};
.SH Constants
.IP "NVME_BPMBL_BMBBA_SHIFT" 12
Shift amount to get the boot partition memory buffer base address
