.TH "nvme_identify_endurance_group_list" 9 "nvme_identify_endurance_group_list" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_identify_endurance_group_list \- Endurance group list data
.SH SYNOPSIS
.B "int" nvme_identify_endurance_group_list
.BI "(int fd "  ","
.BI "__u16 endgrp_id "  ","
.BI "struct nvme_id_endurance_group_list *list "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "endgrp_id" 12
Endurance group identifier
.IP "list" 12
Array of endurance group identifiers
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
