.TH "nvme_get_log_fid_supported_effects" 9 "nvme_get_log_fid_supported_effects" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_fid_supported_effects \- Retrieve Feature Identifiers Supported and Effects
.SH SYNOPSIS
.B "int" nvme_get_log_fid_supported_effects
.BI "(int fd "  ","
.BI "bool rae "  ","
.BI "struct nvme_fid_supported_effects_log *log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "rae" 12
Retain asynchronous events
.IP "log" 12
FID Supported and Effects data structure
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise
