.TH "libnvme" 9 "enum nvme_zns_za" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_zns_za \- Zone Descriptor Data Structure
.SH SYNOPSIS
enum nvme_zns_za {
.br
.BI "    NVME_ZNS_ZA_ZFC"
, 
.br
.br
.BI "    NVME_ZNS_ZA_FZR"
, 
.br
.br
.BI "    NVME_ZNS_ZA_RZR"
, 
.br
.br
.BI "    NVME_ZNS_ZA_ZRWAV"
, 
.br
.br
.BI "    NVME_ZNS_ZA_ZDEV"

};
.SH Constants
.IP "NVME_ZNS_ZA_ZFC" 12
Zone Finished by Controller
.IP "NVME_ZNS_ZA_FZR" 12
Finish Zone Recommended
.IP "NVME_ZNS_ZA_RZR" 12
Reset Zone Recommended
.IP "NVME_ZNS_ZA_ZRWAV" 12
.IP "NVME_ZNS_ZA_ZDEV" 12
Zone Descriptor Extension Valid
