.TH "libnvme" 9 "enum nvme_csi" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_csi \- Defined command set indicators
.SH SYNOPSIS
enum nvme_csi {
.br
.BI "    NVME_CSI_NVM"
, 
.br
.br
.BI "    NVME_CSI_KV"
, 
.br
.br
.BI "    NVME_CSI_ZNS"

};
.SH Constants
.IP "NVME_CSI_NVM" 12
NVM Command Set Indicator
.IP "NVME_CSI_KV" 12
Key Value Command Set
.IP "NVME_CSI_ZNS" 12
Zoned Namespace Command Set
