.TH "libnvme" 9 "struct nvme_feat_host_behavior" "May 2025" "API Manual" LINUX
.SH NAME
struct nvme_feat_host_behavior \- Host Behavior Support - Data Structure
.SH SYNOPSIS
struct nvme_feat_host_behavior {
.br
.BI "    __u8 acre;"
.br
.BI "    __u8 etdas;"
.br
.BI "    __u8 lbafee;"
.br
.BI "    __u8 hdisns;"
.br
.BI "    __le16 cdfe;"
.br
.BI "    __u8 rsvd6[506];"
.br
.BI "
};
.br

.SH Members
.IP "acre" 12
Advanced Command Retry Enable
.IP "etdas" 12
Extended Telemetry Data Area 4 Supported
.IP "lbafee" 12
LBA Format Extension Enable
.IP "hdisns" 12
Host Dispersed Namespace Support
.IP "cdfe" 12
Copy Descriptor Formats Enable
.IP "rsvd6" 12
Reserved
