.TH "libnvme" 9 "struct nvme_perf_attr_id" "May 2025" "API Manual" LINUX
.SH NAME
struct nvme_perf_attr_id \- Performance attribute identifier structure
.SH SYNOPSIS
struct nvme_perf_attr_id {
.br
.BI "    __u8 id[NVME_UUID_LEN];"
.br
.BI "
};
.br

.SH Members
.IP "id" 12
Performance attribute identifier
