.TH "libnvme" 9 "struct nvme_mi_read_port_info" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_mi_read_port_info \- Port Information Data Structure
.SH SYNOPSIS
struct nvme_mi_read_port_info {
.br
.BI "    __u8 portt;"
.br
.BI "    __u8 rsvd1;"
.br
.BI "    __le16 mmctptus;"
.br
.BI "    __le32 meb;"
.br
.BI "    union {"
.br
.BI "      struct nvme_mi_port_pcie pcie;"
.br
.BI "      struct nvme_mi_port_smb smb;"
.br
.BI "    };"
.br
.BI "
};
.br

.SH Members
.IP "portt" 12
Port Type
.IP "rsvd1" 12
Reserved
.IP "mmctptus" 12
Maximum MCTP Transmission Unit Size
.IP "meb" 12
Management Endpoint Buffer Size
.IP "{unnamed_union}" 12
anonymous
.IP "pcie" 12
PCIe Port Specific Data
.IP "smb" 12
SMBus Port Specific Data
