.TH "nvme_mi_admin_identify_ns_descs" 9 "nvme_mi_admin_identify_ns_descs" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_identify_ns_descs \- Perform an Admin identify Namespace Identification Descriptor list command for a namespace
.SH SYNOPSIS
.B "int" nvme_mi_admin_identify_ns_descs
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "__u32 nsid "  ","
.BI "struct nvme_ns_id_desc *descs "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to process identify command
.IP "nsid" 12
Namespace ID
.IP "descs" 12
Namespace Identification Descriptor list to populate
.SH "DESCRIPTION"
Perform an Identify namespace identification description list command,
setting the namespace identification description list in \fIdescs\fP
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
