.TH "nvme_get_features_timestamp" 9 "nvme_get_features_timestamp" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_features_timestamp \- Get timestamp feature
.SH SYNOPSIS
.B "int" nvme_get_features_timestamp
.BI "(int fd "  ","
.BI "enum nvme_get_features_sel sel "  ","
.BI "struct nvme_timestamp *ts "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "sel" 12
Select which type of attribute to return, see \fIenum nvme_get_features_sel\fP
.IP "ts" 12
Current timestamp
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
