.TH "libnvme" 9 "enum nvme_directive_receive_doper" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_directive_receive_doper \- Directive Receive Directive Operation
.SH SYNOPSIS
enum nvme_directive_receive_doper {
.br
.BI "    NVME_DIRECTIVE_RECEIVE_IDENTIFY_DOPER_PARAM"
, 
.br
.br
.BI "    NVME_DIRECTIVE_RECEIVE_STREAMS_DOPER_PARAM"
, 
.br
.br
.BI "    NVME_DIRECTIVE_RECEIVE_STREAMS_DOPER_STATUS"
, 
.br
.br
.BI "    NVME_DIRECTIVE_RECEIVE_STREAMS_DOPER_RESOURCE"

};
.SH Constants
.IP "NVME_DIRECTIVE_RECEIVE_IDENTIFY_DOPER_PARAM" 12
.IP "NVME_DIRECTIVE_RECEIVE_STREAMS_DOPER_PARAM" 12
.IP "NVME_DIRECTIVE_RECEIVE_STREAMS_DOPER_STATUS" 12
.IP "NVME_DIRECTIVE_RECEIVE_STREAMS_DOPER_RESOURCE" 12
