.TH "libnvme" 9 "enum nvme_nvmset_pl_events" "April 2022" "API Manual" LINUX
.SH NAME
enum nvme_nvmset_pl_events \- 
.SH SYNOPSIS
enum nvme_nvmset_pl_events {
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_READ_WARN"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_WRITE_WARN"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_TIME_WARN"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_EXCEEDED"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_EXCURSION"

};
.SH Constants
.IP "NVME_NVMSET_PL_EVENT_DTWIN_READ_WARN" 12
.IP "NVME_NVMSET_PL_EVENT_DTWIN_WRITE_WARN" 12
.IP "NVME_NVMSET_PL_EVENT_DTWIN_TIME_WARN" 12
.IP "NVME_NVMSET_PL_EVENT_DTWIN_EXCEEDED" 12
.IP "NVME_NVMSET_PL_EVENT_DTWIN_EXCURSION" 12
