.TH "libnvme" 9 "enum nvme_fid_supported_effects" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_fid_supported_effects \- FID Supported and Effects Data Structure definitions
.SH SYNOPSIS
enum nvme_fid_supported_effects {
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_FSUPP"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_UDCC"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_NCC"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_NIC"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_CCC"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_UUID_SEL"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_SHIFT"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_MASK"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_NS"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_CTRL"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_NVM_SET"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_ENDGRP"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_DOMAIN"
, 
.br
.br
.BI "    NVME_FID_SUPPORTED_EFFECTS_SCOPE_NSS"

};
.SH Constants
.IP "NVME_FID_SUPPORTED_EFFECTS_FSUPP" 12
FID Supported
.IP "NVME_FID_SUPPORTED_EFFECTS_UDCC" 12
User Data Content Change
.IP "NVME_FID_SUPPORTED_EFFECTS_NCC" 12
Namespace Capability Change
.IP "NVME_FID_SUPPORTED_EFFECTS_NIC" 12
Namespace Inventory Change
.IP "NVME_FID_SUPPORTED_EFFECTS_CCC" 12
Controller Capability Change
.IP "NVME_FID_SUPPORTED_EFFECTS_UUID_SEL" 12
UUID Selection Supported
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_SHIFT" 12
FID Scope Shift
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_MASK" 12
FID Scope Mask
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_NS" 12
Namespace Scope
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_CTRL" 12
Controller Scope
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_NVM_SET" 12
NVM Set Scope
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_ENDGRP" 12
Endurance Group Scope
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_DOMAIN" 12
Domain Scope
.IP "NVME_FID_SUPPORTED_EFFECTS_SCOPE_NSS" 12
NVM Subsystem Scope
