.TH "nvme_ctrl_first_path" 9 "nvme_ctrl_first_path" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_first_path \- Start path iterator
.SH SYNOPSIS
.B "nvme_path_t" nvme_ctrl_first_path
.BI "(nvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
First \fInvme_path_t\fP object of an \fIc\fP iterator
