.TH "nvme_read_config" 9 "nvme_read_config" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_read_config \- Read NVMe JSON configuration file
.SH SYNOPSIS
.B "int" nvme_read_config
.BI "(nvme_root_t r "  ","
.BI "const char *config_file "  ");"
.SH ARGUMENTS
.IP "r" 12
nvme_root_t object
.IP "config_file" 12
JSON configuration file
.SH "DESCRIPTION"
Read in the contents of \fIconfig_file\fP and merge them with
the elements in \fIr\fP.
.SH "RETURN"
0 on success, -1 on failure with errno set.
