.TH "nvme_free_subsystem" 9 "nvme_free_subsystem" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_free_subsystem \- Free a subsystem
.SH SYNOPSIS
.B "void" nvme_free_subsystem
.BI "(struct nvme_subsystem *s "  ");"
.SH ARGUMENTS
.IP "s" 12
subsystem
.SH "DESCRIPTION"
Frees \fIs\fP and all related objects.
