.TH "libnvme" 9 "enum nvme_acq" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_acq \- This field indicates the admin completion queue base address
.SH SYNOPSIS
enum nvme_acq {
.br
.BI "    NVME_ACQ_ACQB_SHIFT"

};
.SH Constants
.IP "NVME_ACQ_ACQB_SHIFT" 12
Shift amount to get the admin completion queue base
