.TH "nvme_get_log_support_cap_config_list" 9 "nvme_get_log_support_cap_config_list" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_support_cap_config_list \- Retrieve Supported Capacity Configuration List
.SH SYNOPSIS
.B "int" nvme_get_log_support_cap_config_list
.BI "(int fd "  ","
.BI "__u16 domid "  ","
.BI "struct nvme_supported_cap_config_list_log *cap "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "domid" 12
Domain Identifier selection, if supported
.IP "cap" 12
User address to store supported capabilities config list
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise
