.TH "nvme_mi_aem_aesi_get_aese" 9 "nvme_mi_aem_aesi_get_aese" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_aem_aesi_get_aese \- return aese from aesi field
.SH SYNOPSIS
.B "bool" nvme_mi_aem_aesi_get_aese
.BI "(__le16 aesi "  ");"
.SH ARGUMENTS
.IP "aesi" 12
aesi field from \fInvme_mi_aem_supported_item\fP
.SH "RETURN"
A bool representing the aese value
