.TH "libnvme" 9 "enum nvme_id_uuid" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_id_uuid \- Identifier Association
.SH SYNOPSIS
enum nvme_id_uuid {
.br
.BI "    NVME_ID_UUID_HDR_ASSOCIATION_MASK"
, 
.br
.br
.BI "    NVME_ID_UUID_ASSOCIATION_NONE"
, 
.br
.br
.BI "    NVME_ID_UUID_ASSOCIATION_VENDOR"
, 
.br
.br
.BI "    NVME_ID_UUID_ASSOCIATION_SUBSYSTEM_VENDOR"

};
.SH Constants
.IP "NVME_ID_UUID_HDR_ASSOCIATION_MASK" 12
.IP "NVME_ID_UUID_ASSOCIATION_NONE" 12
.IP "NVME_ID_UUID_ASSOCIATION_VENDOR" 12
.IP "NVME_ID_UUID_ASSOCIATION_SUBSYSTEM_VENDOR" 12
