.TH "libnvme" 9 "enum nvme_id_ctrl_nvscc" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_nvscc \- This field indicates the configuration settings for NVM Vendor Specific command handling.
.SH SYNOPSIS
enum nvme_id_ctrl_nvscc {
.br
.BI "    NVME_CTRL_NVSCC_FMT"

};
.SH Constants
.IP "NVME_CTRL_NVSCC_FMT" 12
If set, all NVM Vendor Specific Commands use the
format with NDT and NDM fields.
