.TH "libnvme" 9 "enum nvme_pmrctl" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_pmrctl \- This field indicates the persistent memory region control
.SH SYNOPSIS
enum nvme_pmrctl {
.br
.BI "    NVME_PMRCTL_EN_SHIFT"
, 
.br
.br
.BI "    NVME_PMRCTL_EN_MASK"

};
.SH Constants
.IP "NVME_PMRCTL_EN_SHIFT" 12
Shift amount to get the enable
.IP "NVME_PMRCTL_EN_MASK" 12
Mask to get the enable
