.TH "nvme_get_log_create_telemetry_host_mcda" 9 "nvme_get_log_create_telemetry_host_mcda" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_create_telemetry_host_mcda \- Create host telemetry log
.SH SYNOPSIS
.B "int" nvme_get_log_create_telemetry_host_mcda
.BI "(int fd "  ","
.BI "enum nvme_telemetry_da mcda "  ","
.BI "struct nvme_telemetry_log *log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "mcda" 12
Maximum Created Data Area
.IP "log" 12
Userspace address of the log payload
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
