.TH "libnvme" 9 "struct nvme_cmd_effects_log" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_cmd_effects_log \- Commands Supported and Effects Log
.SH SYNOPSIS
struct nvme_cmd_effects_log {
.br
.BI "    __le32 acs[256];"
.br
.BI "    __le32 iocs[256];"
.br
.BI "    __u8 rsvd[2048];"
.br
.BI "
};
.br

.SH Members
.IP "acs" 12
Admin Command Supported
.IP "iocs" 12
I/O Command Supported
.IP "rsvd" 12
Reserved
