.TH "libnvme" 9 "enum nvme_get_features_sel" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_get_features_sel \- Get Features - Select
.SH SYNOPSIS
enum nvme_get_features_sel {
.br
.BI "    NVME_GET_FEATURES_SEL_CURRENT"
, 
.br
.br
.BI "    NVME_GET_FEATURES_SEL_DEFAULT"
, 
.br
.br
.BI "    NVME_GET_FEATURES_SEL_SAVED"
, 
.br
.br
.BI "    NVME_GET_FEATURES_SEL_SUPPORTED"

};
.SH Constants
.IP "NVME_GET_FEATURES_SEL_CURRENT" 12
Current value
.IP "NVME_GET_FEATURES_SEL_DEFAULT" 12
Default value
.IP "NVME_GET_FEATURES_SEL_SAVED" 12
Saved value
.IP "NVME_GET_FEATURES_SEL_SUPPORTED" 12
Supported capabilities
