.TH "nvme_ctrl_get_tls_key" 9 "nvme_ctrl_get_tls_key" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_get_tls_key \- Return Derive TLS PSK
.SH SYNOPSIS
.B "const char *" nvme_ctrl_get_tls_key
.BI "(nvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller to be used for the lookup
.SH "RETURN"
Key in PSK interchange format or NULL if not set
