.TH "libnvme" 9 "enum nvme_mi_csts" "February 2022" "API Manual" LINUX
.SH NAME
enum nvme_mi_csts \- 
.SH SYNOPSIS
enum nvme_mi_csts {
.br
.BI "    NVME_MI_CSTS_RDY"
, 
.br
.br
.BI "    NVME_MI_CSTS_CFS"
, 
.br
.br
.BI "    NVME_MI_CSTS_SHST"
, 
.br
.br
.BI "    NVME_MI_CSTS_NSSRO"
, 
.br
.br
.BI "    NVME_MI_CSTS_CECO"
, 
.br
.br
.BI "    NVME_MI_CSTS_NAC"
, 
.br
.br
.BI "    NVME_MI_CSTS_FA"

};
.SH Constants
.IP "NVME_MI_CSTS_RDY" 12
.IP "NVME_MI_CSTS_CFS" 12
.IP "NVME_MI_CSTS_SHST" 12
.IP "NVME_MI_CSTS_NSSRO" 12
.IP "NVME_MI_CSTS_CECO" 12
.IP "NVME_MI_CSTS_NAC" 12
.IP "NVME_MI_CSTS_FA" 12
