.TH "nvme_zns_identify_ns" 9 "nvme_zns_identify_ns" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_zns_identify_ns \- ZNS identify namespace data
.SH SYNOPSIS
.B "int" nvme_zns_identify_ns
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "struct nvme_zns_id_ns *data "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace to identify
.IP "data" 12
User space destination address to transfer the data
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
