.TH "libnvme" 9 "struct nvme_id_ns_granularity_list" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_id_ns_granularity_list \- Namespace Granularity List
.SH SYNOPSIS
struct nvme_id_ns_granularity_list {
.br
.BI "    __le32 attributes;"
.br
.BI "    __u8 num_descriptors;"
.br
.BI "    __u8 rsvd5[27];"
.br
.BI "    struct nvme_id_ns_granularity_desc entry[NVME_ID_ND_DESCRIPTOR_MAX];"
.br
.BI "    __u8 rsvd288[3808];"
.br
.BI "
};
.br

.SH Members
.IP "attributes" 12
Namespace Granularity Attributes
.IP "num_descriptors" 12
Number of Descriptors
.IP "rsvd5" 12
reserved
.IP "entry" 12
Namespace Granularity Descriptor
.IP "rsvd288" 12
reserved
