.TH "libnvme" 9 "enum nvme_resv_rrega" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_resv_rrega \- Reservation Register - Reservation Register Action
.SH SYNOPSIS
enum nvme_resv_rrega {
.br
.BI "    NVME_RESERVATION_RREGA_REGISTER_KEY"
, 
.br
.br
.BI "    NVME_RESERVATION_RREGA_UNREGISTER_KEY"
, 
.br
.br
.BI "    NVME_RESERVATION_RREGA_REPLACE_KEY"

};
.SH Constants
.IP "NVME_RESERVATION_RREGA_REGISTER_KEY" 12
Register Reservation Key
.IP "NVME_RESERVATION_RREGA_UNREGISTER_KEY" 12
Unregister Reservation Key
.IP "NVME_RESERVATION_RREGA_REPLACE_KEY" 12
Replace Reservation Key
