.TH "libnvme" 9 "enum nvme_cmd_format_mset" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_cmd_format_mset \- Format NVM - Metadata Settings
.SH SYNOPSIS
enum nvme_cmd_format_mset {
.br
.BI "    NVME_FORMAT_MSET_SEPARATE"
, 
.br
.br
.BI "    NVME_FORMAT_MSET_EXTENDED"

};
.SH Constants
.IP "NVME_FORMAT_MSET_SEPARATE" 12
indicates that the metadata is transferred
as part of a separate buffer.
.IP "NVME_FORMAT_MSET_EXTENDED" 12
indicates that the metadata is transferred
as part of an extended data LBA.
