.TH "nvme_ns_compare" 2 "nvme_ns_compare" "February 2020" "libnvme Manual"
.SH NAME
nvme_ns_compare \- 
.SH SYNOPSIS
.B "int" nvme_ns_compare
.BI "(nvme_ns_t " n ","
.BI "void *" buf ","
.BI "off_t " offset ","
.BI "size_t " count ");"
.SH ARGUMENTS
.IP "n" 12
-- undescribed --
.IP "buf" 12
-- undescribed --
.IP "offset" 12
-- undescribed --
.IP "count" 12
