.TH "nvme_submit_io_passthru64" 9 "nvme_submit_io_passthru64" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_submit_io_passthru64 \- Submit a 64-bit nvme passthrough command
.SH SYNOPSIS
.B "int" nvme_submit_io_passthru64
.BI "(int fd "  ","
.BI "struct nvme_passthru_cmd64 *cmd "  ","
.BI "__u64 *result "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "cmd" 12
The nvme io command to send
.IP "result" 12
Optional field to return the result from the CQE DW0-1
.SH "DESCRIPTION"
Uses NVME_IOCTL_IO64_CMD for the ioctl request.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
