.TH "libnvme" 9 "struct nvme_id_ctrl_nvm" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_id_ctrl_nvm \- 
.SH SYNOPSIS
struct nvme_id_ctrl_nvm {
.br
.BI "    __u8 vsl;"
.br
.BI "    __u8 wzsl;"
.br
.BI "    __u8 wusl;"
.br
.BI "    __u8 dmrl;"
.br
.BI "    __u32 dmrsl;"
.br
.BI "    __u64 dmsl;"
.br
.BI "    __u8 rsvd16[4080];"
.br
.BI "
};
.br

.SH Members
.IP "vsl" 12
.IP "wzsl" 12
.IP "wusl" 12
.IP "dmrl" 12
.IP "dmrsl" 12
.IP "dmsl" 12
.IP "rsvd16" 12
