.TH "libnvme" 9 "enum nvme_resv_rrela" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_resv_rrela \- Reservation Release - Reservation Release Action
.SH SYNOPSIS
enum nvme_resv_rrela {
.br
.BI "    NVME_RESERVATION_RRELA_RELEASE"
, 
.br
.br
.BI "    NVME_RESERVATION_RRELA_CLEAR"

};
.SH Constants
.IP "NVME_RESERVATION_RRELA_RELEASE" 12
Release
.IP "NVME_RESERVATION_RRELA_CLEAR" 12
Clear
