.TH "libnvme" 9 "struct nvme_mi_vpd_hdr" "February 2022" "API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_hdr \- 
.SH SYNOPSIS
struct nvme_mi_vpd_hdr {
.br
.BI "    __u8 ipmiver;"
.br
.BI "    __u8 iuaoff;"
.br
.BI "    __u8 ciaoff;"
.br
.BI "    __u8 biaoff;"
.br
.BI "    __u8 piaoff;"
.br
.BI "    __u8 mrioff;"
.br
.BI "    __u8 rsvd6;"
.br
.BI "    __u8 chchk;"
.br
.BI "    __u8 vpd[];"
.br
.BI "
};
.br

.SH Members
.IP "ipmiver" 12
.IP "iuaoff" 12
.IP "ciaoff" 12
.IP "biaoff" 12
.IP "piaoff" 12
.IP "mrioff" 12
.IP "rsvd6" 12
.IP "chchk" 12
.IP "vpd" 12
