.TH "nvme_subsystem_get_nqn" 9 "nvme_subsystem_get_nqn" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_get_nqn \- Retrieve NQN from subsystem
.SH SYNOPSIS
.B "const char *" nvme_subsystem_get_nqn
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
nvme_subsystem_t object
.SH "RETURN"
NQN of subsystem
