.TH "nvme_free_uri" 9 "nvme_free_uri" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_free_uri \- Free the URI structure
.SH SYNOPSIS
.B "void" nvme_free_uri
.BI "(struct nvme_fabrics_uri *uri "  ");"
.SH ARGUMENTS
.IP "uri" 12
\fInvme_fabrics_uri\fP structure
.SH "DESCRIPTION"
Free an \fInvme_fabrics_uri\fP structure.
