.TH "libnvme" 9 "enum nvme_telemetry_da" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_telemetry_da \- Telemetry Log Data Area
.SH SYNOPSIS
enum nvme_telemetry_da {
.br
.BI "    NVME_TELEMETRY_DA_1"
, 
.br
.br
.BI "    NVME_TELEMETRY_DA_2"
, 
.br
.br
.BI "    NVME_TELEMETRY_DA_3"
, 
.br
.br
.BI "    NVME_TELEMETRY_DA_4"

};
.SH Constants
.IP "NVME_TELEMETRY_DA_1" 12
Data Area 1
.IP "NVME_TELEMETRY_DA_2" 12
Data Area 2
.IP "NVME_TELEMETRY_DA_3" 12
Data Area 3
.IP "NVME_TELEMETRY_DA_4" 12
Data Area 4
