.TH "libnvme" 9 "struct nvme_mi_nvm_ss_health_status" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_mi_nvm_ss_health_status \- Subsystem Management Data Structure
.SH SYNOPSIS
struct nvme_mi_nvm_ss_health_status {
.br
.BI "    __u8 nss;"
.br
.BI "    __u8 sw;"
.br
.BI "    __u8 ctemp;"
.br
.BI "    __u8 pdlu;"
.br
.BI "    __le16 ccs;"
.br
.BI "    __u8 rsvd8[2];"
.br
.BI "
};
.br

.SH Members
.IP "nss" 12
NVM Subsystem Status
.IP "sw" 12
Smart Warnings
.IP "ctemp" 12
Composite Temperature
.IP "pdlu" 12
Percentage Drive Life Used
.IP "ccs" 12
Composite Controller Status
.IP "rsvd8" 12
Reserved
