.TH "nvme_ns_write_uncorrectable" 2 "nvme_ns_write_uncorrectable" "February 2020" "libnvme Manual"
.SH NAME
nvme_ns_write_uncorrectable \- 
.SH SYNOPSIS
.B "int" nvme_ns_write_uncorrectable
.BI "(nvme_ns_t " n ","
.BI "off_t " offset ","
.BI "size_t " count ");"
.SH ARGUMENTS
.IP "n" 12
-- undescribed --
.IP "offset" 12
-- undescribed --
.IP "count" 12
