.TH "nvme_ctrl_get_numa_node" 9 "nvme_ctrl_get_numa_node" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_get_numa_node \- NUMA node of an nvme_ctrl_t object
.SH SYNOPSIS
.B "const char *" nvme_ctrl_get_numa_node
.BI "(nvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
nvme_ctrl_t object
.SH "RETURN"
string indicating the NUMA node
