.TH "libnvme" 9 "enum nvme_asq" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_asq \- This field indicates the admin submission queue base address
.SH SYNOPSIS
enum nvme_asq {
.br
.BI "    NVME_ASQ_ASQB_SHIFT"

};
.SH Constants
.IP "NVME_ASQ_ASQB_SHIFT" 12
Shift amount to get the admin submission queue base
