.TH "nvme_set_attr" 2 "nvme_set_attr" "February 2020" "libnvme Manual"
.SH NAME
nvme_set_attr \- 
.SH SYNOPSIS
.B "int" nvme_set_attr
.BI "(const char *" dir ","
.BI "const char *" attr ","
.BI "const char *" value ");"
.SH ARGUMENTS
.IP "dir" 12
-- undescribed --
.IP "attr" 12
-- undescribed --
.IP "value" 12
.SH "DESCRIPTION"
Return 
