.TH "nvme_init_logging" 9 "nvme_init_logging" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_init_logging \- Initialize logging
.SH SYNOPSIS
.B "void" nvme_init_logging
.BI "(nvme_root_t r "  ","
.BI "int lvl "  ","
.BI "bool log_pid "  ","
.BI "bool log_tstamp "  ");"
.SH ARGUMENTS
.IP "r" 12
nvme_root_t context
.IP "lvl" 12
Logging level to set
.IP "log_pid" 12
Boolean to enable logging of the PID
.IP "log_tstamp" 12
Boolean to enable logging of the timestamp
.SH "DESCRIPTION"
Sets the default logging variables for the library.
