.TH "nvme_path_get_ana_state" 9 "nvme_path_get_ana_state" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_path_get_ana_state \- ANA state of an nvme_path_t object
.SH SYNOPSIS
.B "const char *" nvme_path_get_ana_state
.BI "(nvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fInvme_path_t\fP object
.SH "RETURN"
ANA (Asynchronous Namespace Access) state of \fIp\fP
