.TH "nvme_ns_get_uuid" 9 "nvme_ns_get_uuid" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ns_get_uuid \- UUID of a namespace
.SH SYNOPSIS
.B "void" nvme_ns_get_uuid
.BI "(nvme_ns_t n "  ","
.BI "unsigned char out[NVME_UUID_LEN] "  ");"
.SH ARGUMENTS
.IP "n" 12
Namespace instance
.IP "out" 12
buffer for the UUID
.SH "DESCRIPTION"
Copies the namespace's uuid into \fIout\fP
