.TH "libnvme" 9 "enum nvme_fdp_ruh_type" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_fdp_ruh_type \- Reclaim Unit Handle Type
.SH SYNOPSIS
enum nvme_fdp_ruh_type {
.br
.BI "    NVME_FDP_RUHT_INITIALLY_ISOLATED"
, 
.br
.br
.BI "    NVME_FDP_RUHT_PERSISTENTLY_ISOLATED"

};
.SH Constants
.IP "NVME_FDP_RUHT_INITIALLY_ISOLATED" 12
Initially Isolated
.IP "NVME_FDP_RUHT_PERSISTENTLY_ISOLATED" 12
Persistently Isolated
