.TH "nvme_directive_recv_stream_status" 9 "nvme_directive_recv_stream_status" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_directive_recv_stream_status \- Directive receive stream status
.SH SYNOPSIS
.B "int" nvme_directive_recv_stream_status
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "unsigned int nr_entries "  ","
.BI "struct nvme_streams_directive_status *id "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace ID
.IP "nr_entries" 12
Number of streams to receive
.IP "id" 12
Stream status buffer
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
