.TH "nvme_host_set_hostsymname" 9 "nvme_host_set_hostsymname" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_host_set_hostsymname \- Set the host's symbolic name
.SH SYNOPSIS
.B "void" nvme_host_set_hostsymname
.BI "(nvme_host_t h "  ","
.BI "const char *hostsymname "  ");"
.SH ARGUMENTS
.IP "h" 12
Host for which the symbolic name should be set.
.IP "hostsymname" 12
Symbolic name
