.TH "libnvme" 9 "struct nvme_primary_ctrl_cap" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_primary_ctrl_cap \- Identify - Controller Capabilities Structure
.SH SYNOPSIS
struct nvme_primary_ctrl_cap {
.br
.BI "    __le16 cntlid;"
.br
.BI "    __le16 portid;"
.br
.BI "    __u8 crt;"
.br
.BI "    __u8 rsvd5[27];"
.br
.BI "    __le32 vqfrt;"
.br
.BI "    __le32 vqrfa;"
.br
.BI "    __le16 vqrfap;"
.br
.BI "    __le16 vqprt;"
.br
.BI "    __le16 vqfrsm;"
.br
.BI "    __le16 vqgran;"
.br
.BI "    __u8 rsvd48[16];"
.br
.BI "    __le32 vifrt;"
.br
.BI "    __le32 virfa;"
.br
.BI "    __le16 virfap;"
.br
.BI "    __le16 viprt;"
.br
.BI "    __le16 vifrsm;"
.br
.BI "    __le16 vigran;"
.br
.BI "    __u8 rsvd80[4016];"
.br
.BI "
};
.br

.SH Members
.IP "cntlid" 12
Controller Identifier
.IP "portid" 12
Port Identifier
.IP "crt" 12
Controller Resource Types
.IP "rsvd5" 12
reserved
.IP "vqfrt" 12
VQ Resources Flexible Total
.IP "vqrfa" 12
VQ Resources Flexible Assigned
.IP "vqrfap" 12
VQ Resources Flexible Allocated to Primary
.IP "vqprt" 12
VQ Resources Private Total
.IP "vqfrsm" 12
VQ Resources Flexible Secondary Maximum
.IP "vqgran" 12
VQ Flexible Resource Preferred Granularity
.IP "rsvd48" 12
reserved
.IP "vifrt" 12
VI Resources Flexible Total
.IP "virfa" 12
VI Resources Flexible Assigned
.IP "virfap" 12
VI Resources Flexible Allocated to Primary
.IP "viprt" 12
VI Resources Private Total
.IP "vifrsm" 12
VI Resources Flexible Secondary Maximum
.IP "vigran" 12
VI Flexible Resource Preferred Granularity
.IP "rsvd80" 12
reserved
