.TH "nvme_get_log_reachability_groups" 9 "nvme_get_log_reachability_groups" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_reachability_groups \- Retrieve Reachability Groups Log
.SH SYNOPSIS
.B "int" nvme_get_log_reachability_groups
.BI "(int fd "  ","
.BI "bool rgo "  ","
.BI "bool rae "  ","
.BI "__u32 len "  ","
.BI "struct nvme_reachability_groups_log *log "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "rgo" 12
Return groups only
.IP "rae" 12
Retain asynchronous events
.IP "len" 12
The allocated length of the log page
.IP "log" 12
User address to store the log page
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise
