.TH "nvme_subsystem_get_model" 9 "nvme_subsystem_get_model" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_get_model \- Return the model of subsystem
.SH SYNOPSIS
.B "const char *" nvme_subsystem_get_model
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
nvme_subsystem_t object
.SH "RETURN"
Model of the current subsystem
