.TH "libnvme" 9 "enum nvme_cmbsts" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_cmbsts \- This field indicates the controller memory buffer status
.SH SYNOPSIS
enum nvme_cmbsts {
.br
.BI "    NVME_CMBSTS_CBAI_SHIFT"
, 
.br
.br
.BI "    NVME_CMBSTS_CBAI_MASK"

};
.SH Constants
.IP "NVME_CMBSTS_CBAI_SHIFT" 12
Shift amount to get the controller base address invalid
.IP "NVME_CMBSTS_CBAI_MASK" 12
Mask to get the controller base address invalid
