.TH "nvme_mi_admin_get_log_smart" 9 "nvme_mi_admin_get_log_smart" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_smart \- Retrieve nvme smart log
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_smart
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "__u32 nsid "  ","
.BI "bool rae "  ","
.BI "struct nvme_smart_log *smart_log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "nsid" 12
Optional namespace identifier
.IP "rae" 12
Retain asynchronous events
.IP "smart_log" 12
User address to store the smart log
.SH "DESCRIPTION"
This log page provides SMART and general health information. The information
provided is over the life of the controller and is retained across power
cycles. To request the controller log page, the namespace identifier
specified is FFFFFFFFh. The controller may also support requesting the log
page on a per namespace basis, as indicated by bit 0 of the LPA field in the
Identify Controller data structure.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
