.TH "nvme_status_get_value" 9 "nvme_status_get_value" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_status_get_value \- extract the status value from a nvme_* return value
.SH SYNOPSIS
.B "__u32" nvme_status_get_value
.BI "(int status "  ");"
.SH ARGUMENTS
.IP "status" 12
the (non-negative) return value from the NVMe API
.SH "RETURN"
the value component of the status; the set of values will depend
on the status type.
