.TH "nvme_identify_ns_descs" 9 "nvme_identify_ns_descs" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_identify_ns_descs \- Retrieves namespace descriptor list
.SH SYNOPSIS
.B "int" nvme_identify_ns_descs
.BI "(int fd "  ","
.BI "__u32 nsid "  ","
.BI "struct nvme_ns_id_desc *descs "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
The namespace id to retrieve descriptors
.IP "descs" 12
User space destination address to transfer the data
.SH "DESCRIPTION"
A list of Namespace Identification Descriptor structures is returned to the
host for the namespace specified in the Namespace Identifier (NSID) field if
it is an active NSID.

The data returned is in the form of an array of 'struct nvme_ns_id_desc'.

See \fIstruct nvme_ns_id_desc\fP for the definition of the returned structure.
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise.
