.TH "nvme_subsystem_first_ns" 9 "nvme_subsystem_first_ns" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_first_ns \- Start namespace iterator
.SH SYNOPSIS
.B "nvme_ns_t" nvme_subsystem_first_ns
.BI "(nvme_subsystem_t s "  ");"
.SH ARGUMENTS
.IP "s" 12
nvme_subsystem_t object
.SH "RETURN"
First nvme_ns_t object of an \fIs\fP iterator
