.TH "nvme_free_tree" 9 "nvme_free_tree" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_free_tree \- Free root object
.SH SYNOPSIS
.B "void" nvme_free_tree
.BI "(nvme_root_t r "  ");"
.SH ARGUMENTS
.IP "r" 12
\fInvme_root_t\fP object
.SH "DESCRIPTION"
Free an \fInvme_root_t\fP object and all attached objects
