.TH "libnvme" 9 "enum nvme_ae_info_notice" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_ae_info_notice \- Asynchronous Event Information - Notice
.SH SYNOPSIS
enum nvme_ae_info_notice {
.br
.BI "    NVME_AER_NOTICE_NS_CHANGED"
, 
.br
.br
.BI "    NVME_AER_NOTICE_FW_ACT_STARTING"
, 
.br
.br
.BI "    NVME_AER_NOTICE_TELEMETRY"
, 
.br
.br
.BI "    NVME_AER_NOTICE_ANA"
, 
.br
.br
.BI "    NVME_AER_NOTICE_PL_EVENT"
, 
.br
.br
.BI "    NVME_AER_NOTICE_LBA_STATUS_ALERT"
, 
.br
.br
.BI "    NVME_AER_NOTICE_EG_EVENT"
, 
.br
.br
.BI "    NVME_AER_NOTICE_DISC_CHANGED"

};
.SH Constants
.IP "NVME_AER_NOTICE_NS_CHANGED" 12
Namespace Attribute Changed
.IP "NVME_AER_NOTICE_FW_ACT_STARTING" 12
Firmware Activation Starting
.IP "NVME_AER_NOTICE_TELEMETRY" 12
Telemetry Log Changed
.IP "NVME_AER_NOTICE_ANA" 12
Asymmetric Namespace Access Change
.IP "NVME_AER_NOTICE_PL_EVENT" 12
Predictable Latency Event Aggregate Log Change
.IP "NVME_AER_NOTICE_LBA_STATUS_ALERT" 12
LBA Status Information Alert
.IP "NVME_AER_NOTICE_EG_EVENT" 12
Endurance Group Event Aggregate Log Page Change
.IP "NVME_AER_NOTICE_DISC_CHANGED" 12
Discovery Log Page Change
