.TH "libnvme" 9 "enum nvme_persistent_event_types" "April 2022" "API Manual" LINUX
.SH NAME
enum nvme_persistent_event_types \- 
.SH SYNOPSIS
enum nvme_persistent_event_types {
.br
.BI "    NVME_PEL_SMART_HEALTH_EVENT"
, 
.br
.br
.BI "    NVME_PEL_FW_COMMIT_EVENT"
, 
.br
.br
.BI "    NVME_PEL_TIMESTAMP_EVENT"
, 
.br
.br
.BI "    NVME_PEL_POWER_ON_RESET_EVENT"
, 
.br
.br
.BI "    NVME_PEL_NSS_HW_ERROR_EVENT"
, 
.br
.br
.BI "    NVME_PEL_CHANGE_NS_EVENT"
, 
.br
.br
.BI "    NVME_PEL_FORMAT_START_EVENT"
, 
.br
.br
.BI "    NVME_PEL_FORMAT_COMPLETION_EVENT"
, 
.br
.br
.BI "    NVME_PEL_SANITIZE_START_EVENT"
, 
.br
.br
.BI "    NVME_PEL_SANITIZE_COMPLETION_EVENT"
, 
.br
.br
.BI "    NVME_PEL_SET_FEATURE_EVENT"
, 
.br
.br
.BI "    NVME_PEL_TELEMETRY_CRT"
, 
.br
.br
.BI "    NVME_PEL_THERMAL_EXCURSION_EVENT"

};
.SH Constants
.IP "NVME_PEL_SMART_HEALTH_EVENT" 12
.IP "NVME_PEL_FW_COMMIT_EVENT" 12
.IP "NVME_PEL_TIMESTAMP_EVENT" 12
.IP "NVME_PEL_POWER_ON_RESET_EVENT" 12
.IP "NVME_PEL_NSS_HW_ERROR_EVENT" 12
.IP "NVME_PEL_CHANGE_NS_EVENT" 12
.IP "NVME_PEL_FORMAT_START_EVENT" 12
.IP "NVME_PEL_FORMAT_COMPLETION_EVENT" 12
.IP "NVME_PEL_SANITIZE_START_EVENT" 12
.IP "NVME_PEL_SANITIZE_COMPLETION_EVENT" 12
.IP "NVME_PEL_SET_FEATURE_EVENT" 12
.IP "NVME_PEL_TELEMETRY_CRT" 12
.IP "NVME_PEL_THERMAL_EXCURSION_EVENT" 12
