.TH "nvme_mi_admin_get_log_rotational_media_info" 9 "nvme_mi_admin_get_log_rotational_media_info" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_rotational_media_info \- Retrieve Rotational Media Information Log
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_rotational_media_info
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "__u16 endgid "  ","
.BI "__u32 len "  ","
.BI "struct nvme_rotational_media_info_log *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "endgid" 12
Endurance Group Identifier
.IP "len" 12
The allocated length of the log page
.IP "log" 12
User address to store the log page
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise
