.TH "nvme_ctrl_get_config" 9 "nvme_ctrl_get_config" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_get_config \- Fabrics configuration of a controller
.SH SYNOPSIS
.B "struct nvme_fabrics_config *" nvme_ctrl_get_config
.BI "(nvme_ctrl_t c "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.SH "RETURN"
Fabrics configuration of \fIc\fP
