.TH "nvme_ctrl_for_each_path" 9 "nvme_ctrl_for_each_path" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_ctrl_for_each_path \- Traverse paths
.SH SYNOPSIS
.B "nvme_ctrl_for_each_path
.BI "(c "  ","
.BI "p "  ");"
.SH ARGUMENTS
.IP "c" 12
Controller instance
.IP "p" 12
\fInvme_path_t\fP object
