.TH "libnvme" 9 "enum nvme_nvmset_pl_events" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_nvmset_pl_events \- Predictable Latency Per NVM Set Log - Event Type
.SH SYNOPSIS
enum nvme_nvmset_pl_events {
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_READ_WARN"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_WRITE_WARN"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_TIME_WARN"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_EXCEEDED"
, 
.br
.br
.BI "    NVME_NVMSET_PL_EVENT_DTWIN_EXCURSION"

};
.SH Constants
.IP "NVME_NVMSET_PL_EVENT_DTWIN_READ_WARN" 12
DTWIN Reads Warning
.IP "NVME_NVMSET_PL_EVENT_DTWIN_WRITE_WARN" 12
DTWIN Writes Warning
.IP "NVME_NVMSET_PL_EVENT_DTWIN_TIME_WARN" 12
DTWIN Time Warning
.IP "NVME_NVMSET_PL_EVENT_DTWIN_EXCEEDED" 12
Autonomous transition from DTWIN
to NDWIN due to typical or
maximum value exceeded
.IP "NVME_NVMSET_PL_EVENT_DTWIN_EXCURSION" 12
Autonomous transition from DTWIN
to NDWIN due to Deterministic
Excursion
