.TH "nvme_directive_recv" 2 "nvme_directive_recv" "February 2020" "libnvme Manual"
.SH NAME
nvme_directive_recv \- Receive directive specific data
.SH SYNOPSIS
.B "int" nvme_directive_recv
.BI "(int " fd ","
.BI "__u32 " nsid ","
.BI "__u16 " dspec ","
.BI "enum nvme_directive_receive_doper " doper ","
.BI "enum nvme_directive_dtype " dtype ","
.BI "__u32 " cdw12 ","
.BI "__u32 " data_len ","
.BI "void *" data ","
.BI "__u32 *" result ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "nsid" 12
Namespace ID, if applicable
.IP "dspec" 12
Directive specific field
.IP "doper" 12
Directive receive operation, see \fIenum nvme_directive_receive_doper\fP
.IP "dtype" 12
Directive type, see \fIenum nvme_directive_dtype\fP
.IP "cdw12" 12
-- undescribed --
.IP "data_len" 12
Length of data payload
.IP "data" 12
Usespace address of data payload in bytes
.IP "result" 12
If successful, the CQE dword0 value
.SH "RETURN"
The nvme command status if a response was received or -1 with errno
set otherwise.
