.TH "libnvme" 9 "enum nvme_id_iocs_iocsc" "May 2025" "API Manual" LINUX
.SH NAME
enum nvme_id_iocs_iocsc \- This field indicates the Identify I/O Command Set Data Structure
.SH SYNOPSIS
enum nvme_id_iocs_iocsc {
.br
.BI "    NVME_IOCS_IOCSC_NVMCS_SHIFT"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_NVMCS_MASK"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_KVCS_SHIFT"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_KVCS_MASK"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_ZNSCS_SHIFT"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_ZNSCS_MASK"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_SLMCS_SHIFT"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_SLMCS_MASK"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_CPNCS_SHIFT"
, 
.br
.br
.BI "    NVME_IOCS_IOCSC_CPNCS_MASK"

};
.SH Constants
.IP "NVME_IOCS_IOCSC_NVMCS_SHIFT" 12
Shift amount to get the value of NVM Command Set
.IP "NVME_IOCS_IOCSC_NVMCS_MASK" 12
Mask to get the value of NVM Command Set
.IP "NVME_IOCS_IOCSC_KVCS_SHIFT" 12
Shift amount to get the value of Key Value Command Set
.IP "NVME_IOCS_IOCSC_KVCS_MASK" 12
Mask to get the value of Key Value Command Set
.IP "NVME_IOCS_IOCSC_ZNSCS_SHIFT" 12
Shift amount to get the value of Zoned Namespace Command
Set
.IP "NVME_IOCS_IOCSC_ZNSCS_MASK" 12
Mask to get the value of Zoned Namespace Command Set
.IP "NVME_IOCS_IOCSC_SLMCS_SHIFT" 12
Shift amount to get the value of Subsystem Local Memory
Command Set
.IP "NVME_IOCS_IOCSC_SLMCS_MASK" 12
Mask to get the value of Subsystem Local Memory Command Set
.IP "NVME_IOCS_IOCSC_CPNCS_SHIFT" 12
Shift amount to get the value of Computational Programs
Namespace Command Set
.IP "NVME_IOCS_IOCSC_CPNCS_MASK" 12
Mask to get the value of Computational Programs Namespace
Command Set
