.TH "nvme_path_get_sysfs_dir" 9 "nvme_path_get_sysfs_dir" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_path_get_sysfs_dir \- sysfs directory of an nvme_path_t object
.SH SYNOPSIS
.B "const char *" nvme_path_get_sysfs_dir
.BI "(nvme_path_t p "  ");"
.SH ARGUMENTS
.IP "p" 12
\fInvme_path_t\fP object
.SH "RETURN"
sysfs directory of \fIp\fP
