.TH "libnvme" 9 "enum nvme_zns_recv_action" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_zns_recv_action \- Zone Management Receive - Zone Receive Action Specific Features
.SH SYNOPSIS
enum nvme_zns_recv_action {
.br
.BI "    NVME_ZNS_ZRA_REPORT_ZONES"
, 
.br
.br
.BI "    NVME_ZNS_ZRA_EXTENDED_REPORT_ZONES"

};
.SH Constants
.IP "NVME_ZNS_ZRA_REPORT_ZONES" 12
Report Zones
.IP "NVME_ZNS_ZRA_EXTENDED_REPORT_ZONES" 12
Extended Report Zones
