.TH "libnvme" 9 "struct nvme_id_ctrl_nvm" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_id_ctrl_nvm \- I/O Command Set Specific Identify Controller data structure
.SH SYNOPSIS
struct nvme_id_ctrl_nvm {
.br
.BI "    __u8 vsl;"
.br
.BI "    __u8 wzsl;"
.br
.BI "    __u8 wusl;"
.br
.BI "    __u8 dmrl;"
.br
.BI "    __u32 dmrsl;"
.br
.BI "    __u64 dmsl;"
.br
.BI "    __u8 rsvd16[4080];"
.br
.BI "
};
.br

.SH Members
.IP "vsl" 12
Verify Size Limit
.IP "wzsl" 12
Write Zeroes Size Limit
.IP "wusl" 12
Write Uncorrectable Size Limit
.IP "dmrl" 12
Dataset Management Ranges Limit
.IP "dmrsl" 12
Dataset Management Range Size Limit
.IP "dmsl" 12
Dataset Management Size Limit
.IP "rsvd16" 12
reserved
