.TH "nvme_first_host" 9 "nvme_first_host" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_first_host \- Start host iterator
.SH SYNOPSIS
.B "nvme_host_t" nvme_first_host
.BI "(nvme_root_t r "  ");"
.SH ARGUMENTS
.IP "r" 12
\fInvme_root_t\fP object
.SH "RETURN"
First \fInvme_host_t\fP object in an iterator
