.TH "nvme_for_each_subsystem_safe" 9 "nvme_for_each_subsystem_safe" "February 2022" "libnvme API manual" LINUX
.SH NAME
nvme_for_each_subsystem_safe \- Traverse subsystems
.SH SYNOPSIS
.B "nvme_for_each_subsystem_safe
.BI "(h "  ","
.BI "s "  ","
.BI "_s "  ");"
.SH ARGUMENTS
.IP "h" 12
nvme_host_t object
.IP "s" 12
nvme_subsystem_t object
.IP "_s" 12
temporary nvme_subsystem_t object
