.TH "nvme_mi_admin_get_log_dispersed_ns_participating_nss" 9 "nvme_mi_admin_get_log_dispersed_ns_participating_nss" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvme_mi_admin_get_log_dispersed_ns_participating_nss \- Retrieve Dispersed Namespace Participating NVM Subsystems Log
.SH SYNOPSIS
.B "int" nvme_mi_admin_get_log_dispersed_ns_participating_nss
.BI "(nvme_mi_ctrl_t ctrl "  ","
.BI "__u32 nsid "  ","
.BI "__u32 len "  ","
.BI "struct nvme_dispersed_ns_participating_nss_log *log "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller to query
.IP "nsid" 12
Namespace Identifier
.IP "len" 12
The allocated length of the log page
.IP "log" 12
User address to store the log page
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise
