.TH "nvme_subsystem_reset" 9 "nvme_subsystem_reset" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_subsystem_reset \- Initiate a subsystem reset
.SH SYNOPSIS
.B "int" nvme_subsystem_reset
.BI "(int fd "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.SH "DESCRIPTION"
This should only be sent to controller handles, not to namespaces.
.SH "RETURN"
Zero if a subsystem reset was initiated or -1 with errno set
otherwise.
