.TH "nvme_get_log_boot_partition" 9 "nvme_get_log_boot_partition" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_get_log_boot_partition \- Retrieve Boot Partition
.SH SYNOPSIS
.B "int" nvme_get_log_boot_partition
.BI "(int fd "  ","
.BI "bool rae "  ","
.BI "__u8 lsp "  ","
.BI "__u32 len "  ","
.BI "struct nvme_boot_partition *part "  ");"
.SH ARGUMENTS
.IP "fd" 12
File descriptor of nvme device
.IP "rae" 12
Retain asynchronous events
.IP "lsp" 12
The log specified field of LID
.IP "len" 12
The allocated size, minimum
struct nvme_boot_partition
.IP "part" 12
User address to store the log page
.SH "RETURN"
The nvme command status if a response was received (see
\fIenum nvme_status_field\fP) or -1 with errno set otherwise
