.TH "libnvme" 9 "enum nvme_ae_info_css_nvm" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_ae_info_css_nvm \- Asynchronous Event Information - I/O Command Specific Status
.SH SYNOPSIS
enum nvme_ae_info_css_nvm {
.br
.BI "    NVME_AER_CSS_NVM_RESERVATION"
, 
.br
.br
.BI "    NVME_AER_CSS_NVM_SANITIZE_COMPLETED"
, 
.br
.br
.BI "    NVME_AER_CSS_NVM_UNEXPECTED_SANITIZE_DEALLOC"

};
.SH Constants
.IP "NVME_AER_CSS_NVM_RESERVATION" 12
Reservation Log Page Available
.IP "NVME_AER_CSS_NVM_SANITIZE_COMPLETED" 12
Sanitize Operation Completed
.IP "NVME_AER_CSS_NVM_UNEXPECTED_SANITIZE_DEALLOC" 12
Sanitize Operation Completed
With Unexpected Deallocation
