.TH "nvme_init_copy_range_f1" 9 "nvme_init_copy_range_f1" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvme_init_copy_range_f1 \- Constructs a copy range f1 structure
.SH SYNOPSIS
.B "void" nvme_init_copy_range_f1
.BI "(struct nvme_copy_range_f1 *copy "  ","
.BI "__u16 *nlbs "  ","
.BI "__u64 *slbas "  ","
.BI "__u64 *eilbrts "  ","
.BI "__u32 *elbatms "  ","
.BI "__u32 *elbats "  ","
.BI "__u16 nr "  ");"
.SH ARGUMENTS
.IP "copy" 12
Copy range array
.IP "nlbs" 12
Number of logical blocks
.IP "slbas" 12
Starting LBA
.IP "eilbrts" 12
Expected initial logical block reference tag
.IP "elbatms" 12
Expected logical block application tag mask
.IP "elbats" 12
Expected logical block application tag
.IP "nr" 12
Number of descriptors to construct
