.TH "libnvme" 9 "struct nvme_mi_osc" "January 2023" "API Manual" LINUX
.SH NAME
struct nvme_mi_osc \- Optionally Supported Command Data Structure
.SH SYNOPSIS
struct nvme_mi_osc {
.br
.BI "    __u8 type;"
.br
.BI "    __u8 opc;"
.br
.BI "
};
.br

.SH Members
.IP "type" 12
Command Type
.IP "opc" 12
Opcode
