.TH "libnvme" 9 "enum nvme_nvm_id_ns_elbaf" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_nvm_id_ns_elbaf \- This field indicates the extended LBA format
.SH SYNOPSIS
enum nvme_nvm_id_ns_elbaf {
.br
.BI "    NVME_NVM_ELBAF_STS_MASK"
, 
.br
.br
.BI "    NVME_NVM_ELBAF_PIF_MASK"

};
.SH Constants
.IP "NVME_NVM_ELBAF_STS_MASK" 12
Mask to get the storage tag size used to determine
the variable-sized storage tag/reference tag fields
.IP "NVME_NVM_ELBAF_PIF_MASK" 12
Mask to get the protection information format for
the extended LBA format.
