.TH "libnvme" 9 "enum nvme_id_ctrl_fcatt" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_id_ctrl_fcatt \- This field indicates attributes of the controller that are specific to NVMe over Fabrics.
.SH SYNOPSIS
enum nvme_id_ctrl_fcatt {
.br
.BI "    NVME_CTRL_FCATT_DYNAMIC"

};
.SH Constants
.IP "NVME_CTRL_FCATT_DYNAMIC" 12
If cleared, then the NVM subsystem uses a dynamic
controller model. If set, then the NVM subsystem
uses a static controller model.
