.TH "libnvme" 9 "enum nvme_fdp_supported_event_attributes" "January 2023" "API Manual" LINUX
.SH NAME
enum nvme_fdp_supported_event_attributes \- Supported FDP Event Attributes
.SH SYNOPSIS
enum nvme_fdp_supported_event_attributes {
.br
.BI "    NVME_FDP_SUPP_EVENT_ENABLED_SHIFT"
, 
.br
.br
.BI "    NVME_FDP_SUPP_EVENT_ENABLED_MASK"

};
.SH Constants
.IP "NVME_FDP_SUPP_EVENT_ENABLED_SHIFT" 12
FDP Event Enable Shift
.IP "NVME_FDP_SUPP_EVENT_ENABLED_MASK" 12
FDP Event Enable Mask
