.TH "libnvme" 9 "enum nvmf_exattype" "January 2023" "API Manual" LINUX
.SH NAME
enum nvmf_exattype \- Extended Attribute Type
.SH SYNOPSIS
enum nvmf_exattype {
.br
.BI "    NVMF_EXATTYPE_HOSTID"
, 
.br
.br
.BI "    NVMF_EXATTYPE_SYMNAME"

};
.SH Constants
.IP "NVMF_EXATTYPE_HOSTID" 12
Host Identifier
.IP "NVMF_EXATTYPE_SYMNAME" 12
Symblic Name
