.TH "libnvme" 9 "enum nvmf_rdma_cms" "January 2023" "API Manual" LINUX
.SH NAME
enum nvmf_rdma_cms \- RDMA Connection Management Service Type codes for Discovery Log Page entry TSAS RDMA_CMS field
.SH SYNOPSIS
enum nvmf_rdma_cms {
.br
.BI "    NVMF_RDMA_CMS_RDMA_CM"

};
.SH Constants
.IP "NVMF_RDMA_CMS_RDMA_CM" 12
Sockets based endpoint addressing
