.TH "nvmf_get_discovery_log" 2 "nvmf_get_discovery_log" "February 2020" "libnvme Manual"
.SH NAME
nvmf_get_discovery_log \- 
.SH SYNOPSIS
.B "int" nvmf_get_discovery_log
.BI "(nvme_ctrl_t " c ","
.BI "struct nvmf_discovery_log **" logp ","
.BI "int " max_retries ");"
.SH ARGUMENTS
.IP "c" 12
-- undescribed --
.IP "logp" 12
-- undescribed --
.IP "max_retries" 12
-- undescribed --
