.TH "nvmf_prtype_str" 9 "nvmf_prtype_str" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvmf_prtype_str \- Decode RDMA Provider type field
.SH SYNOPSIS
.B "const char *" nvmf_prtype_str
.BI "(__u8 prtype "  ");"
.SH ARGUMENTS
.IP "prtype" 12
value to be decoded
.SH "DESCRIPTION"
Decode the RDMA Provider type field in the discovery
log page entry.
.SH "RETURN"
decoded string
