.TH "libnvme" 9 "enum nvmf_dim_etype" "January 2023" "API Manual" LINUX
.SH NAME
enum nvmf_dim_etype \- Discovery Information Management Entity Type
.SH SYNOPSIS
enum nvmf_dim_etype {
.br
.BI "    NVMF_DIM_ETYPE_HOST"
, 
.br
.br
.BI "    NVMF_DIM_ETYPE_DDC"
, 
.br
.br
.BI "    NVMF_DIM_ETYPE_CDC"

};
.SH Constants
.IP "NVMF_DIM_ETYPE_HOST" 12
Host
.IP "NVMF_DIM_ETYPE_DDC" 12
Direct Discovery controller
.IP "NVMF_DIM_ETYPE_CDC" 12
Centralized Discovery controller
