.TH "nvmf_hostid_from_file" 9 "nvmf_hostid_from_file" "May 2025" "libnvme API manual" LINUX
.SH NAME
nvmf_hostid_from_file \- Reads the host identifier from the config default location
.SH SYNOPSIS
.B "char *" nvmf_hostid_from_file
.SH ARGUMENTS
.SH "DESCRIPTION"

Retrieve the host idenditifer from the config file located in $SYSCONFDIR/nvme/.
$SYSCONFDIR is usually /etc.
.SH "RETURN"
The host identifier, or NULL if unsuccessful. If found, the caller
is responsible to free the string.
