.TH "libnvme" 9 "enum nvmf_rdma_qptype" "January 2023" "API Manual" LINUX
.SH NAME
enum nvmf_rdma_qptype \- RDMA QP Service Type codes for Discovery Log Page entry TSAS RDMA_QPTYPE field
.SH SYNOPSIS
enum nvmf_rdma_qptype {
.br
.BI "    NVMF_RDMA_QPTYPE_CONNECTED"
, 
.br
.br
.BI "    NVMF_RDMA_QPTYPE_DATAGRAM"

};
.SH Constants
.IP "NVMF_RDMA_QPTYPE_CONNECTED" 12
Reliable Connected
.IP "NVMF_RDMA_QPTYPE_DATAGRAM" 12
Reliable Datagram
