.TH "nvmf_hostnqn_from_file" 9 "nvmf_hostnqn_from_file" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvmf_hostnqn_from_file \- Reads the host nvm qualified name from the config default location in /usr/local/etc/nvme/
.SH SYNOPSIS
.B "char *" nvmf_hostnqn_from_file
.SH ARGUMENTS
.SH "RETURN"
The host nqn, or NULL if unsuccessful. If found, the caller
is responsible to free the string.
