.TH "libnvme" 9 "enum nvmf_dim_tas" "January 2023" "API Manual" LINUX
.SH NAME
enum nvmf_dim_tas \- Discovery Information Management Task
.SH SYNOPSIS
enum nvmf_dim_tas {
.br
.BI "    NVMF_DIM_TAS_REGISTER"
, 
.br
.br
.BI "    NVMF_DIM_TAS_DEREGISTER"
, 
.br
.br
.BI "    NVMF_DIM_TAS_UPDATE"

};
.SH Constants
.IP "NVMF_DIM_TAS_REGISTER" 12
Register
.IP "NVMF_DIM_TAS_DEREGISTER" 12
Deregister
.IP "NVMF_DIM_TAS_UPDATE" 12
Update
