.TH "nvmf_connect_disc_entry" 2 "nvmf_connect_disc_entry" "February 2020" "libnvme Manual"
.SH NAME
nvmf_connect_disc_entry \- 
.SH SYNOPSIS
.B "nvme_ctrl_t" nvmf_connect_disc_entry
.BI "(struct nvmf_disc_log_entry *" e ","
.BI "const struct nvme_fabrics_config *" defcfg ","
.BI "bool *" discover ");"
.SH ARGUMENTS
.IP "e" 12
-- undescribed --
.IP "defcfg" 12
-- undescribed --
.IP "discover" 12
-- undescribed --
