.TH "nvmf_default_config" 9 "nvmf_default_config" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvmf_default_config \- Default values for fabrics configuration
.SH SYNOPSIS
.B "void" nvmf_default_config
.BI "(struct nvme_fabrics_config *cfg "  ");"
.SH ARGUMENTS
.IP "cfg" 12
config values to set
.SH "DESCRIPTION"
Initializes \fIcfg\fP with default values.
