.TH "nvmf_get_discovery_log" 9 "nvmf_get_discovery_log" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvmf_get_discovery_log \- Return the discovery log page
.SH SYNOPSIS
.B "int" nvmf_get_discovery_log
.BI "(nvme_ctrl_t c "  ","
.BI "struct nvmf_discovery_log **logp "  ","
.BI "int max_retries "  ");"
.SH ARGUMENTS
.IP "c" 12
Discovery controller to use
.IP "logp" 12
Pointer to the log page to be returned
.IP "max_retries" 12
Number of retries in case of failure
.SH "DESCRIPTION"
The memory allocated for the log page and returned in \fIlogp\fP
must be freed by the caller using \fBfree\fP.
.SH "NOTE"
Consider using \fBnvmf_get_discovery_wargs\fP instead.
.SH "RETURN"
0 on success; on failure -1 is returned and errno is set
