.TH "nvmf_hostnqn_generate" 9 "nvmf_hostnqn_generate" "January 2023" "libnvme API manual" LINUX
.SH NAME
nvmf_hostnqn_generate \- Generate a machine specific host nqn
.SH SYNOPSIS
.B "char *" nvmf_hostnqn_generate
.SH ARGUMENTS
.SH "RETURN"
An nvm namespace qualified name string based on the machine
identifier, or NULL if not successful.
