.TH "libnvme" 9 "enum nvmf_dim_entfmt" "January 2023" "API Manual" LINUX
.SH NAME
enum nvmf_dim_entfmt \- Discovery Information Management Entry Format
.SH SYNOPSIS
enum nvmf_dim_entfmt {
.br
.BI "    NVMF_DIM_ENTFMT_BASIC"
, 
.br
.br
.BI "    NVMF_DIM_ENTFMT_EXTENDED"

};
.SH Constants
.IP "NVMF_DIM_ENTFMT_BASIC" 12
Basic discovery information entry
.IP "NVMF_DIM_ENTFMT_EXTENDED" 12
Extended discovery information entry
