.TH "libnvme" 2 "struct nvme_mi_vpd_mra" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_mra \-  @nmravn; @ff; @i18vpwr; @m18vpwr; @i33vpwr; @m33vpwr; @m33vapsr; @i5vapsr; @m5vapsr; @i12vapsr; @m12vapsr; @mtl; @tnvmcap[16];
.SH SYNOPSIS
struct nvme_mi_vpd_mra {
.br
.BI "    __u8 nmravn;"
.br
.BI "    __u8 ff;"
.br
.BI "    __u8 rsvd7[6];"
.br
.BI "    __u8 i18vpwr;"
.br
.BI "    __u8 m18vpwr;"
.br
.BI "    __u8 i33vpwr;"
.br
.BI "    __u8 m33vpwr;"
.br
.BI "    __u8 rsvd17;"
.br
.BI "    __u8 m33vapsr;"
.br
.BI "    __u8 i5vapsr;"
.br
.BI "    __u8 m5vapsr;"
.br
.BI "    __u8 i12vapsr;"
.br
.BI "    __u8 m12vapsr;"
.br
.BI "    __u8 mtl;"
.br
.BI "    __u8 tnvmcap[16];"
.br
.BI "    __u8 rsvd37[27];"
.br
.BI "
};
.br

.SH Members
