.TH "libnvme" 2 "struct nvme_mi_port_smb" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_mi_port_smb \- 
.SH SYNOPSIS
struct nvme_mi_port_smb {
.br
.BI "    __u8 vpd_addr;"
.br
.BI "    __u8 mvpd_freq;"
.br
.BI "    __u8 mme_addr;"
.br
.BI "    __u8 mme_freq;"
.br
.BI "    __u8 nvmebm;"
.br
.BI "    __u8 rsvd13[19];"
.br
.BI "
};
.br

.SH Members
