.TH "libnvme" 2 "struct nvme_mi_vpd_hdr" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_hdr \- 
.SH SYNOPSIS
struct nvme_mi_vpd_hdr {
.br
.BI "    __u8 ipmiver;"
.br
.BI "    __u8 iuaoff;"
.br
.BI "    __u8 ciaoff;"
.br
.BI "    __u8 biaoff;"
.br
.BI "    __u8 piaoff;"
.br
.BI "    __u8 mrioff;"
.br
.BI "    __u8 rsvd6;"
.br
.BI "    __u8 chchk;"
.br
.BI "    __u8 vpd[];"
.br
.BI "
};
.br

.SH Members
