.TH "libnvme" 2 "struct nvme_resv_notification_log" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_resv_notification_log \- 
.SH SYNOPSIS
struct nvme_resv_notification_log {
.br
.BI "    __le64 lpc;"
.br
.BI "    __u8 rnlpt;"
.br
.BI "    __u8 nalp;"
.br
.BI "    __u8 rsvd9[2];"
.br
.BI "    __le32 nsid;"
.br
.BI "    __u8 rsvd16[48];"
.br
.BI "
};
.br

.SH Members
