.TH "libnvme" 2 "struct nvme_mi_vpd_tra" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_tra \- 
.SH SYNOPSIS
struct nvme_mi_vpd_tra {
.br
.BI "    __u8 vn;"
.br
.BI "    __u8 rsvd6;"
.br
.BI "    __u8 ec;"
.br
.BI "    struct nvme_mi_vpd_telem elems[0];"
.br
.BI "
};
.br

.SH Members
