.TH "libnvme" 2 "struct nvme_mi_vpd_ppmra" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_mi_vpd_ppmra \- 
.SH SYNOPSIS
struct nvme_mi_vpd_ppmra {
.br
.BI "    __u8 nppmravn;"
.br
.BI "    __u8 pn;"
.br
.BI "    __u8 ppi;"
.br
.BI "    __u8 ls;"
.br
.BI "    __u8 mlw;"
.br
.BI "    __u8 mctp;"
.br
.BI "    __u8 refccap;"
.br
.BI "    __u8 pi;"
.br
.BI "    __u8 rsvd13[3];"
.br
.BI "
};
.br

.SH Members
