.TH "libnvme" 2 "struct nvme_aggregate_endurance_group_event" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_aggregate_endurance_group_event \- 
.SH SYNOPSIS
struct nvme_aggregate_endurance_group_event {
.br
.BI "    __le64 num_entries;"
.br
.BI "    __le16 entries[];"
.br
.BI "
};
.br

.SH Members
