.TH "libnvme" 2 "struct nvme_id_ns_granularity_desc" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_id_ns_granularity_desc \- 
.SH SYNOPSIS
struct nvme_id_ns_granularity_desc {
.br
.BI "    __le64 namespace_size_granularity;"
.br
.BI "    __le64 namespace_capacity_granularity;"
.br
.BI "
};
.br

.SH Members
