.TH "libnvme" 2 "struct nvme_mi_read_nvm_ss_info" "February 2020" "LIBNVME API Manual" LINUX
.SH NAME
struct nvme_mi_read_nvm_ss_info \- 
.SH SYNOPSIS
struct nvme_mi_read_nvm_ss_info {
.br
.BI "    __u8 nump;"
.br
.BI "    __u8 mjr;"
.br
.BI "    __u8 mnr;"
.br
.BI "    __u8 rsvd3[29];"
.br
.BI "
};
.br

.SH Members
