'\" t
.\"     Title: nvme-compare
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-COMPARE" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-compare \- Send an NVMe Compare command, provide results
.SH "SYNOPSIS"
.sp
.nf
\fInvme\-compare\fR <device> [\-\-start\-block=<slba> | \-s <slba>]
                        [\-\-block\-count=<nlb> | \-c <nlb>]
                        [\-\-data\-size=<size> | \-z <size>]
                        [\-\-ref\-tag=<reftag> | \-r <reftag>]
                        [\-\-data=<data\-file> | \-d <data\-file>]
                        [\-\-prinfo=<prinfo> | \-p <prinfo>]
                        [\-\-app\-tag\-mask=<appmask> | \-m <appmask>]
                        [\-\-app\-tag=<apptag> | \-a <apptag>]
                        [\-\-limited\-retry | \-l]
                        [\-\-force\-unit\-access | \-f]
.fi
.SH "DESCRIPTION"
.sp
The Compare command reads the logical blocks specified by the command from the medium and compares the data read to a comparison data buffer transferred as part of the command\&. If the data read from the controller and the comparison data buffer are equivalent with no miscompares, then the command completes successfully\&. If there is any miscompare, the command completes with an error of Compare Failure\&. If metadata is provided, then a comparison is also performed for the metadata\&.
.SH "OPTIONS"
.PP
\-\-start\-block=<slba>, \-s <slba>
.RS 4
Start block\&.
.RE
.SH "EXAMPLES"
.sp
No examples yet\&.
.SH "NVME"
.sp
Part of the nvme\-user suite
