'\" t
.\"     Title: nvme-nvme-mi-recv
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/20/2025
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-NVME\-MI\-RECV" "1" "05/20/2025" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-nvme-mi-recv \- Send a NVMe\-MI Receive command to the specified device
.SH "SYNOPSIS"
.sp
.nf
\fInvme nvme\-mi\-recv\fR <device> [\-\-opcode=<opcode> | \-O <opcode>]
                        [\-\-namespace\-id=<nsid> | \-n <nsid>]
                        [\-\-data\-len=<data\-len> | \-l <data\-len>]
                        [\-\-nmimt=<nmimt> | \-m <nmimt>]
                        [\-\-nmd0=<nmd0> | \-0 <nmd0>] [\-\-nmd1=<nmd1> | \-1 <nmd1>]
                        [\-\-input\-file=<file> | \-i <file>]
                        [\-\-output\-format=<fmt> | \-o <fmt>] [\-\-verbose | \-v]
.fi
.SH "DESCRIPTION"
.sp
Send a NVMe\-MI Receive command to the specified device, return results\&.
.sp
The <device> parameter is mandatory and may be either the NVMe character device (ex: /dev/nvme0) or block device (ex: /dev/nvme0n1)\&.
.sp
On success it returns 0, error code otherwise\&.
.SH "OPTIONS"
.PP
\-O <opcode>, \-\-opcode=<opcode>
.RS 4
The NVMe\-MI opcode to send to the device in the command Required argument as this param is mandatory\&.
.RE
.PP
\-n <nsid>, \-\-namespace\-id=<nsid>
.RS 4
The value for the ns\-id in the command\&.
.RE
.PP
\-l <data\-len>, \-\-data\-len=<data\-len>
.RS 4
The data length for the buffer used for this command\&.
.RE
.PP
\-m <nmimt>, \-\-nmimt=<nmimt>
.RS 4
The value for the NVMe\-MI message type in the command\&.
.RE
.PP
\-0 <nmd0>, \-\-nmd0=<nmd0>
.RS 4
The value for the NVMe management request dword 0 in the command\&.
.RE
.PP
\-1 <nmd1>, \-\-nmd1=<nmd1>
.RS 4
The value for the NVMe management request dword 1 in the command\&.
.RE
.PP
\-i <file>, \-\-input\-file=<file>
.RS 4
If the command is a data\-out (write) command, use this file to fill the buffer sent to the device\&. If no file is given, assumed to use STDIN\&.
.RE
.PP
\-o <fmt>, \-\-output\-format=<fmt>
.RS 4
Set the reporting format to
\fInormal\fR,
\fIjson\fR
or
\fIbinary\fR\&. Only one output format can be used at a time\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Increase the information detail in the output\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Has the program issue a nvme\-mi\-recv to execute the VPD read\&.
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme nvme\-mi\-recv /dev/nvme0n1 \-O 5 \-m 1 \-0 0 \-1 0x100 \-l 256
.fi
.if n \{\
.RE
.\}
.RE
.SH "NVME"
.sp
Part of the nvme\-user suite\&.
