'\" t
.\"     Title: nvme-lnvm-diag-bbtbl
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-LNVM\-DIAG\-BB" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-diag-bbtbl \- Diagnose the bad block table
.SH "SYNOPSIS"
.sp
.nf
\fInvme lnvm\-diag\-bbtbl\fR [\-\-namespace\-id=<NUM> | \-n <NUM>]
                        [\-\-channel\-id=<CHID> | \-c <CHID>]
                        [\-\-lun\-id=<LUNID> | \-l <LUNID>]
                        [\-\-raw\-binary | \-b]
.fi
.SH "DESCRIPTION"
.sp
Retrieve the bad block table for a given channel and lun\&.
.sp
The statistics will be shown in the default case, and the actual output bad block information can be retrieved when \-\-raw\-binary is passed\&.
.sp
The raw binary output follows this format:
.sp
Channel 0, LUN0 (Dual plane flash)
.sp
Byte 0 \(-> Plane 0, Block 0 Byte 1 \(-> Plane 1, Block 0 Byte 2 \(-> Plane 0, Block 1 \&...
.SH "OPTIONS"
.PP
\-\-namespace\-id=<NUM>, \-n <NUM>
.RS 4
Namespace id to use
.RE
.PP
\-\-channel\-id=<NUM>, \-c
.RS 4
Channel id
.RE
.PP
\-\-lun\-id=<NUM>, \-l
.RS 4
LUN id
.RE
.PP
\-\-raw\-binary, \-b
.RS 4
Returns the bad block table in binary form without statistics\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Retrieve bad block table statistics for physical device nvme0, channel 0, and lun 0:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-diag\-bbtbl /dev/nvme0 \-c 0 \-n 0
.fi
.if n \{\
.RE
.\}
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Display the bad block table in raw form without statistics for same query:
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-diag\-bbtbl /dev/nvme0 \-c 0 \-n 0 \-b | hexdump
.fi
.if n \{\
.RE
.\}
.SH "NVME"
.sp
Part of the nvme\-user suite
