'\" t
.\"     Title: nvme-lnvm-create
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-LNVM\-CREATE" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-create \- Instantiate a target on top of a LightNVM enabled device
.SH "SYNOPSIS"
.sp
.nf
\fInvme lnvm\-create\fR [\-\-device\-name=<DEVICE> | \-d <DEVICE>]
                        [\-\-target\-name=<TARGET> | \-n <TARGET>]
                        [\-\-target\-type=<TARGETTYPE> | \-t <TARGETTYPE>]
                        [\-\-lun\-begin <NUM> | \-b <NUM>]
                        [\-\-lun\-end <NUM> | \-e <NUM>]
.fi
.SH "DESCRIPTION"
.sp
Instantiate a target on top of a LightNVM enabled device\&. This exposes the physical for the user to use\&.
.sp
The target name is the name of which the media is exposed as in /dev/<targetname>
.sp
The target type is the target to be instantiated\&. Typically pblk or rrpc\&.
.sp
LUN begin and end defines the range of LUNs to use for a target instantiation\&.
.SH "OPTIONS"
.PP
\-\-device\-name=<DEVICE>, \-d <DEVICE>
.RS 4
Device name to initialize\&.
.RE
.PP
\-\-target\-name=<TARGET>, \-n <TARGET>
.RS 4
Target name of the device to initialize\&. For example: target0\&.
.RE
.PP
\-\-target\-type=<TARGETTYPE>, \-t <TARGETTYPE>
.RS 4
Target type of the device to use\&. For example: pblk
.RE
.PP
\-\-lun\-begin <NUM>, \-b <NUM>
.RS 4
Begin LUN id offset to use for target
.RE
.PP
\-\-lun\-end <NUM>, \-e <NUM>
.RS 4
End LUN id offset to use for target
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Initialize nvme0n1 with pblk target with 64 LUNs\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-create \-d nvme0n1 \-t pblk \-n target0 \-b 0 \-e 63
.fi
.if n \{\
.RE
.\}
.SH "NVME"
.sp
Part of the nvme\-user suite
