'\" t
.\"     Title: nvme-lnvm-init
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-LNVM\-INIT" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-init \- Initialize LightNVM device with media manager
.SH "SYNOPSIS"
.sp
.nf
\fInvme lnvm\-init\fR [\-\-device\-name=<DEVICE> | \-d <DEVICE>]
                        [\-\-mediamgr\-name | \-m]
.fi
.SH "DESCRIPTION"
.sp
Initialize LightNVM device\&. A LightNVM/Open\-Channel SSD must have a media manager associated before it can be exposed to the user\&. The default is to initialize the general media manager on top of the device\&.
.SH "OPTIONS"
.PP
\-\-device\-name=<DEVICE>, \-d <DEVICE>
.RS 4
Device name to initialize\&.
.RE
.PP
\-\-mediamgr\-name=<MediaMgr>, \-m <MediaMgr>
.RS 4
Media Manager name to use for initialization\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Initialize nvme0n1
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-init \-d nvme0n1
.fi
.if n \{\
.RE
.\}
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Initialize nvme0n1 with gennvm media manager (default media manager)
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-init \-d nvme0n1 \-m gennvm
.fi
.if n \{\
.RE
.\}
.SH "NVME"
.sp
Part of the nvme\-user suite
