'\" t
.\"     Title: nvme-wdc-vs-telemetry-controller-option
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/20/2020
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-WDC\-VS\-TELEM" "1" "10/20/2020" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-wdc-vs-telemetry-controller-option \- Disable/Enable the controller initiated option of the telemetry log page\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme wdc vs\-telemetry\-controller\-option\fR <device> [\-\-disable, \-d] [\-\-enable, \-e]
    [\-\-status, \-s]
.fi
.SH "DESCRIPTION"
.sp
For the NVMe device given, sends the WDC Vendor Specific set feature command to disable, enable or get current status of the controller initiated option of the telemetry log page\&.
.sp
The <device> parameter is mandatory NVMe character device (ex: /dev/nvme0)\&.
.sp
This will only work on WDC devices supporting this feature\&. Results for any other device are undefined\&.
.SH "OPTIONS"
.PP
\-d, \-\-disable
.RS 4
Disables the controller initiated option of the telemetry log page\&.
.RE
.PP
\-e, \-\-enable
.RS 4
Enables the controller initiated option of the telemetry log page\&.
.RE
.PP
\-s, \-\-status
.RS 4
Returns the current status (enabled or disabled) of the controller initiated option of the telemetry log page\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Disables the controller initiated option of the telemetry log page:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc vs\-telemetry\-controller\-option /dev/nvme0 \-\-disable
# nvme wdc vs\-telemetry\-controller\-option /dev/nvme0 \-d
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Enables the controller initiated option of the telemetry log page:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc vs\-telemetry\-controller\-option /dev/nvme0 \-\-enable
# nvme wdc vs\-telemetry\-controller\-option /dev/nvme0 \-e
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gets the current status (enabled or disabled) of the controller initiated option of the telemetry log page:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc vs\-telemetry\-controller\-option /dev/nvme0 \-\-status
# nvme wdc vs\-telemetry\-controller\-option /dev/nvme0 \-s
.fi
.if n \{\
.RE
.\}
.RE
.SH "NVME"
.sp
Part of the nvme\-user suite\&.
