'\" t
.\"     Title: nvme-wdc-drive-essentials
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/20/2020
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-WDC\-DRIVE\-ES" "1" "10/20/2020" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-wdc-drive-essentials \- Retrieve WDC device\*(Aqs drive essentials bin files and save to a tar file\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme wdc drive\-essentials\fR <device> [\-\-dir\-name=<DIRECTORY>, \-d <DIRECTORY>]
.fi
.SH "DESCRIPTION"
.sp
For the NVMe device given, captures the drive essential bin files and saves them into a tar file\&. The tar file will be in the following format: DRIVE_ESSENTIALS_<Serial Num>_<FW Revision>_<Date>_<Time>\&.tar\&.gz e\&.g\&. DRIVE_ESSENTIALS_A00FD8CA_1048_20170713_091731\&.tar\&.gz
.sp
The <device> parameter is mandatory; NVMe character device (ex: /dev/nvme0)\&.
.sp
This will only work on WDC devices supporting this feature\&. Results for any other device are undefined\&.
.SH "OPTIONS"
.PP
\-d <DIRECTORY>, \-\-dir\-name=<DIRECTORY>
.RS 4
Output directory; defaults to current working directory\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gets the drive essentials data files from the device and saves the tar file in current directory (e\&.g\&. DRIVE_ESSENTIALS_A00FD8CA_1048_20170713_091731\&.tar\&.gz):
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc drive\-essentials /dev/nvme0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gets the drive essentials data files from the device and saves the tar file to specified directory (e\&.g\&. /tmp/DRIVE_ESSENTIALS_A00FD8CA_1048_20170713_091731):
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme wdc drive\-essentials /dev/nvme0 \-d /tmp/
.fi
.if n \{\
.RE
.\}
.RE
.SH "NVME"
.sp
Part of the nvme\-user suite\&.
