'\" t
.\"     Title: nvme
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme \- the dumb pci\-e storage utility
.SH "SYNOPSIS"
.sp
.nf
\fInvme\fR <command> <device> [<args>]
.fi
.SH "DESCRIPTION"
.sp
NVM\-Express is a fast, scalable host controller interface designed to address the needs for PCI Express based solid state drives\&.
.sp
This \fInvme\fR program is a user space utility to provide standards compliant tooling for NVM\-Express drives\&. It was made specifically for Linux as it relies on the IOCTLs defined by the mainline kernel driver\&.
.SH "NVME COMMANDS"
.sp
The utility has sub\-commands for all admin and io commands defined in the specification and for displaying controller registers\&. There is also an option to submit completely arbitrary commands\&. For a list of commands available, run "nvme help"\&.
.SH "NVME CLI SUB-COMMANDS"
.SS "Main commands"
.PP
\fBnvme-admin-passthru\fR(1)
.RS 4
Admin Passthrough Command
.RE
.PP
\fBnvme-compare\fR(1)
.RS 4
IO Compare
.RE
.PP
\fBnvme-error-log\fR(1)
.RS 4
Retrieve error logs
.RE
.PP
\fBnvme-flush\fR(1)
.RS 4
Submit flush
.RE
.PP
\fBnvme-dms\fR(1)
.RS 4
Submit Data Set Management
.RE
.PP
\fBnvme-format\fR(1)
.RS 4
Format namespace(s)
.RE
.PP
\fBnvme-fw-activate\fR(1)
.RS 4
F/W Activate
.RE
.PP
\fBnvme-fw-download\fR(1)
.RS 4
F/W Download
.RE
.PP
\fBnvme-fw-log\fR(1)
.RS 4
Retrieve f/w log
.RE
.PP
\fBnvme-get-feature\fR(1)
.RS 4
Get Features
.RE
.PP
\fBnvme-get-log\fR(1)
.RS 4
Generic Get Log
.RE
.PP
\fBnvme-smart-log\fR(1)
.RS 4
Retrieve Smart Log
.RE
.PP
\fBnvme-get-ns-id\fR(1)
.RS 4
Retrieve namespace identifier
.RE
.PP
\fBnvme-help\fR(1)
.RS 4
NVMe CLI Help
.RE
.PP
\fBnvme-id-ctrl\fR(1)
.RS 4
Identify Controller
.RE
.PP
\fBnvme-id-ns\fR(1)
.RS 4
Identify Namespace
.RE
.PP
\fBnvme-create-ns\fR(1)
.RS 4
Create a new namespace
.RE
.PP
\fBnvme-delete-ns\fR(1)
.RS 4
Delete existing namespace
.RE
.PP
\fBnvme-attach-ns\fR(1)
.RS 4
Attach namespace
.RE
.PP
\fBnvme-detach-ns\fR(1)
.RS 4
Detach namespace
.RE
.PP
\fBnvme-io-passthru\fR(1)
.RS 4
IO Passthrough Command
.RE
.PP
\fBnvme-list-ns\fR(1)
.RS 4
List all nvme namespaces
.RE
.PP
\fBnvme-list\fR(1)
.RS 4
List all nvme controllers
.RE
.PP
\fBnvme-list-ctrl\fR(1)
.RS 4
List controller in NVMe subsystem
.RE
.PP
\fBnvme-read\fR(1)
.RS 4
Issue IO Read Command
.RE
.PP
\fBnvme-write\fR(1)
.RS 4
Issue IO Write Command
.RE
.PP
\fBnvme-write-zeroes\fR(1)
.RS 4
Issue IO Write Zeroes Command
.RE
.PP
\fBnvme-write-uncor\fR(1)
.RS 4
Issue IO Write Uncorrectable Command
.RE
.PP
\fBnvme-resv-acquire\fR(1)
.RS 4
Acquire Namespace Reservation
.RE
.PP
\fBnvme-resv-register\fR(1)
.RS 4
Register Namespace Reservation
.RE
.PP
\fBnvme-resv-release\fR(1)
.RS 4
Release Namespace Reservation
.RE
.PP
\fBnvme-resv-report\fR(1)
.RS 4
Report Reservation Capabilities
.RE
.PP
\fBnvme-security-recv\fR(1)
.RS 4
Security Receive
.RE
.PP
\fBnvme-security-send\fR(1)
.RS 4
Security Send
.RE
.PP
\fBnvme-set-feature\fR(1)
.RS 4
Set Feature
.RE
.PP
\fBnvme-show-regs\fR(1)
.RS 4
Show NVMe Controller Registers
.RE
.PP
\fBnvme-discover\fR(1)
.RS 4
Send Get Log Page request to Discovery Controller
.RE
.PP
\fBnvme-connect\fR(1)
.RS 4
Connect to an NVMe\-over\-Fabrics subsystem
.RE
.SH "FURTHER DOCUMENTATION"
.sp
See the freely available references on the \m[blue]\fBOfficial NVM\-Express Site\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTHORS"
.sp
This is written and maintained by \m[blue]\fBKeith Busch\fR\m[]\&\s-2\u[2]\d\s+2\&.
.SH "REPORTING BUGS"
.sp
Patches and issues may be submitted to the official repository at \m[blue]\fBhttps://github\&.com/linux\-nvme/nvme\-cli\fR\m[] or the Linux NVMe mailing list \m[blue]\fBlinux\-nvme\fR\m[]\&\s-2\u[3]\d\s+2
.SH "NVME"
.sp
Part of the nvme suite
.SH "NOTES"
.IP " 1." 4
Official NVM-Express Site
.RS 4
\%http://nvmexpress.org
.RE
.IP " 2." 4
Keith Busch
.RS 4
\%mailto:keith.busch@intel.com
.RE
.IP " 3." 4
linux-nvme
.RS 4
\%mailto:linux-nvme@lists.infradead.org
.RE
