'\" t
.\"     Title: nvme-micron-id-ctrl
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/10/2026
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-MICRON\-ID\-CT" "1" "03/10/2026" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-micron-id-ctrl \- Send NVMe Identify Controller with Micron vendor\-specific fields
.SH "SYNOPSIS"
.sp
.nf
\fInvme micron id\-ctrl\fR <device> [\-\-output\-format=<fmt> | \-o <fmt>]
.fi
.SH "DESCRIPTION"
.sp
For the NVMe device given, sends an identify controller command and provides the result with Micron vendor\-specific fields decoded\&.
.sp
The <device> parameter is mandatory and may be either the NVMe character device (ex: /dev/nvme0), or a namespace block device (ex: /dev/nvme0n1)\&.
.sp
This command extends the standard Identify Controller output with Micron\-specific fields:
.PP
PMS (Power Measurement Support)
.RS 4
Bit 21 of CTRATT (Controller Attributes)\&. Indicates whether the controller supports power measurement\&.
.RE
.PP
IPMSR (Interval Power Measurement Sample Rate)
.RS 4
Located at bytes 392\-393 in the Identify Controller reserved area\&. Specifies the sample rate for interval power measurement\&.
.RE
.PP
MSMT (Maximum Stop Measurement Time)
.RS 4
Located at bytes 394\-395 in the Identify Controller reserved area\&. Specifies the maximum time to stop power measurement\&.
.RE
.SH "OPTIONS"
.PP
\-o <fmt>, \-\-output\-format=<fmt>
.RS 4
Set the reporting format to
\fInormal\fR
or
\fIjson\fR\&. Default is
\fInormal\fR\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Display Identify Controller in human\-readable format:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme micron id\-ctrl /dev/nvme0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Display Identify Controller in JSON format:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme micron id\-ctrl /dev/nvme0 \-o json
.fi
.if n \{\
.RE
.\}
.RE
.SH "NVME"
.sp
Part of the nvme\-user suite
