'\" t
.\"     Title: nvme-lnvm-id-ns
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-LNVM\-ID\-NS" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-id-ns \- Identify Geometry for LightNVM NVMe device
.SH "SYNOPSIS"
.sp
.nf
\fInvme lnvm\-id\-ns\fR <device> [\-\-namespace\-id=<nsid> | \-n <nsid>]
                        [\-\-force | \-f]
                        [\-\-raw\-binary | \-b]
                        [\-\-human\-readable | \-H]
.fi
.SH "DESCRIPTION"
.sp
Send an Identify Geometry command to the given LightNVM device, returns properties of the specified namespace in either human\-readable or binary format\&.
.SH "OPTIONS"
.PP
\-\-namespace\-id=<nsid>, \-n <nsid>
.RS 4
Retrieve the geometry from the selected namespace\&.
.RE
.PP
\-\-force, \-f
.RS 4
Try to read the data and assume it is a LightNVM device
.RE
.PP
\-\-raw\-binary, \-b
.RS 4
Output the raw output
.RE
.PP
\-\-human\-readable, \-H
.RS 4
Output the status in human readable format
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Retrieve the geometry from nvme0
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-id\-ns /dev/nvme0 \-n 1
.fi
.if n \{\
.RE
.\}
.SH "NVME"
.sp
Part of the nvme\-user suite
