'\" t
.\"     Title: nvme-connect-all
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 04/17/2026
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-CONNECT\-ALL" "1" "04/17/2026" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-connect-all \- Discover and Connect to Fabrics controllers\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme connect\-all\fR
                        [\-\-raw=<filename> | \-r <filename>]
                        [\-\-device=<device> | \-d <device>]
                        [\-\-config=<filename> | \-J <cfg>]
                        [\-\-persistent | \-p] [\-\-quiet]
                        [\-\-dump\-config | \-O] [\-\-nbft] [\-\-no\-nbft]
                        [\-\-nbft\-path=<STR>] [\-\-context=<STR>]
                        [<fabrics\-options>]
                        [<global\-options>]
.fi
.SH "DESCRIPTION"
.sp
Send one or more Discovery requests to a NVMe over Fabrics Discovery Controller, and create controllers for the returned discovery records\&.
.sp
If no parameters are given, then \fInvme connect\-all\fR will attempt to find a /usr/local/etc/nvme/discovery\&.conf file to use to supply a list of connect\-all commands to run\&. If no /usr/local/etc/nvme/discovery\&.conf file exists, the command will quit with an error\&.
.sp
Otherwise a specific Discovery Controller should be specified using the \-\-transport, \-\-traddr and if necessary the \-\-trsvcid and a Discovery request will be sent to the specified Discovery Controller\&.
.sp
See the documentation for the nvme\-discover(1) command for further background\&.
.SH "OPTIONS"
.PP
\-r <filename>, \-\-raw=<filename>
.RS 4
This field will take the output of the
\fInvme connect\-all\fR
command and dump it to a raw binary file\&. By default
\fInvme connect\-all\fR
will dump the output to stdout\&.
.RE
.PP
\-d <device>, \-\-device=<device>
.RS 4
This field takes a device as input\&. It must be a persistent device associated with a Discovery Controller previously created by the command "connect\-all" or "discover"\&. <device> follows the format nvme*, eg\&. nvme0, nvme1\&.
.RE
.PP
\-J <filename>, \-\-config=<filename>
.RS 4
Use the specified JSON configuration file instead of the default /usr/local/etc/nvme/config\&.json file or
\fInone\fR
to not read in an existing configuration file\&. The JSON configuration file format is documented in
\m[blue]\fBhttps://github\&.com/linux\-nvme/nvme\-cli/blob/master/libnvme/doc/config\-schema\&.json\fR\m[]
.RE
.PP
\-p, \-\-persistent
.RS 4
Don\(cqt remove the discovery controller after retrieving the discovery log page\&.
.RE
.PP
\-\-quiet
.RS 4
Suppress error messages\&.
.RE
.PP
\-O, \-\-dump\-config
.RS 4
Print out resulting JSON configuration file to stdout\&.
.RE
.PP
\-\-nbft
.RS 4
Only look at NBFT tables
.RE
.PP
\-\-no\-nbft
.RS 4
Do not look at NBFT tables
.RE
.PP
\-\-nbft\-path=<STR>
.RS 4
Use a user\-defined path to the NBFT tables
.RE
.PP
\-\-context <STR>
.RS 4
Set the execution context to <STR>\&. This allows to coordinate the management of the global resources\&.
.RE
.SH "FABRICS OPTIONS"
.sp
The following options are common to NVMe over Fabrics commands such as nvme connect:
.PP
\-a <traddr>, \-\-traddr=<traddr>
.RS 4
Specify the network address of the controller\&. For transports using IP addressing (e\&.g\&. rdma, tcp), this should be an IP address\&.
.RE
.PP
\-\-concat
.RS 4
Enable secure concatenation (TCP)\&.
.RE
.PP
\-c <#>, \-\-reconnect\-delay=<#>
.RS 4
Set the delay in seconds before reconnect is attempted after a connection loss\&.
.RE
.PP
\-C <secret>, \-\-dhchap\-ctrl\-secret=<secret>
.RS 4
Controller authentication secret for bi\-directional authentication\&. If not specified, bi\-directional authentication is not attempted\&.
.RE
.PP
\-S <secret>, \-\-dhchap\-secret=<secret>
.RS 4
Host authentication secret (DH\-HMAC\-CHAP)\&. Must be provided in ASCII format as defined in the NVMe specification\&.
.RE
.PP
\-\-disable\-sqflow
.RS 4
Disable submission queue flow control\&.
.RE
.PP
\-G, \-\-data\-digest
.RS 4
Enable data digest generation/verification (TCP)\&.
.RE
.PP
\-D, \-\-duplicate\-connect
.RS 4
Allow duplicate connections to the same subsystem\&.
.RE
.PP
\-g, \-\-hdr\-digest
.RS 4
Enable header digest generation/verification (TCP)\&.
.RE
.PP
\-f <iface>, \-\-host\-iface=<iface>
.RS 4
Specify the network interface to use for the connection\&.
.RE
.PP
\-I <hostid>, \-\-hostid=<hostid>
.RS 4
Specify the host UUID\&.
.RE
.PP
\-q <hostnqn>, \-\-hostnqn=<hostnqn>
.RS 4
Override the default host NQN\&.
.RE
.PP
\-w <traddr>, \-\-host\-traddr=<traddr>
.RS 4
Specify the source address on the host side of the connection\&.
.RE
.PP
\-k <#>, \-\-keep\-alive\-tmo=<#>
.RS 4
Set the keep\-alive timeout in seconds\&.
.RE
.PP
\-\-keyring=<keyring>
.RS 4
Keyring to use for TLS key lookup\&.
.RE
.PP
\-n <subnqn>, \-\-nqn=<subnqn>
.RS 4
Specify the NVMe subsystem NQN to connect to\&.
.RE
.PP
\-i <#>, \-\-nr\-io\-queues=<#>
.RS 4
Number of I/O queues to create\&.
.RE
.PP
\-P <#>, \-\-nr\-poll\-queues=<#>
.RS 4
Number of polling queues to create\&.
.RE
.PP
\-W <#>, \-\-nr\-write\-queues=<#>
.RS 4
Number of write queues to create\&.
.RE
.PP
\-Q <#>, \-\-queue\-size=<#>
.RS 4
Queue depth for I/O queues\&.
.RE
.PP
\-l <#>, \-\-ctrl\-loss\-tmo=<#>
.RS 4
Maximum time in seconds to retry reconnect attempts after controller loss\&.
.RE
.PP
\-s <trsvcid>, \-\-trsvcid=<trsvcid>
.RS 4
Transport service identifier (e\&.g\&. TCP/rdma port)\&. Default is 4420 for RDMA\&.
.RE
.PP
\-T <#>, \-\-tos=<#>
.RS 4
Type of service value for the connection (TCP)\&.
.RE
.PP
\-t <trtype>, \-\-transport=<trtype>
.RS 4
Specify the transport type\&. Supported values include:
.RE
.sp
+
.TS
allbox tab(:);
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
.sp
Value
T}:T{
.sp
Description
T}
T{
.sp
rdma
T}:T{
.sp
RDMA (RoCE, iWARP, InfiniBand)
T}
T{
.sp
tcp
T}:T{
.sp
TCP/IP
T}
T{
.sp
fc
T}:T{
.sp
Fibre Channel (\fBexperimental\fR)
T}
T{
.sp
loop
T}:T{
.sp
Local loopback transport
T}
.TE
.sp 1
.PP
\-\-tls
.RS 4
Enable TLS encryption (TCP)\&.
.RE
.PP
\-\-tls\-key=<tls\-key>
.RS 4
TLS key for the connection\&. It is recommended to preload keys into the system keyring instead of passing them via the command line\&.
.RE
.PP
\-\-tls\-key\-identity=<identity>
.RS 4
Identity associated with the TLS key\&.
.RE
.SH "GLOBAL OPTIONS"
.sp
The following options are defined at the top\-level nvme command and are available to this subcommand:
.PP
\-\-dry\-run
.RS 4
Print the command that would be executed, but do not actually execute it\&.
.RE
.PP
\-\-no\-ioctl\-probing
.RS 4
Disable probing for 64\-bit IOCTL support\&.
.RE
.PP
\-\-no\-retries
.RS 4
Disable retry logic on transient errors\&.
.RE
.PP
\-o <fmt>, \-\-output\-format=<fmt>
.RS 4
Set the reporting format to
\fInormal\fR,
\fItabular, \*(Aqjson\fR, or
\fIbinary\fR\&. Only one output format may be used at a time\&.
.RE
.PP
\-\-output\-format\-version=<version>
.RS 4
Select the output format version\&. Version
\fI1\fR
uses the original field naming, while version
\fI2\fR
(default) provides more consistent and script\-friendly field names\&.
.RE
.PP
\-\-timeout=<ms>
.RS 4
Set the timeout for the command in milliseconds\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Increase the level of detail in the output\&. May be specified multiple times to further increase verbosity\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Connect to all records returned by the Discover Controller with IP4 address 192\&.168\&.1\&.3 for all resources allocated for NVMe Host name host1\-rogue\-nqn on the RDMA network\&. Port 4420 is used by default:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme connect\-all \-\-transport=rdma \-\-traddr=192\&.168\&.1\&.3 \e
\-\-hostnqn=host1\-rogue\-nqn
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Issue a
\fInvme connect\-all\fR
command using the default system defined NBFT tables:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme connect\-all \-\-nbft
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Issue a
\fInvme connect\-all\fR
command with a user\-defined path for the NBFT table:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme connet\-all \-\-nbft\-path=/sys/firmware/acpi/tables/NBFT1
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Issue a
\fInvme connect\-all\fR
command using a /usr/local/etc/nvme/discovery\&.conf file:
.sp
.if n \{\
.RS 4
.\}
.nf
# Machine default \*(Aqnvme discover\*(Aq commands\&. Query the
# Discovery Controller\*(Aqs two ports (some resources may only
# be accessible on a single port)\&. Note an official
# nqn (Host) name defined in the NVMe specification is being used
# in this example\&.
\-t rdma \-a 192\&.168\&.69\&.33 \-s 4420 \-q nqn\&.2014\-08\&.com\&.example:nvme:nvm\-subsystem\-sn\-d78432
\-t rdma \-a 192\&.168\&.1\&.4   \-s 4420 \-q nqn\&.2014\-08\&.com\&.example:nvme:nvm\-subsystem\-sn\-d78432

At the prompt type "nvme connect\-all"\&.
.fi
.if n \{\
.RE
.\}
.RE
.SH "SEE ALSO"
.sp
nvme\-discover(1) nvme\-connect(1)
.SH "NVME"
.sp
Part of the nvme\-user suite
