'\" t
.\"     Title: nvme-resv-release
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-RESV\-RELEASE" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-resv-release \- Release an nvme reservation
.SH "SYNOPSIS"
.sp
.nf
\fInvme resv\-release\fR <device>
.fi
.SH "DESCRIPTION"
.sp
The Reservation Release command is used to release or clear a reservation held on a namespace\&.
.SH "OPTIONS"
.PP
\-n <nsid>, \-\-namespace\-id=<nsid>
.RS 4
Override the nsid field\&. If using the admin character device, this parameter is required\&.
.RE
.PP
\-c <crkey>, \-\-crkey=<crkey>
.RS 4
Current Reservation Key: If the Reservation Register Action is 001b (i\&.e\&., Unregister Reservation Key) or 010b (i\&.e\&., Replace Reservation Key), then this field contains the current reservation key associated with the host\&. For all other Reservation Register Action values, this field is reserved\&. The controller ignores the value of this field when the Ignore Existing Key (IEKEY) bit is set to \(oq1\(cq\&.
.RE
.PP
\-t <rtype>, \-\-rtyep=<rtype>
.RS 4
Reservation Type: This field specifies the type of reservation to be created\&.
.TS
allbox tab(:);
lt lt
lt lt
lt lt
lt lt
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
Value
T}:T{
Definition
T}
T{
0h
T}:T{
Reserved
T}
T{
1h
T}:T{
Write Exclusive Reservation
T}
T{
2h
T}:T{
Exclusive Access Reservation
T}
T{
3h
T}:T{
Write Exclusive \- Registrants Only Reservation
T}
T{
4h
T}:T{
Exclusive Access \- Registrants Only Reservation
T}
T{
5h
T}:T{
Write Exclusive \- All Registrants Reservation
T}
T{
6h
T}:T{
Exclusive Access \- All Registrants Reservation
T}
T{
07h\-FFh
T}:T{
Reserved
T}
.TE
.sp 1
.RE
.PP
\-a <rrela>, \-\-rrela=<rrela>
.RS 4
Reservation Release Action: This field specifies the registration action that is performed by the command\&.
.TS
allbox tab(:);
lt lt
lt lt
lt lt
lt lt.
T{
Value
T}:T{
Definition
T}
T{
0
T}:T{
Release
T}
T{
1
T}:T{
Clear
T}
T{
2\-7
T}:T{
Reserved
T}
.TE
.sp 1
.RE
.PP
\-i, \-\-iekey
.RS 4
Ignore Existing Key: If this bit is set to a
\fI1\fR, then the Current Reservation Key (CRKEY) check is disabled and the command shall succeed regardless of the CRKEY field value\&.
.sp
Indicator option, defaults to
\fI0\fR\&.
.RE
.SH "EXAMPLES"
.sp
No examples yet
.SH "NVME"
.sp
Part of the nvme\-user suite
