'\" t
.\"     Title: nvme-resv-register
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-RESV\-REGISTER" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-resv-register \- Register an nvme reservation
.SH "SYNOPSIS"
.sp
.nf
\fInvme resv\-register\fR <device>
.fi
.SH "DESCRIPTION"
.sp
The Reservation Register command is used to register, unregister, or replace a reservation key\&.
.SH "OPTIONS"
.PP
\-n <nsid>, \-\-namespace\-id=<nsid>
.RS 4
Override the nsid field\&. If using the admin character device, this parameter is required\&.
.RE
.PP
\-c <crkey>, \-\-crkey=<crkey>
.RS 4
Current Reservation Key: If the Reservation Register Action is 001b (i\&.e\&., Unregister Reservation Key) or 010b (i\&.e\&., Replace Reservation Key), then this field contains the current reservation key associated with the host\&. For all other Reservation Register Action values, this field is reserved\&. The controller ignores the value of this field when the Ignore Existing Key (IEKEY) bit is set to \(oq1\(cq\&.
.RE
.PP
\-k <nrkey>, \-\-nrkey=<nrkey>
.RS 4
New Reservation Key: If the Reservation Register Action is 000b (i\&.e\&., Register Reservation Key) or 010b (i\&.e\&., Replace Reservation Key), then this field contains the new reservation key associated with the host\&. For all other Reservation Register Action values, this field is reserved\&.
.RE
.PP
\-p <cptpl>, \-\-cptpl=<cptpl>
.RS 4
Change Persist Through Power Loss State: This field allows the Persist Through Power Loss state associated with the namespace to be modified as a side effect of processing this command\&.
.TS
allbox tab(:);
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
Value
T}:T{
Definition
T}
T{
0
T}:T{
No change to PTPL state
T}
T{
1
T}:T{
Reserved
T}
T{
2
T}:T{
Set PTPL state to \(oq0\(cq\&. Reservations are released and registrants are cleared on a power on\&.
T}
T{
3
T}:T{
Set PTPL state to \(oq1\(cq\&. Reservations and registrants persist across a power loss\&.
T}
.TE
.sp 1
.RE
.PP
\-a <rrega>, \-\-rrega=<rrega>
.RS 4
Reservation Register Action: This field specifies the registration action that is performed by the command\&.
.TS
allbox tab(:);
lt lt
lt lt
lt lt
lt lt
lt lt.
T{
Value
T}:T{
Definition
T}
T{
0
T}:T{
Register Reservation Key
T}
T{
1
T}:T{
Unregister Reservation Key
T}
T{
2
T}:T{
Replace Reservation Key
T}
T{
3\-7
T}:T{
Reserved
T}
.TE
.sp 1
.RE
.PP
\-i, \-\-iekey
.RS 4
Ignore Existing Key: If this bit is set to a
\fI1\fR, then the Current Reservation Key (CRKEY) check is disabled and the command shall succeed regardless of the CRKEY field value\&.
.sp
Indicator option, defaults to
\fI0\fR\&.
.RE
.SH "EXAMPLES"
.sp
No examples yet
.SH "NVME"
.sp
Part of the nvme\-user suite
