'\" t
.\"     Title: nvme-lnvm-diag-set-bbtbl
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-LNVM\-DIAG\-SE" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-diag-set-bbtbl \- Set a block state in the bad block table
.SH "SYNOPSIS"
.sp
.nf
\fInvme lnvm\-diag\-set\-bbtbl\fR [\-\-namespace\-id=<NUM> | \-n <NUM>]
                        [\-\-channel\-id=<CHID> | \-c <CHID>]
                        [\-\-lun\-id=<LUNID> | \-l <LUNID>]
                        [\-\-plane\-id=<PLANEID> | \-p <PLANEID>]
                        [\-\-block\-id=<BLKID> | \-b <BLKID>]
                        [\-\-value=<NUM> | \-v <NUM>]
.fi
.SH "DESCRIPTION"
.sp
Set the bad block table for a given channel, lun, plane and block with value v\&.
.sp
For each block available, the status byte is read as follows:
.sp
0: Good block 1: Bad block 2: Grown bad block 4: Device reserved block 8: Host\-side reserved block 16: Media managed reserved block
.SH "OPTIONS"
.PP
\-\-namespace\-id=<NUM>, \-n <NUM>
.RS 4
Namespace id to use
.RE
.PP
\-\-channel\-id, \-c
.RS 4
Channel id
.RE
.PP
\-\-lun\-id, \-l
.RS 4
LUN id
.RE
.PP
\-\-plane\-id, \-p
.RS 4
Plane id
.RE
.PP
\-\-block\-id, \-b
.RS 4
Block id
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Set channel 0, lun 0, plane 0, block 10 to bad block value 2 (grown bad) on physical device /dev/nvme0
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-diag\-set\-bbtbl /dev/nvme0 \-c 0 \-l 0 \-p 0 \-b 10 \-v 2
.fi
.if n \{\
.RE
.\}
.SH "NVME"
.sp
Part of the nvme\-user suite
