'\" t
.\"     Title: nvme-lnvm-remove
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-LNVM\-REMOVE" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-remove \- Remove an initialized LightNVM target\&.
.SH "SYNOPSIS"
.sp
.nf
\fInvme lnvm\-remove\fR [\-\-target\-name=<TARGET> | \-n <TARGET>]
.fi
.SH "DESCRIPTION"
.sp
Remove an initialized target\&.
.sp
The target name is the name of which the media is exposed as in /dev/<TARGET>
.SH "OPTIONS"
.PP
\-\-target\-name=<TARGET>, \-n <TARGET>
.RS 4
Target name of the device to initialize\&. For example: target0\&.
.RE
.SH "EXAMPLES"
.sp
None yet
.SH "NVME"
.sp
Part of the nvme\-user suite
