'\" t
.\"     Title: nvme-intel-internal-log
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 10/20/2020
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-INTEL\-INTERNA" "1" "10/20/2020" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-intel-internal-log \- Retrieve Intel device\*(Aqs internal log and save to file\&.
.SH "SYNOPSIS"
.sp
.nf
\*(Aqnvme intel internal\-log \*(Aq <device> [\-\-log=<NUM>, \-l <NUM>]
                [\-\-region=<NUM>, r <NUM>]
                [\-\-nlognum=<NUM>, m <NUM>]
                [\-\-namespace\-id=<NUM>, \-n <NUM>]
                [\-\-output\-file=<FILE>, \-o <FILE>]
.fi
.SH "DESCRIPTION"
.sp
For the NVMe device given, sends the Intel vendor unique device log request and saves the result to a file\&.
.sp
The <device> parameter is mandatory and may be either the NVMe character device (ex: /dev/nvme0), or a namespace block device (ex: /dev/nvme0n1)\&. If using the character device, the namespace id parameter is mandatory\&.
.sp
This will only work on Intel devices supporting this feature which includes (but not limited to) all the Intel DC P3xxx family of controllers\&. Results for any other device are undefined\&.
.SH "OPTIONS"
.PP
\-l <NUM>, \-\-log=<NUM>
.RS 4
Log type: 0, 1, or 2 for nlog, event log, and assert log, respectively\&.
.RE
.PP
\-n <NUM>, \-\-namespace\-id=<NUM>
.RS 4
Namespace to use\&.
.RE
.PP
\-o <FILE>, \-\-output\-file=<FILE>
.RS 4
Output file; defaults to device name provided
.RE
.PP
\-r <NUM>, \-\-region=<NUM>
.RS 4
Select which core region to retrieve the log from\&. \-1 for all available, if supported by the device\&.
.RE
.PP
\-m <NUM>, \-\-nlognum=<NUM>
.RS 4
When used with
\fInlog\fR, this specifies which nlog to read\&. \-1 for all, if supported by the device\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gets the nlog from the device and saves to default file:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel internal\-log /dev/nvme0 \-\-namespace\-id=1 \-\-log=0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Gets the event log from the device and saves to defined file:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel internal\-log /dev/nvme0 \-\-namespace\-id=1 \-\-log=1 \-\-output\-file=MyAwesomeEventLog
.fi
.if n \{\
.RE
.\}
.RE
.SH "NVME"
.sp
Part of the nvme\-user suite
