'\" t
.\"     Title: nvme-lnvm-factory
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/17/2016
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.\"
.TH "NVME\-LNVM\-FACTORY" "1" "11/17/2016" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-lnvm-factory \- Factory reset a LightNVM device
.SH "SYNOPSIS"
.sp
.nf
\fInvme lnvm\-factory\fR [\-\-device\-name=<DEVICE> | \-d <DEVICE>]
                        [\-\-erase\-only\-marked | \-e]
                        [\-\-clear\-host\-side\-blks | \-s]
                        [\-\-clear\-bb\-blks | \-b]
.fi
.SH "DESCRIPTION"
.sp
Instantiate a target on top of a LightNVM enabled device\&. This exposes the physical for the user to use\&.
.SH "OPTIONS"
.PP
\-\-device\-name=<DEVICE>, \-d <DEVICE>
.RS 4
Device name to factory initialize
.RE
.PP
\-\-erase\-only\-marked, \-e
.RS 4
Erases only blocks that are marked in the bad block list
.RE
.PP
\-\-clear\-host\-side\-blks, \-s
.RS 4
Remove host\-side bad block marks\&. This clear the media manager registration
.RE
.PP
\-\-clear\-bb\-blks, \-b
.RS 4
Removes the grown bad block marks\&. Allowing them to be rediscovered\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Factory reset of device nvme0n1
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-factory \-d nvme0n1
.fi
.if n \{\
.RE
.\}
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Complete factory reset of device nvme0n1
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme lnvm\-factory \-d nvme0n1 \-s \-b
.fi
.if n \{\
.RE
.\}
.SH "NVME"
.sp
Part of the nvme\-user suite
