---
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of nvme.
# Copyright (c) 2026 SUSE LLC
#
# Authors: Daniel Wagner <dwagner@suse.de>

name: Codecov

on:
  push:
    branches: [master]

jobs:
  code-coverage:
    if: github.repository == 'linux-nvme/nvme-cli'
    name: code coverage
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: ghcr.io/linux-nvme/debian:latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Mark repo as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: build
        run: |
          scripts/build.sh coverage
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        env:
          CODECOV_WORKING_DIR: ${{ github.workspace }}
        with:
          root_dir: ${{ github.workspace }}
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
